/*
 * This file is generated by jOOQ.
 */
package me.aa07.paradise.taskdaemon.database.gamedb.tables.records;


import java.time.LocalDateTime;

import me.aa07.paradise.taskdaemon.database.gamedb.tables.Ip2group;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ip2groupRecord extends UpdatableRecordImpl<Ip2groupRecord> implements Record3<UInteger, LocalDateTime, UInteger> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>paradb_unmodified.ip2group.ip</code>.
     */
    public void setIp(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>paradb_unmodified.ip2group.ip</code>.
     */
    public UInteger getIp() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>paradb_unmodified.ip2group.date</code>.
     */
    public void setDate(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>paradb_unmodified.ip2group.date</code>.
     */
    public LocalDateTime getDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>paradb_unmodified.ip2group.groupstr</code>.
     */
    public void setGroupstr(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>paradb_unmodified.ip2group.groupstr</code>.
     */
    public UInteger getGroupstr() {
        return (UInteger) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<UInteger, LocalDateTime, UInteger> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<UInteger, LocalDateTime, UInteger> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<UInteger> field1() {
        return Ip2group.IP2GROUP.IP;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return Ip2group.IP2GROUP.DATE;
    }

    @Override
    public Field<UInteger> field3() {
        return Ip2group.IP2GROUP.GROUPSTR;
    }

    @Override
    public UInteger component1() {
        return getIp();
    }

    @Override
    public LocalDateTime component2() {
        return getDate();
    }

    @Override
    public UInteger component3() {
        return getGroupstr();
    }

    @Override
    public UInteger value1() {
        return getIp();
    }

    @Override
    public LocalDateTime value2() {
        return getDate();
    }

    @Override
    public UInteger value3() {
        return getGroupstr();
    }

    @Override
    public Ip2groupRecord value1(UInteger value) {
        setIp(value);
        return this;
    }

    @Override
    public Ip2groupRecord value2(LocalDateTime value) {
        setDate(value);
        return this;
    }

    @Override
    public Ip2groupRecord value3(UInteger value) {
        setGroupstr(value);
        return this;
    }

    @Override
    public Ip2groupRecord values(UInteger value1, LocalDateTime value2, UInteger value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Ip2groupRecord
     */
    public Ip2groupRecord() {
        super(Ip2group.IP2GROUP);
    }

    /**
     * Create a detached, initialised Ip2groupRecord
     */
    public Ip2groupRecord(UInteger ip, LocalDateTime date, UInteger groupstr) {
        super(Ip2group.IP2GROUP);

        setIp(ip);
        setDate(date);
        setGroupstr(groupstr);
    }
}
