/*
 * This file is generated by jOOQ.
 */
package me.aa07.paradise.taskdaemon.database.authentik.tables;


import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import me.aa07.paradise.taskdaemon.database.authentik.Indexes;
import me.aa07.paradise.taskdaemon.database.authentik.Keys;
import me.aa07.paradise.taskdaemon.database.authentik.Public;
import me.aa07.paradise.taskdaemon.database.authentik.tables.records.AuthentikStagesAuthenticatorValidateAuthenticatorvalida3e25Record;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthentikStagesAuthenticatorValidateAuthenticatorvalida3e25 extends TableImpl<AuthentikStagesAuthenticatorValidateAuthenticatorvalida3e25Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>public.authentik_stages_authenticator_validate_authenticatorvalida3e25</code>
     */
    public static final AuthentikStagesAuthenticatorValidateAuthenticatorvalida3e25 AUTHENTIK_STAGES_AUTHENTICATOR_VALIDATE_AUTHENTICATORVALIDA3E25 = new AuthentikStagesAuthenticatorValidateAuthenticatorvalida3e25();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuthentikStagesAuthenticatorValidateAuthenticatorvalida3e25Record> getRecordType() {
        return AuthentikStagesAuthenticatorValidateAuthenticatorvalida3e25Record.class;
    }

    /**
     * The column
     * <code>public.authentik_stages_authenticator_validate_authenticatorvalida3e25.id</code>.
     */
    public final TableField<AuthentikStagesAuthenticatorValidateAuthenticatorvalida3e25Record, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column
     * <code>public.authentik_stages_authenticator_validate_authenticatorvalida3e25.authenticatorvalidatestage_id</code>.
     */
    public final TableField<AuthentikStagesAuthenticatorValidateAuthenticatorvalida3e25Record, UUID> AUTHENTICATORVALIDATESTAGE_ID = createField(DSL.name("authenticatorvalidatestage_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column
     * <code>public.authentik_stages_authenticator_validate_authenticatorvalida3e25.stage_id</code>.
     */
    public final TableField<AuthentikStagesAuthenticatorValidateAuthenticatorvalida3e25Record, UUID> STAGE_ID = createField(DSL.name("stage_id"), SQLDataType.UUID.nullable(false), this, "");

    private AuthentikStagesAuthenticatorValidateAuthenticatorvalida3e25(Name alias, Table<AuthentikStagesAuthenticatorValidateAuthenticatorvalida3e25Record> aliased) {
        this(alias, aliased, null);
    }

    private AuthentikStagesAuthenticatorValidateAuthenticatorvalida3e25(Name alias, Table<AuthentikStagesAuthenticatorValidateAuthenticatorvalida3e25Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased
     * <code>public.authentik_stages_authenticator_validate_authenticatorvalida3e25</code>
     * table reference
     */
    public AuthentikStagesAuthenticatorValidateAuthenticatorvalida3e25(String alias) {
        this(DSL.name(alias), AUTHENTIK_STAGES_AUTHENTICATOR_VALIDATE_AUTHENTICATORVALIDA3E25);
    }

    /**
     * Create an aliased
     * <code>public.authentik_stages_authenticator_validate_authenticatorvalida3e25</code>
     * table reference
     */
    public AuthentikStagesAuthenticatorValidateAuthenticatorvalida3e25(Name alias) {
        this(alias, AUTHENTIK_STAGES_AUTHENTICATOR_VALIDATE_AUTHENTICATORVALIDA3E25);
    }

    /**
     * Create a
     * <code>public.authentik_stages_authenticator_validate_authenticatorvalida3e25</code>
     * table reference
     */
    public AuthentikStagesAuthenticatorValidateAuthenticatorvalida3e25() {
        this(DSL.name("authentik_stages_authenticator_validate_authenticatorvalida3e25"), null);
    }

    public <O extends Record> AuthentikStagesAuthenticatorValidateAuthenticatorvalida3e25(Table<O> child, ForeignKey<O, AuthentikStagesAuthenticatorValidateAuthenticatorvalida3e25Record> key) {
        super(child, key, AUTHENTIK_STAGES_AUTHENTICATOR_VALIDATE_AUTHENTICATORVALIDA3E25);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.AUTHENTIK_STAGES_AUTHENTIC_AUTHENTICATORVALIDATESTAGE_AFF63C61, Indexes.AUTHENTIK_STAGES_AUTHENTIC_STAGE_ID_3C37CAC7);
    }

    @Override
    public Identity<AuthentikStagesAuthenticatorValidateAuthenticatorvalida3e25Record, Integer> getIdentity() {
        return (Identity<AuthentikStagesAuthenticatorValidateAuthenticatorvalida3e25Record, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<AuthentikStagesAuthenticatorValidateAuthenticatorvalida3e25Record> getPrimaryKey() {
        return Keys.AUTHENTIK_STAGES_AUTHENTICATOR_VALIDATE_AUTHENTICATORVALID_PKEY;
    }

    @Override
    public List<UniqueKey<AuthentikStagesAuthenticatorValidateAuthenticatorvalida3e25Record>> getUniqueKeys() {
        return Arrays.asList(Keys.AUTHENTIK_STAGES_AUTHENT_AUTHENTICATORVALIDATESTA_EFE8BF64_UNIQ);
    }

    @Override
    public List<ForeignKey<AuthentikStagesAuthenticatorValidateAuthenticatorvalida3e25Record, ?>> getReferences() {
        return Arrays.asList(Keys.AUTHENTIK_STAGES_AUTHENTICATOR_VALIDATE_AUTHENTICATORVALIDA3E25__AUTHENTIK_STAGES_AUT_AUTHENTICATORVALIDAT_AFF63C61_FK_AUTHENTIK, Keys.AUTHENTIK_STAGES_AUTHENTICATOR_VALIDATE_AUTHENTICATORVALIDA3E25__AUTHENTIK_STAGES_AUT_STAGE_ID_3C37CAC7_FK_AUTHENTIK);
    }

    private transient AuthentikStagesAuthenticatorValidateAuthenticatorvalida499c _authentikStagesAuthenticatorValidateAuthenticatorvalida499c;
    private transient AuthentikFlowsStage _authentikFlowsStage;

    public AuthentikStagesAuthenticatorValidateAuthenticatorvalida499c authentikStagesAuthenticatorValidateAuthenticatorvalida499c() {
        if (_authentikStagesAuthenticatorValidateAuthenticatorvalida499c == null)
            _authentikStagesAuthenticatorValidateAuthenticatorvalida499c = new AuthentikStagesAuthenticatorValidateAuthenticatorvalida499c(this, Keys.AUTHENTIK_STAGES_AUTHENTICATOR_VALIDATE_AUTHENTICATORVALIDA3E25__AUTHENTIK_STAGES_AUT_AUTHENTICATORVALIDAT_AFF63C61_FK_AUTHENTIK);

        return _authentikStagesAuthenticatorValidateAuthenticatorvalida499c;
    }

    public AuthentikFlowsStage authentikFlowsStage() {
        if (_authentikFlowsStage == null)
            _authentikFlowsStage = new AuthentikFlowsStage(this, Keys.AUTHENTIK_STAGES_AUTHENTICATOR_VALIDATE_AUTHENTICATORVALIDA3E25__AUTHENTIK_STAGES_AUT_STAGE_ID_3C37CAC7_FK_AUTHENTIK);

        return _authentikFlowsStage;
    }

    @Override
    public AuthentikStagesAuthenticatorValidateAuthenticatorvalida3e25 as(String alias) {
        return new AuthentikStagesAuthenticatorValidateAuthenticatorvalida3e25(DSL.name(alias), this);
    }

    @Override
    public AuthentikStagesAuthenticatorValidateAuthenticatorvalida3e25 as(Name alias) {
        return new AuthentikStagesAuthenticatorValidateAuthenticatorvalida3e25(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthentikStagesAuthenticatorValidateAuthenticatorvalida3e25 rename(String name) {
        return new AuthentikStagesAuthenticatorValidateAuthenticatorvalida3e25(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthentikStagesAuthenticatorValidateAuthenticatorvalida3e25 rename(Name name) {
        return new AuthentikStagesAuthenticatorValidateAuthenticatorvalida3e25(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, UUID, UUID> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
