/*
 * This file is generated by jOOQ.
 */
package me.aa07.paradise.taskdaemon.database.authentik.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import me.aa07.paradise.taskdaemon.database.authentik.Indexes;
import me.aa07.paradise.taskdaemon.database.authentik.Keys;
import me.aa07.paradise.taskdaemon.database.authentik.Public;
import me.aa07.paradise.taskdaemon.database.authentik.tables.records.AuthentikSourcesScimScimsourcegroupRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthentikSourcesScimScimsourcegroup extends TableImpl<AuthentikSourcesScimScimsourcegroupRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>public.authentik_sources_scim_scimsourcegroup</code>
     */
    public static final AuthentikSourcesScimScimsourcegroup AUTHENTIK_SOURCES_SCIM_SCIMSOURCEGROUP = new AuthentikSourcesScimScimsourcegroup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuthentikSourcesScimScimsourcegroupRecord> getRecordType() {
        return AuthentikSourcesScimScimsourcegroupRecord.class;
    }

    /**
     * The column <code>public.authentik_sources_scim_scimsourcegroup.id</code>.
     */
    public final TableField<AuthentikSourcesScimScimsourcegroupRecord, String> ID = createField(DSL.name("id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column
     * <code>public.authentik_sources_scim_scimsourcegroup.attributes</code>.
     */
    public final TableField<AuthentikSourcesScimScimsourcegroupRecord, JSONB> ATTRIBUTES = createField(DSL.name("attributes"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column
     * <code>public.authentik_sources_scim_scimsourcegroup.group_id</code>.
     */
    public final TableField<AuthentikSourcesScimScimsourcegroupRecord, UUID> GROUP_ID = createField(DSL.name("group_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column
     * <code>public.authentik_sources_scim_scimsourcegroup.source_id</code>.
     */
    public final TableField<AuthentikSourcesScimScimsourcegroupRecord, UUID> SOURCE_ID = createField(DSL.name("source_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column
     * <code>public.authentik_sources_scim_scimsourcegroup.external_id</code>.
     */
    public final TableField<AuthentikSourcesScimScimsourcegroupRecord, String> EXTERNAL_ID = createField(DSL.name("external_id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column
     * <code>public.authentik_sources_scim_scimsourcegroup.last_update</code>.
     */
    public final TableField<AuthentikSourcesScimScimsourcegroupRecord, OffsetDateTime> LAST_UPDATE = createField(DSL.name("last_update"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    private AuthentikSourcesScimScimsourcegroup(Name alias, Table<AuthentikSourcesScimScimsourcegroupRecord> aliased) {
        this(alias, aliased, null);
    }

    private AuthentikSourcesScimScimsourcegroup(Name alias, Table<AuthentikSourcesScimScimsourcegroupRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased
     * <code>public.authentik_sources_scim_scimsourcegroup</code> table
     * reference
     */
    public AuthentikSourcesScimScimsourcegroup(String alias) {
        this(DSL.name(alias), AUTHENTIK_SOURCES_SCIM_SCIMSOURCEGROUP);
    }

    /**
     * Create an aliased
     * <code>public.authentik_sources_scim_scimsourcegroup</code> table
     * reference
     */
    public AuthentikSourcesScimScimsourcegroup(Name alias) {
        this(alias, AUTHENTIK_SOURCES_SCIM_SCIMSOURCEGROUP);
    }

    /**
     * Create a <code>public.authentik_sources_scim_scimsourcegroup</code> table
     * reference
     */
    public AuthentikSourcesScimScimsourcegroup() {
        this(DSL.name("authentik_sources_scim_scimsourcegroup"), null);
    }

    public <O extends Record> AuthentikSourcesScimScimsourcegroup(Table<O> child, ForeignKey<O, AuthentikSourcesScimScimsourcegroupRecord> key) {
        super(child, key, AUTHENTIK_SOURCES_SCIM_SCIMSOURCEGROUP);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.AUTHENTIK_S_EXTERNA_05E346_IDX, Indexes.AUTHENTIK_SOURCES_SCIM_SCIMSOURCEGROUP_GROUP_ID_C59BDE52, Indexes.AUTHENTIK_SOURCES_SCIM_SCIMSOURCEGROUP_ID_F5FE9E43_LIKE, Indexes.AUTHENTIK_SOURCES_SCIM_SCIMSOURCEGROUP_SOURCE_ID_000FF364);
    }

    @Override
    public UniqueKey<AuthentikSourcesScimScimsourcegroupRecord> getPrimaryKey() {
        return Keys.AUTHENTIK_SOURCES_SCIM_SCIMSOURCEGROUP_PKEY;
    }

    @Override
    public List<UniqueKey<AuthentikSourcesScimScimsourcegroupRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.AUTHENTIK_SOURCES_SCIM_S_EXTERNAL_ID_SOURCE_ID_2FA367FB_UNIQ);
    }

    @Override
    public List<ForeignKey<AuthentikSourcesScimScimsourcegroupRecord, ?>> getReferences() {
        return Arrays.asList(Keys.AUTHENTIK_SOURCES_SCIM_SCIMSOURCEGROUP__AUTHENTIK_SOURCES_SC_GROUP_ID_C59BDE52_FK_AUTHENTIK, Keys.AUTHENTIK_SOURCES_SCIM_SCIMSOURCEGROUP__AUTHENTIK_SOURCES_SC_SOURCE_ID_000FF364_FK_AUTHENTIK);
    }

    private transient AuthentikCoreGroup _authentikCoreGroup;
    private transient AuthentikSourcesScimScimsource _authentikSourcesScimScimsource;

    public AuthentikCoreGroup authentikCoreGroup() {
        if (_authentikCoreGroup == null)
            _authentikCoreGroup = new AuthentikCoreGroup(this, Keys.AUTHENTIK_SOURCES_SCIM_SCIMSOURCEGROUP__AUTHENTIK_SOURCES_SC_GROUP_ID_C59BDE52_FK_AUTHENTIK);

        return _authentikCoreGroup;
    }

    public AuthentikSourcesScimScimsource authentikSourcesScimScimsource() {
        if (_authentikSourcesScimScimsource == null)
            _authentikSourcesScimScimsource = new AuthentikSourcesScimScimsource(this, Keys.AUTHENTIK_SOURCES_SCIM_SCIMSOURCEGROUP__AUTHENTIK_SOURCES_SC_SOURCE_ID_000FF364_FK_AUTHENTIK);

        return _authentikSourcesScimScimsource;
    }

    @Override
    public AuthentikSourcesScimScimsourcegroup as(String alias) {
        return new AuthentikSourcesScimScimsourcegroup(DSL.name(alias), this);
    }

    @Override
    public AuthentikSourcesScimScimsourcegroup as(Name alias) {
        return new AuthentikSourcesScimScimsourcegroup(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthentikSourcesScimScimsourcegroup rename(String name) {
        return new AuthentikSourcesScimScimsourcegroup(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthentikSourcesScimScimsourcegroup rename(Name name) {
        return new AuthentikSourcesScimScimsourcegroup(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<String, JSONB, UUID, UUID, String, OffsetDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
