/*
 * This file is generated by jOOQ.
 */
package me.aa07.paradise.taskdaemon.database.authentik.tables;


import java.util.Arrays;
import java.util.List;

import me.aa07.paradise.taskdaemon.database.authentik.Indexes;
import me.aa07.paradise.taskdaemon.database.authentik.Keys;
import me.aa07.paradise.taskdaemon.database.authentik.Public;
import me.aa07.paradise.taskdaemon.database.authentik.tables.records.AuthentikRbacInitialpermissionsPermissionsRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthentikRbacInitialpermissionsPermissions extends TableImpl<AuthentikRbacInitialpermissionsPermissionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>public.authentik_rbac_initialpermissions_permissions</code>
     */
    public static final AuthentikRbacInitialpermissionsPermissions AUTHENTIK_RBAC_INITIALPERMISSIONS_PERMISSIONS = new AuthentikRbacInitialpermissionsPermissions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuthentikRbacInitialpermissionsPermissionsRecord> getRecordType() {
        return AuthentikRbacInitialpermissionsPermissionsRecord.class;
    }

    /**
     * The column
     * <code>public.authentik_rbac_initialpermissions_permissions.id</code>.
     */
    public final TableField<AuthentikRbacInitialpermissionsPermissionsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column
     * <code>public.authentik_rbac_initialpermissions_permissions.initialpermissions_id</code>.
     */
    public final TableField<AuthentikRbacInitialpermissionsPermissionsRecord, Integer> INITIALPERMISSIONS_ID = createField(DSL.name("initialpermissions_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column
     * <code>public.authentik_rbac_initialpermissions_permissions.permission_id</code>.
     */
    public final TableField<AuthentikRbacInitialpermissionsPermissionsRecord, Integer> PERMISSION_ID = createField(DSL.name("permission_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private AuthentikRbacInitialpermissionsPermissions(Name alias, Table<AuthentikRbacInitialpermissionsPermissionsRecord> aliased) {
        this(alias, aliased, null);
    }

    private AuthentikRbacInitialpermissionsPermissions(Name alias, Table<AuthentikRbacInitialpermissionsPermissionsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased
     * <code>public.authentik_rbac_initialpermissions_permissions</code> table
     * reference
     */
    public AuthentikRbacInitialpermissionsPermissions(String alias) {
        this(DSL.name(alias), AUTHENTIK_RBAC_INITIALPERMISSIONS_PERMISSIONS);
    }

    /**
     * Create an aliased
     * <code>public.authentik_rbac_initialpermissions_permissions</code> table
     * reference
     */
    public AuthentikRbacInitialpermissionsPermissions(Name alias) {
        this(alias, AUTHENTIK_RBAC_INITIALPERMISSIONS_PERMISSIONS);
    }

    /**
     * Create a
     * <code>public.authentik_rbac_initialpermissions_permissions</code> table
     * reference
     */
    public AuthentikRbacInitialpermissionsPermissions() {
        this(DSL.name("authentik_rbac_initialpermissions_permissions"), null);
    }

    public <O extends Record> AuthentikRbacInitialpermissionsPermissions(Table<O> child, ForeignKey<O, AuthentikRbacInitialpermissionsPermissionsRecord> key) {
        super(child, key, AUTHENTIK_RBAC_INITIALPERMISSIONS_PERMISSIONS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.AUTHENTIK_RBAC_INITIALPERM_INITIALPERMISSIONS_ID_791926A4, Indexes.AUTHENTIK_RBAC_INITIALPERM_PERMISSION_ID_41D32761);
    }

    @Override
    public Identity<AuthentikRbacInitialpermissionsPermissionsRecord, Integer> getIdentity() {
        return (Identity<AuthentikRbacInitialpermissionsPermissionsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<AuthentikRbacInitialpermissionsPermissionsRecord> getPrimaryKey() {
        return Keys.AUTHENTIK_RBAC_INITIALPERMISSIONS_PERMISSIONS_PKEY;
    }

    @Override
    public List<UniqueKey<AuthentikRbacInitialpermissionsPermissionsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.AUTHENTIK_RBAC_INITIALPE_INITIALPERMISSIONS_ID_PE_F5A0E7EB_UNIQ);
    }

    @Override
    public List<ForeignKey<AuthentikRbacInitialpermissionsPermissionsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.AUTHENTIK_RBAC_INITIALPERMISSIONS_PERMISSIONS__AUTHENTIK_RBAC_INITI_INITIALPERMISSIONS_I_791926A4_FK_AUTHENTIK, Keys.AUTHENTIK_RBAC_INITIALPERMISSIONS_PERMISSIONS__AUTHENTIK_RBAC_INITI_PERMISSION_ID_41D32761_FK_AUTH_PERM);
    }

    private transient AuthentikRbacInitialpermissions _authentikRbacInitialpermissions;
    private transient AuthPermission _authPermission;

    public AuthentikRbacInitialpermissions authentikRbacInitialpermissions() {
        if (_authentikRbacInitialpermissions == null)
            _authentikRbacInitialpermissions = new AuthentikRbacInitialpermissions(this, Keys.AUTHENTIK_RBAC_INITIALPERMISSIONS_PERMISSIONS__AUTHENTIK_RBAC_INITI_INITIALPERMISSIONS_I_791926A4_FK_AUTHENTIK);

        return _authentikRbacInitialpermissions;
    }

    public AuthPermission authPermission() {
        if (_authPermission == null)
            _authPermission = new AuthPermission(this, Keys.AUTHENTIK_RBAC_INITIALPERMISSIONS_PERMISSIONS__AUTHENTIK_RBAC_INITI_PERMISSION_ID_41D32761_FK_AUTH_PERM);

        return _authPermission;
    }

    @Override
    public AuthentikRbacInitialpermissionsPermissions as(String alias) {
        return new AuthentikRbacInitialpermissionsPermissions(DSL.name(alias), this);
    }

    @Override
    public AuthentikRbacInitialpermissionsPermissions as(Name alias) {
        return new AuthentikRbacInitialpermissionsPermissions(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthentikRbacInitialpermissionsPermissions rename(String name) {
        return new AuthentikRbacInitialpermissionsPermissions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthentikRbacInitialpermissionsPermissions rename(Name name) {
        return new AuthentikRbacInitialpermissionsPermissions(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
