/*
 * This file is generated by jOOQ.
 */
package me.aa07.paradise.taskdaemon.database.authentik.tables;


import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import me.aa07.paradise.taskdaemon.database.authentik.Keys;
import me.aa07.paradise.taskdaemon.database.authentik.Public;
import me.aa07.paradise.taskdaemon.database.authentik.tables.records.AuthentikOutpostsKubernetesserviceconnectionRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthentikOutpostsKubernetesserviceconnection extends TableImpl<AuthentikOutpostsKubernetesserviceconnectionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>public.authentik_outposts_kubernetesserviceconnection</code>
     */
    public static final AuthentikOutpostsKubernetesserviceconnection AUTHENTIK_OUTPOSTS_KUBERNETESSERVICECONNECTION = new AuthentikOutpostsKubernetesserviceconnection();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuthentikOutpostsKubernetesserviceconnectionRecord> getRecordType() {
        return AuthentikOutpostsKubernetesserviceconnectionRecord.class;
    }

    /**
     * The column
     * <code>public.authentik_outposts_kubernetesserviceconnection.outpostserviceconnection_ptr_id</code>.
     */
    public final TableField<AuthentikOutpostsKubernetesserviceconnectionRecord, UUID> OUTPOSTSERVICECONNECTION_PTR_ID = createField(DSL.name("outpostserviceconnection_ptr_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column
     * <code>public.authentik_outposts_kubernetesserviceconnection.kubeconfig</code>.
     */
    public final TableField<AuthentikOutpostsKubernetesserviceconnectionRecord, JSONB> KUBECONFIG = createField(DSL.name("kubeconfig"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column
     * <code>public.authentik_outposts_kubernetesserviceconnection.verify_ssl</code>.
     */
    public final TableField<AuthentikOutpostsKubernetesserviceconnectionRecord, Boolean> VERIFY_SSL = createField(DSL.name("verify_ssl"), SQLDataType.BOOLEAN.nullable(false), this, "");

    private AuthentikOutpostsKubernetesserviceconnection(Name alias, Table<AuthentikOutpostsKubernetesserviceconnectionRecord> aliased) {
        this(alias, aliased, null);
    }

    private AuthentikOutpostsKubernetesserviceconnection(Name alias, Table<AuthentikOutpostsKubernetesserviceconnectionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased
     * <code>public.authentik_outposts_kubernetesserviceconnection</code> table
     * reference
     */
    public AuthentikOutpostsKubernetesserviceconnection(String alias) {
        this(DSL.name(alias), AUTHENTIK_OUTPOSTS_KUBERNETESSERVICECONNECTION);
    }

    /**
     * Create an aliased
     * <code>public.authentik_outposts_kubernetesserviceconnection</code> table
     * reference
     */
    public AuthentikOutpostsKubernetesserviceconnection(Name alias) {
        this(alias, AUTHENTIK_OUTPOSTS_KUBERNETESSERVICECONNECTION);
    }

    /**
     * Create a
     * <code>public.authentik_outposts_kubernetesserviceconnection</code> table
     * reference
     */
    public AuthentikOutpostsKubernetesserviceconnection() {
        this(DSL.name("authentik_outposts_kubernetesserviceconnection"), null);
    }

    public <O extends Record> AuthentikOutpostsKubernetesserviceconnection(Table<O> child, ForeignKey<O, AuthentikOutpostsKubernetesserviceconnectionRecord> key) {
        super(child, key, AUTHENTIK_OUTPOSTS_KUBERNETESSERVICECONNECTION);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<AuthentikOutpostsKubernetesserviceconnectionRecord> getPrimaryKey() {
        return Keys.AUTHENTIK_OUTPOSTS_KUBERNETESSERVICECONNECTION_PKEY;
    }

    @Override
    public List<ForeignKey<AuthentikOutpostsKubernetesserviceconnectionRecord, ?>> getReferences() {
        return Arrays.asList(Keys.AUTHENTIK_OUTPOSTS_KUBERNETESSERVICECONNECTION__AUTHENTIK_OUTPOSTS_K_OUTPOSTSERVICECONNEC_F5CF691D_FK_AUTHENTIK);
    }

    private transient AuthentikOutpostsOutpostserviceconnection _authentikOutpostsOutpostserviceconnection;

    public AuthentikOutpostsOutpostserviceconnection authentikOutpostsOutpostserviceconnection() {
        if (_authentikOutpostsOutpostserviceconnection == null)
            _authentikOutpostsOutpostserviceconnection = new AuthentikOutpostsOutpostserviceconnection(this, Keys.AUTHENTIK_OUTPOSTS_KUBERNETESSERVICECONNECTION__AUTHENTIK_OUTPOSTS_K_OUTPOSTSERVICECONNEC_F5CF691D_FK_AUTHENTIK);

        return _authentikOutpostsOutpostserviceconnection;
    }

    @Override
    public AuthentikOutpostsKubernetesserviceconnection as(String alias) {
        return new AuthentikOutpostsKubernetesserviceconnection(DSL.name(alias), this);
    }

    @Override
    public AuthentikOutpostsKubernetesserviceconnection as(Name alias) {
        return new AuthentikOutpostsKubernetesserviceconnection(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthentikOutpostsKubernetesserviceconnection rename(String name) {
        return new AuthentikOutpostsKubernetesserviceconnection(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthentikOutpostsKubernetesserviceconnection rename(Name name) {
        return new AuthentikOutpostsKubernetesserviceconnection(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, JSONB, Boolean> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
