/*
 * This file is generated by jOOQ.
 */
package me.aa07.paradise.taskdaemon.database.authentik.tables;


import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import me.aa07.paradise.taskdaemon.database.authentik.Indexes;
import me.aa07.paradise.taskdaemon.database.authentik.Public;
import me.aa07.paradise.taskdaemon.database.authentik.tables.records.AuthentikCoreGroupancestryRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthentikCoreGroupancestry extends TableImpl<AuthentikCoreGroupancestryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>public.authentik_core_groupancestry</code>
     */
    public static final AuthentikCoreGroupancestry AUTHENTIK_CORE_GROUPANCESTRY = new AuthentikCoreGroupancestry();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuthentikCoreGroupancestryRecord> getRecordType() {
        return AuthentikCoreGroupancestryRecord.class;
    }

    /**
     * The column <code>public.authentik_core_groupancestry.id</code>.
     */
    public final TableField<AuthentikCoreGroupancestryRecord, String> ID = createField(DSL.name("id"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>public.authentik_core_groupancestry.descendant_id</code>.
     */
    public final TableField<AuthentikCoreGroupancestryRecord, UUID> DESCENDANT_ID = createField(DSL.name("descendant_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.authentik_core_groupancestry.ancestor_id</code>.
     */
    public final TableField<AuthentikCoreGroupancestryRecord, UUID> ANCESTOR_ID = createField(DSL.name("ancestor_id"), SQLDataType.UUID, this, "");

    private AuthentikCoreGroupancestry(Name alias, Table<AuthentikCoreGroupancestryRecord> aliased) {
        this(alias, aliased, null);
    }

    private AuthentikCoreGroupancestry(Name alias, Table<AuthentikCoreGroupancestryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.materializedView());
    }

    /**
     * Create an aliased <code>public.authentik_core_groupancestry</code> table
     * reference
     */
    public AuthentikCoreGroupancestry(String alias) {
        this(DSL.name(alias), AUTHENTIK_CORE_GROUPANCESTRY);
    }

    /**
     * Create an aliased <code>public.authentik_core_groupancestry</code> table
     * reference
     */
    public AuthentikCoreGroupancestry(Name alias) {
        this(alias, AUTHENTIK_CORE_GROUPANCESTRY);
    }

    /**
     * Create a <code>public.authentik_core_groupancestry</code> table reference
     */
    public AuthentikCoreGroupancestry() {
        this(DSL.name("authentik_core_groupancestry"), null);
    }

    public <O extends Record> AuthentikCoreGroupancestry(Table<O> child, ForeignKey<O, AuthentikCoreGroupancestryRecord> key) {
        super(child, key, AUTHENTIK_CORE_GROUPANCESTRY);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.AUTHENTIK_C_ANCESTO_974845_IDX, Indexes.AUTHENTIK_C_DESCEND_F83A71_IDX, Indexes.AUTHENTIK_C_ID_5D0BB4_IDX);
    }

    @Override
    public AuthentikCoreGroupancestry as(String alias) {
        return new AuthentikCoreGroupancestry(DSL.name(alias), this);
    }

    @Override
    public AuthentikCoreGroupancestry as(Name alias) {
        return new AuthentikCoreGroupancestry(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthentikCoreGroupancestry rename(String name) {
        return new AuthentikCoreGroupancestry(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthentikCoreGroupancestry rename(Name name) {
        return new AuthentikCoreGroupancestry(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, UUID, UUID> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
