/*
 * This file is generated by jOOQ.
 */
package me.aa07.paradise.taskdaemon.database.authentik.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import me.aa07.paradise.taskdaemon.database.authentik.Indexes;
import me.aa07.paradise.taskdaemon.database.authentik.Keys;
import me.aa07.paradise.taskdaemon.database.authentik.Public;
import me.aa07.paradise.taskdaemon.database.authentik.tables.records.DjangoChannelsPostgresGroupchannelRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DjangoChannelsPostgresGroupchannel extends TableImpl<DjangoChannelsPostgresGroupchannelRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>public.django_channels_postgres_groupchannel</code>
     */
    public static final DjangoChannelsPostgresGroupchannel DJANGO_CHANNELS_POSTGRES_GROUPCHANNEL = new DjangoChannelsPostgresGroupchannel();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DjangoChannelsPostgresGroupchannelRecord> getRecordType() {
        return DjangoChannelsPostgresGroupchannelRecord.class;
    }

    /**
     * The column <code>public.django_channels_postgres_groupchannel.id</code>.
     */
    public final TableField<DjangoChannelsPostgresGroupchannelRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column
     * <code>public.django_channels_postgres_groupchannel.group_key</code>.
     */
    public final TableField<DjangoChannelsPostgresGroupchannelRecord, String> GROUP_KEY = createField(DSL.name("group_key"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column
     * <code>public.django_channels_postgres_groupchannel.channel</code>.
     */
    public final TableField<DjangoChannelsPostgresGroupchannelRecord, String> CHANNEL = createField(DSL.name("channel"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column
     * <code>public.django_channels_postgres_groupchannel.expires</code>.
     */
    public final TableField<DjangoChannelsPostgresGroupchannelRecord, OffsetDateTime> EXPIRES = createField(DSL.name("expires"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    private DjangoChannelsPostgresGroupchannel(Name alias, Table<DjangoChannelsPostgresGroupchannelRecord> aliased) {
        this(alias, aliased, null);
    }

    private DjangoChannelsPostgresGroupchannel(Name alias, Table<DjangoChannelsPostgresGroupchannelRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased
     * <code>public.django_channels_postgres_groupchannel</code> table reference
     */
    public DjangoChannelsPostgresGroupchannel(String alias) {
        this(DSL.name(alias), DJANGO_CHANNELS_POSTGRES_GROUPCHANNEL);
    }

    /**
     * Create an aliased
     * <code>public.django_channels_postgres_groupchannel</code> table reference
     */
    public DjangoChannelsPostgresGroupchannel(Name alias) {
        this(alias, DJANGO_CHANNELS_POSTGRES_GROUPCHANNEL);
    }

    /**
     * Create a <code>public.django_channels_postgres_groupchannel</code> table
     * reference
     */
    public DjangoChannelsPostgresGroupchannel() {
        this(DSL.name("django_channels_postgres_groupchannel"), null);
    }

    public <O extends Record> DjangoChannelsPostgresGroupchannel(Table<O> child, ForeignKey<O, DjangoChannelsPostgresGroupchannelRecord> key) {
        super(child, key, DJANGO_CHANNELS_POSTGRES_GROUPCHANNEL);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.DJANGO_CHAN_GROUP_K_173F44_IDX, Indexes.DJANGO_CHAN_GROUP_K_45D2E0_IDX, Indexes.DJANGO_CHANNELS_POSTGRES_GROUPCHANNEL_CHANNEL_6A5B3E9F, Indexes.DJANGO_CHANNELS_POSTGRES_GROUPCHANNEL_CHANNEL_6A5B3E9F_LIKE, Indexes.DJANGO_CHANNELS_POSTGRES_GROUPCHANNEL_EXPIRES_6DF3D2E1, Indexes.DJANGO_CHANNELS_POSTGRES_GROUPCHANNEL_GROUP_KEY_9D0AD8B3, Indexes.DJANGO_CHANNELS_POSTGRES_GROUPCHANNEL_GROUP_KEY_9D0AD8B3_LIKE);
    }

    @Override
    public UniqueKey<DjangoChannelsPostgresGroupchannelRecord> getPrimaryKey() {
        return Keys.DJANGO_CHANNELS_POSTGRES_GROUPCHANNEL_PKEY;
    }

    @Override
    public DjangoChannelsPostgresGroupchannel as(String alias) {
        return new DjangoChannelsPostgresGroupchannel(DSL.name(alias), this);
    }

    @Override
    public DjangoChannelsPostgresGroupchannel as(Name alias) {
        return new DjangoChannelsPostgresGroupchannel(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DjangoChannelsPostgresGroupchannel rename(String name) {
        return new DjangoChannelsPostgresGroupchannel(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DjangoChannelsPostgresGroupchannel rename(Name name) {
        return new DjangoChannelsPostgresGroupchannel(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<UUID, String, String, OffsetDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
