/*
 * This file is generated by jOOQ.
 */
package me.aa07.paradise.taskdaemon.database.authentik.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;

import me.aa07.paradise.taskdaemon.database.authentik.Indexes;
import me.aa07.paradise.taskdaemon.database.authentik.Keys;
import me.aa07.paradise.taskdaemon.database.authentik.Public;
import me.aa07.paradise.taskdaemon.database.authentik.tables.records.DjangoSessionRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DjangoSession extends TableImpl<DjangoSessionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.django_session</code>
     */
    public static final DjangoSession DJANGO_SESSION = new DjangoSession();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DjangoSessionRecord> getRecordType() {
        return DjangoSessionRecord.class;
    }

    /**
     * The column <code>public.django_session.session_key</code>.
     */
    public final TableField<DjangoSessionRecord, String> SESSION_KEY = createField(DSL.name("session_key"), SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>public.django_session.session_data</code>.
     */
    public final TableField<DjangoSessionRecord, String> SESSION_DATA = createField(DSL.name("session_data"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.django_session.expire_date</code>.
     */
    public final TableField<DjangoSessionRecord, OffsetDateTime> EXPIRE_DATE = createField(DSL.name("expire_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    private DjangoSession(Name alias, Table<DjangoSessionRecord> aliased) {
        this(alias, aliased, null);
    }

    private DjangoSession(Name alias, Table<DjangoSessionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.django_session</code> table reference
     */
    public DjangoSession(String alias) {
        this(DSL.name(alias), DJANGO_SESSION);
    }

    /**
     * Create an aliased <code>public.django_session</code> table reference
     */
    public DjangoSession(Name alias) {
        this(alias, DJANGO_SESSION);
    }

    /**
     * Create a <code>public.django_session</code> table reference
     */
    public DjangoSession() {
        this(DSL.name("django_session"), null);
    }

    public <O extends Record> DjangoSession(Table<O> child, ForeignKey<O, DjangoSessionRecord> key) {
        super(child, key, DJANGO_SESSION);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.DJANGO_SESSION_EXPIRE_DATE_A5C62663, Indexes.DJANGO_SESSION_SESSION_KEY_C0390E0F_LIKE);
    }

    @Override
    public UniqueKey<DjangoSessionRecord> getPrimaryKey() {
        return Keys.DJANGO_SESSION_PKEY;
    }

    @Override
    public DjangoSession as(String alias) {
        return new DjangoSession(DSL.name(alias), this);
    }

    @Override
    public DjangoSession as(Name alias) {
        return new DjangoSession(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DjangoSession rename(String name) {
        return new DjangoSession(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DjangoSession rename(Name name) {
        return new DjangoSession(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, OffsetDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
