/*
 * This file is generated by jOOQ.
 */
package me.aa07.paradise.taskdaemon.database.forums;


import java.util.Arrays;
import java.util.List;

import me.aa07.paradise.taskdaemon.database.forums.tables.BrilliantdiscordApprovalActions;
import me.aa07.paradise.taskdaemon.database.forums.tables.BrilliantdiscordBehavior;
import me.aa07.paradise.taskdaemon.database.forums.tables.BrilliantdiscordGroupdata;
import me.aa07.paradise.taskdaemon.database.forums.tables.BrilliantdiscordLogs;
import me.aa07.paradise.taskdaemon.database.forums.tables.BrilliantdiscordNotifications;
import me.aa07.paradise.taskdaemon.database.forums.tables.BrilliantdiscordRatelimits;
import me.aa07.paradise.taskdaemon.database.forums.tables.BrilliantdiscordXinvites;
import me.aa07.paradise.taskdaemon.database.forums.tables.CalendarCalendars;
import me.aa07.paradise.taskdaemon.database.forums.tables.CalendarEventComments;
import me.aa07.paradise.taskdaemon.database.forums.tables.CalendarEventReminders;
import me.aa07.paradise.taskdaemon.database.forums.tables.CalendarEventReviews;
import me.aa07.paradise.taskdaemon.database.forums.tables.CalendarEventRsvp;
import me.aa07.paradise.taskdaemon.database.forums.tables.CalendarEvents;
import me.aa07.paradise.taskdaemon.database.forums.tables.CalendarImportFeeds;
import me.aa07.paradise.taskdaemon.database.forums.tables.CalendarImportMap;
import me.aa07.paradise.taskdaemon.database.forums.tables.CalendarVenues;
import me.aa07.paradise.taskdaemon.database.forums.tables.ConvertAppSessions;
import me.aa07.paradise.taskdaemon.database.forums.tables.ConvertApps;
import me.aa07.paradise.taskdaemon.database.forums.tables.ConvertBbcodeMediatag;
import me.aa07.paradise.taskdaemon.database.forums.tables.ConvertCustomBbcode;
import me.aa07.paradise.taskdaemon.database.forums.tables.ConvertLink;
import me.aa07.paradise.taskdaemon.database.forums.tables.ConvertLinkPms;
import me.aa07.paradise.taskdaemon.database.forums.tables.ConvertLinkPosts;
import me.aa07.paradise.taskdaemon.database.forums.tables.ConvertLinkTopics;
import me.aa07.paradise.taskdaemon.database.forums.tables.ConvertLogs;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreAchievementsLog;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreAchievementsLogMilestones;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreAchievementsRules;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreAcpNotifcationsDismissals;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreAcpNotifications;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreAcpNotificationsPreferences;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreAcpSearchIndex;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreAcpTabOrder;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreAcronyms;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreAdminLoginLogs;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreAdminLogs;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreAdminPermissionRows;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreAdvertisements;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreAlerts;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreAlertsSeen;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreAnnouncements;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreAnonymousPosts;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreApiKeys;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreApiLogs;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreApiWebhookFires;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreApiWebhooks;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreApplications;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreApprovalQueue;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreAttachments;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreAttachmentsMap;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreAutomaticModerationPending;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreAutomaticModerationRules;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreAutomaticModerationTypes;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreBadges;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreBanfilters;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreBulkMail;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreCache;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreClubPages;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreClubs;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreClubsFields;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreClubsFieldvalues;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreClubsMemberships;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreClubsNodeMap;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreContactVerify;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreContentFeatured;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreContentMeta;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreDeletionLog;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreDev;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreEditHistory;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreEditorStoredReplies;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreEmailTemplates;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreEmoticons;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreErrorLogs;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreFileLogs;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreFileStorage;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreFiles;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreFilesTemp;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreFollow;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreFollowCountCache;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreGeoipCache;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreGoogleauthUsedCodes;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreGroupPromotions;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreGroups;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreHooks;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreIgnoredUsers;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreIncomingEmails;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreIpsBulletins;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreItemMarkers;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreItemMemberMap;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreItemRedirect;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreItemStatisticsCache;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreJavascript;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreLeaders;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreLeadersGroups;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreLog;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreLoginFailures;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreLoginHandlers;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreLoginLinks;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreLoginMethods;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreMailErrorLogs;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreMemberBadges;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreMemberHistory;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreMemberPrivacyActions;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreMemberRanks;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreMemberRecognize;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreMemberStatusReplies;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreMemberStatusUpdates;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreMembers;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreMembersFeatureSeen;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreMembersKnownDevices;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreMembersKnownIpAddresses;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreMembersLogins;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreMembersWarnActions;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreMembersWarnLogs;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreMembersWarnReasons;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreMenu;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreMessagePosts;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreMessageTopicUserMap;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreMessageTopics;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreModeratorLogs;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreModerators;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreModules;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreNotificationDefaults;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreNotificationPreferences;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreNotifications;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreNotificationsPwaKeys;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreNotificationsPwaQueue;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreOauthAuthorizePrompts;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreOauthClients;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreOauthServerAccessTokens;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreOauthServerAuthorizationCodes;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreOutputCache;
import me.aa07.paradise.taskdaemon.database.forums.tables.CorePermissionIndex;
import me.aa07.paradise.taskdaemon.database.forums.tables.CorePfieldsContent;
import me.aa07.paradise.taskdaemon.database.forums.tables.CorePfieldsData;
import me.aa07.paradise.taskdaemon.database.forums.tables.CorePfieldsGroups;
import me.aa07.paradise.taskdaemon.database.forums.tables.CorePlugins;
import me.aa07.paradise.taskdaemon.database.forums.tables.CorePointsLog;
import me.aa07.paradise.taskdaemon.database.forums.tables.CorePolls;
import me.aa07.paradise.taskdaemon.database.forums.tables.CorePostBeforeRegistering;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreProfanityFilters;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreProfileCompletion;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreProfileSteps;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreQuestionAndAnswer;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreQueue;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreRatings;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreRcAuthorNotificationText;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreRcComments;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreRcIndex;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreRcReports;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreReactions;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreReferralBanners;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreReferrals;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreReputationIndex;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreReputationLeaderboardHistory;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreReputationLevels;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreRssExport;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreRssImport;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreRssImported;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreS3Deletions;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreSavedCharts;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreSearchIndex;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreSearchIndexItemMap;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreSearchIndexTags;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreSecurityAnswers;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreSecurityQuestions;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreSeoMeta;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreSessions;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreShareLinks;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreSitemap;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreSocialPromote;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreSocialPromoteContent;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreSocialPromoteSharers;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreSoftDeleteLog;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreSolvedIndex;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreSpamServiceLog;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreSpamWhitelist;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreStatistics;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreStore;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreStreamSubscriptions;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreStreams;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreSysConfSettings;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreSysCpSessions;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreSysLang;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreSysLangWords;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreSysSocialGroupMembers;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreSysSocialGroups;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreTags;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreTagsCache;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreTagsPerms;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreTasks;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreTasksLog;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreThemeConflict;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreThemeContentHistory;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreThemeCss;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreThemeResources;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreThemeSettingsFields;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreThemeSettingsValues;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreThemeTemplates;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreThemes;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreUpgradeHistory;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreValidating;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreViewUpdates;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreVoters;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreWidgetAreas;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreWidgetTrash;
import me.aa07.paradise.taskdaemon.database.forums.tables.CoreWidgets;
import me.aa07.paradise.taskdaemon.database.forums.tables.ForumsAnswerRatings;
import me.aa07.paradise.taskdaemon.database.forums.tables.ForumsArchivePosts;
import me.aa07.paradise.taskdaemon.database.forums.tables.ForumsArchiveRules;
import me.aa07.paradise.taskdaemon.database.forums.tables.ForumsForums;
import me.aa07.paradise.taskdaemon.database.forums.tables.ForumsPosts;
import me.aa07.paradise.taskdaemon.database.forums.tables.ForumsQuestionRatings;
import me.aa07.paradise.taskdaemon.database.forums.tables.ForumsTopicMmod;
import me.aa07.paradise.taskdaemon.database.forums.tables.ForumsTopics;
import me.aa07.paradise.taskdaemon.database.forums.tables.ForumsViewMethod;
import me.aa07.paradise.taskdaemon.database.forums.tables.PatreonintegrationTier;
import me.aa07.paradise.taskdaemon.database.forums.tables.PatreonintegrationUser;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ParadiseForums extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>paradise_forums</code>
     */
    public static final ParadiseForums PARADISE_FORUMS = new ParadiseForums();

    /**
     * The table <code>paradise_forums.brilliantdiscord_approval_actions</code>.
     */
    public final BrilliantdiscordApprovalActions BRILLIANTDISCORD_APPROVAL_ACTIONS = BrilliantdiscordApprovalActions.BRILLIANTDISCORD_APPROVAL_ACTIONS;

    /**
     * The table <code>paradise_forums.brilliantdiscord_behavior</code>.
     */
    public final BrilliantdiscordBehavior BRILLIANTDISCORD_BEHAVIOR = BrilliantdiscordBehavior.BRILLIANTDISCORD_BEHAVIOR;

    /**
     * The table <code>paradise_forums.brilliantdiscord_groupdata</code>.
     */
    public final BrilliantdiscordGroupdata BRILLIANTDISCORD_GROUPDATA = BrilliantdiscordGroupdata.BRILLIANTDISCORD_GROUPDATA;

    /**
     * The table <code>paradise_forums.brilliantdiscord_logs</code>.
     */
    public final BrilliantdiscordLogs BRILLIANTDISCORD_LOGS = BrilliantdiscordLogs.BRILLIANTDISCORD_LOGS;

    /**
     * The table <code>paradise_forums.brilliantdiscord_notifications</code>.
     */
    public final BrilliantdiscordNotifications BRILLIANTDISCORD_NOTIFICATIONS = BrilliantdiscordNotifications.BRILLIANTDISCORD_NOTIFICATIONS;

    /**
     * The table <code>paradise_forums.brilliantdiscord_ratelimits</code>.
     */
    public final BrilliantdiscordRatelimits BRILLIANTDISCORD_RATELIMITS = BrilliantdiscordRatelimits.BRILLIANTDISCORD_RATELIMITS;

    /**
     * The table <code>paradise_forums.brilliantdiscord_xinvites</code>.
     */
    public final BrilliantdiscordXinvites BRILLIANTDISCORD_XINVITES = BrilliantdiscordXinvites.BRILLIANTDISCORD_XINVITES;

    /**
     * The table <code>paradise_forums.calendar_calendars</code>.
     */
    public final CalendarCalendars CALENDAR_CALENDARS = CalendarCalendars.CALENDAR_CALENDARS;

    /**
     * The table <code>paradise_forums.calendar_event_comments</code>.
     */
    public final CalendarEventComments CALENDAR_EVENT_COMMENTS = CalendarEventComments.CALENDAR_EVENT_COMMENTS;

    /**
     * The table <code>paradise_forums.calendar_event_reminders</code>.
     */
    public final CalendarEventReminders CALENDAR_EVENT_REMINDERS = CalendarEventReminders.CALENDAR_EVENT_REMINDERS;

    /**
     * The table <code>paradise_forums.calendar_event_reviews</code>.
     */
    public final CalendarEventReviews CALENDAR_EVENT_REVIEWS = CalendarEventReviews.CALENDAR_EVENT_REVIEWS;

    /**
     * The table <code>paradise_forums.calendar_event_rsvp</code>.
     */
    public final CalendarEventRsvp CALENDAR_EVENT_RSVP = CalendarEventRsvp.CALENDAR_EVENT_RSVP;

    /**
     * The table <code>paradise_forums.calendar_events</code>.
     */
    public final CalendarEvents CALENDAR_EVENTS = CalendarEvents.CALENDAR_EVENTS;

    /**
     * The table <code>paradise_forums.calendar_import_feeds</code>.
     */
    public final CalendarImportFeeds CALENDAR_IMPORT_FEEDS = CalendarImportFeeds.CALENDAR_IMPORT_FEEDS;

    /**
     * The table <code>paradise_forums.calendar_import_map</code>.
     */
    public final CalendarImportMap CALENDAR_IMPORT_MAP = CalendarImportMap.CALENDAR_IMPORT_MAP;

    /**
     * The table <code>paradise_forums.calendar_venues</code>.
     */
    public final CalendarVenues CALENDAR_VENUES = CalendarVenues.CALENDAR_VENUES;

    /**
     * The table <code>paradise_forums.convert_app_sessions</code>.
     */
    public final ConvertAppSessions CONVERT_APP_SESSIONS = ConvertAppSessions.CONVERT_APP_SESSIONS;

    /**
     * The table <code>paradise_forums.convert_apps</code>.
     */
    public final ConvertApps CONVERT_APPS = ConvertApps.CONVERT_APPS;

    /**
     * The table <code>paradise_forums.convert_bbcode_mediatag</code>.
     */
    public final ConvertBbcodeMediatag CONVERT_BBCODE_MEDIATAG = ConvertBbcodeMediatag.CONVERT_BBCODE_MEDIATAG;

    /**
     * The table <code>paradise_forums.convert_custom_bbcode</code>.
     */
    public final ConvertCustomBbcode CONVERT_CUSTOM_BBCODE = ConvertCustomBbcode.CONVERT_CUSTOM_BBCODE;

    /**
     * The table <code>paradise_forums.convert_link</code>.
     */
    public final ConvertLink CONVERT_LINK = ConvertLink.CONVERT_LINK;

    /**
     * The table <code>paradise_forums.convert_link_pms</code>.
     */
    public final ConvertLinkPms CONVERT_LINK_PMS = ConvertLinkPms.CONVERT_LINK_PMS;

    /**
     * The table <code>paradise_forums.convert_link_posts</code>.
     */
    public final ConvertLinkPosts CONVERT_LINK_POSTS = ConvertLinkPosts.CONVERT_LINK_POSTS;

    /**
     * The table <code>paradise_forums.convert_link_topics</code>.
     */
    public final ConvertLinkTopics CONVERT_LINK_TOPICS = ConvertLinkTopics.CONVERT_LINK_TOPICS;

    /**
     * The table <code>paradise_forums.convert_logs</code>.
     */
    public final ConvertLogs CONVERT_LOGS = ConvertLogs.CONVERT_LOGS;

    /**
     * The table <code>paradise_forums.core_achievements_log</code>.
     */
    public final CoreAchievementsLog CORE_ACHIEVEMENTS_LOG = CoreAchievementsLog.CORE_ACHIEVEMENTS_LOG;

    /**
     * The table <code>paradise_forums.core_achievements_log_milestones</code>.
     */
    public final CoreAchievementsLogMilestones CORE_ACHIEVEMENTS_LOG_MILESTONES = CoreAchievementsLogMilestones.CORE_ACHIEVEMENTS_LOG_MILESTONES;

    /**
     * The table <code>paradise_forums.core_achievements_rules</code>.
     */
    public final CoreAchievementsRules CORE_ACHIEVEMENTS_RULES = CoreAchievementsRules.CORE_ACHIEVEMENTS_RULES;

    /**
     * The table <code>paradise_forums.core_acp_notifcations_dismissals</code>.
     */
    public final CoreAcpNotifcationsDismissals CORE_ACP_NOTIFCATIONS_DISMISSALS = CoreAcpNotifcationsDismissals.CORE_ACP_NOTIFCATIONS_DISMISSALS;

    /**
     * The table <code>paradise_forums.core_acp_notifications</code>.
     */
    public final CoreAcpNotifications CORE_ACP_NOTIFICATIONS = CoreAcpNotifications.CORE_ACP_NOTIFICATIONS;

    /**
     * The table
     * <code>paradise_forums.core_acp_notifications_preferences</code>.
     */
    public final CoreAcpNotificationsPreferences CORE_ACP_NOTIFICATIONS_PREFERENCES = CoreAcpNotificationsPreferences.CORE_ACP_NOTIFICATIONS_PREFERENCES;

    /**
     * The table <code>paradise_forums.core_acp_search_index</code>.
     */
    public final CoreAcpSearchIndex CORE_ACP_SEARCH_INDEX = CoreAcpSearchIndex.CORE_ACP_SEARCH_INDEX;

    /**
     * The table <code>paradise_forums.core_acp_tab_order</code>.
     */
    public final CoreAcpTabOrder CORE_ACP_TAB_ORDER = CoreAcpTabOrder.CORE_ACP_TAB_ORDER;

    /**
     * The table <code>paradise_forums.core_acronyms</code>.
     */
    public final CoreAcronyms CORE_ACRONYMS = CoreAcronyms.CORE_ACRONYMS;

    /**
     * The table <code>paradise_forums.core_admin_login_logs</code>.
     */
    public final CoreAdminLoginLogs CORE_ADMIN_LOGIN_LOGS = CoreAdminLoginLogs.CORE_ADMIN_LOGIN_LOGS;

    /**
     * The table <code>paradise_forums.core_admin_logs</code>.
     */
    public final CoreAdminLogs CORE_ADMIN_LOGS = CoreAdminLogs.CORE_ADMIN_LOGS;

    /**
     * The table <code>paradise_forums.core_admin_permission_rows</code>.
     */
    public final CoreAdminPermissionRows CORE_ADMIN_PERMISSION_ROWS = CoreAdminPermissionRows.CORE_ADMIN_PERMISSION_ROWS;

    /**
     * The table <code>paradise_forums.core_advertisements</code>.
     */
    public final CoreAdvertisements CORE_ADVERTISEMENTS = CoreAdvertisements.CORE_ADVERTISEMENTS;

    /**
     * The table <code>paradise_forums.core_alerts</code>.
     */
    public final CoreAlerts CORE_ALERTS = CoreAlerts.CORE_ALERTS;

    /**
     * The table <code>paradise_forums.core_alerts_seen</code>.
     */
    public final CoreAlertsSeen CORE_ALERTS_SEEN = CoreAlertsSeen.CORE_ALERTS_SEEN;

    /**
     * The table <code>paradise_forums.core_announcements</code>.
     */
    public final CoreAnnouncements CORE_ANNOUNCEMENTS = CoreAnnouncements.CORE_ANNOUNCEMENTS;

    /**
     * The table <code>paradise_forums.core_anonymous_posts</code>.
     */
    public final CoreAnonymousPosts CORE_ANONYMOUS_POSTS = CoreAnonymousPosts.CORE_ANONYMOUS_POSTS;

    /**
     * The table <code>paradise_forums.core_api_keys</code>.
     */
    public final CoreApiKeys CORE_API_KEYS = CoreApiKeys.CORE_API_KEYS;

    /**
     * The table <code>paradise_forums.core_api_logs</code>.
     */
    public final CoreApiLogs CORE_API_LOGS = CoreApiLogs.CORE_API_LOGS;

    /**
     * The table <code>paradise_forums.core_api_webhook_fires</code>.
     */
    public final CoreApiWebhookFires CORE_API_WEBHOOK_FIRES = CoreApiWebhookFires.CORE_API_WEBHOOK_FIRES;

    /**
     * The table <code>paradise_forums.core_api_webhooks</code>.
     */
    public final CoreApiWebhooks CORE_API_WEBHOOKS = CoreApiWebhooks.CORE_API_WEBHOOKS;

    /**
     * The table <code>paradise_forums.core_applications</code>.
     */
    public final CoreApplications CORE_APPLICATIONS = CoreApplications.CORE_APPLICATIONS;

    /**
     * The table <code>paradise_forums.core_approval_queue</code>.
     */
    public final CoreApprovalQueue CORE_APPROVAL_QUEUE = CoreApprovalQueue.CORE_APPROVAL_QUEUE;

    /**
     * The table <code>paradise_forums.core_attachments</code>.
     */
    public final CoreAttachments CORE_ATTACHMENTS = CoreAttachments.CORE_ATTACHMENTS;

    /**
     * The table <code>paradise_forums.core_attachments_map</code>.
     */
    public final CoreAttachmentsMap CORE_ATTACHMENTS_MAP = CoreAttachmentsMap.CORE_ATTACHMENTS_MAP;

    /**
     * The table <code>paradise_forums.core_automatic_moderation_pending</code>.
     */
    public final CoreAutomaticModerationPending CORE_AUTOMATIC_MODERATION_PENDING = CoreAutomaticModerationPending.CORE_AUTOMATIC_MODERATION_PENDING;

    /**
     * The table <code>paradise_forums.core_automatic_moderation_rules</code>.
     */
    public final CoreAutomaticModerationRules CORE_AUTOMATIC_MODERATION_RULES = CoreAutomaticModerationRules.CORE_AUTOMATIC_MODERATION_RULES;

    /**
     * The table <code>paradise_forums.core_automatic_moderation_types</code>.
     */
    public final CoreAutomaticModerationTypes CORE_AUTOMATIC_MODERATION_TYPES = CoreAutomaticModerationTypes.CORE_AUTOMATIC_MODERATION_TYPES;

    /**
     * The table <code>paradise_forums.core_badges</code>.
     */
    public final CoreBadges CORE_BADGES = CoreBadges.CORE_BADGES;

    /**
     * The table <code>paradise_forums.core_banfilters</code>.
     */
    public final CoreBanfilters CORE_BANFILTERS = CoreBanfilters.CORE_BANFILTERS;

    /**
     * The table <code>paradise_forums.core_bulk_mail</code>.
     */
    public final CoreBulkMail CORE_BULK_MAIL = CoreBulkMail.CORE_BULK_MAIL;

    /**
     * The table <code>paradise_forums.core_cache</code>.
     */
    public final CoreCache CORE_CACHE = CoreCache.CORE_CACHE;

    /**
     * The table <code>paradise_forums.core_club_pages</code>.
     */
    public final CoreClubPages CORE_CLUB_PAGES = CoreClubPages.CORE_CLUB_PAGES;

    /**
     * The table <code>paradise_forums.core_clubs</code>.
     */
    public final CoreClubs CORE_CLUBS = CoreClubs.CORE_CLUBS;

    /**
     * The table <code>paradise_forums.core_clubs_fields</code>.
     */
    public final CoreClubsFields CORE_CLUBS_FIELDS = CoreClubsFields.CORE_CLUBS_FIELDS;

    /**
     * The table <code>paradise_forums.core_clubs_fieldvalues</code>.
     */
    public final CoreClubsFieldvalues CORE_CLUBS_FIELDVALUES = CoreClubsFieldvalues.CORE_CLUBS_FIELDVALUES;

    /**
     * The table <code>paradise_forums.core_clubs_memberships</code>.
     */
    public final CoreClubsMemberships CORE_CLUBS_MEMBERSHIPS = CoreClubsMemberships.CORE_CLUBS_MEMBERSHIPS;

    /**
     * The table <code>paradise_forums.core_clubs_node_map</code>.
     */
    public final CoreClubsNodeMap CORE_CLUBS_NODE_MAP = CoreClubsNodeMap.CORE_CLUBS_NODE_MAP;

    /**
     * The table <code>paradise_forums.core_contact_verify</code>.
     */
    public final CoreContactVerify CORE_CONTACT_VERIFY = CoreContactVerify.CORE_CONTACT_VERIFY;

    /**
     * The table <code>paradise_forums.core_content_featured</code>.
     */
    public final CoreContentFeatured CORE_CONTENT_FEATURED = CoreContentFeatured.CORE_CONTENT_FEATURED;

    /**
     * The table <code>paradise_forums.core_content_meta</code>.
     */
    public final CoreContentMeta CORE_CONTENT_META = CoreContentMeta.CORE_CONTENT_META;

    /**
     * The table <code>paradise_forums.core_deletion_log</code>.
     */
    public final CoreDeletionLog CORE_DELETION_LOG = CoreDeletionLog.CORE_DELETION_LOG;

    /**
     * IN_DEV only. Store when the database schema was last synced.
     */
    public final CoreDev CORE_DEV = CoreDev.CORE_DEV;

    /**
     * The table <code>paradise_forums.core_edit_history</code>.
     */
    public final CoreEditHistory CORE_EDIT_HISTORY = CoreEditHistory.CORE_EDIT_HISTORY;

    /**
     * The table <code>paradise_forums.core_editor_stored_replies</code>.
     */
    public final CoreEditorStoredReplies CORE_EDITOR_STORED_REPLIES = CoreEditorStoredReplies.CORE_EDITOR_STORED_REPLIES;

    /**
     * The table <code>paradise_forums.core_email_templates</code>.
     */
    public final CoreEmailTemplates CORE_EMAIL_TEMPLATES = CoreEmailTemplates.CORE_EMAIL_TEMPLATES;

    /**
     * The table <code>paradise_forums.core_emoticons</code>.
     */
    public final CoreEmoticons CORE_EMOTICONS = CoreEmoticons.CORE_EMOTICONS;

    /**
     * The table <code>paradise_forums.core_error_logs</code>.
     */
    public final CoreErrorLogs CORE_ERROR_LOGS = CoreErrorLogs.CORE_ERROR_LOGS;

    /**
     * The table <code>paradise_forums.core_file_logs</code>.
     */
    public final CoreFileLogs CORE_FILE_LOGS = CoreFileLogs.CORE_FILE_LOGS;

    /**
     * The table <code>paradise_forums.core_file_storage</code>.
     */
    public final CoreFileStorage CORE_FILE_STORAGE = CoreFileStorage.CORE_FILE_STORAGE;

    /**
     * The table <code>paradise_forums.core_files</code>.
     */
    public final CoreFiles CORE_FILES = CoreFiles.CORE_FILES;

    /**
     * The table <code>paradise_forums.core_files_temp</code>.
     */
    public final CoreFilesTemp CORE_FILES_TEMP = CoreFilesTemp.CORE_FILES_TEMP;

    /**
     * The table <code>paradise_forums.core_follow</code>.
     */
    public final CoreFollow CORE_FOLLOW = CoreFollow.CORE_FOLLOW;

    /**
     * The table <code>paradise_forums.core_follow_count_cache</code>.
     */
    public final CoreFollowCountCache CORE_FOLLOW_COUNT_CACHE = CoreFollowCountCache.CORE_FOLLOW_COUNT_CACHE;

    /**
     * Caches GeoIP data to prevent multiple remote calls
     */
    public final CoreGeoipCache CORE_GEOIP_CACHE = CoreGeoipCache.CORE_GEOIP_CACHE;

    /**
     * The table <code>paradise_forums.core_googleauth_used_codes</code>.
     */
    public final CoreGoogleauthUsedCodes CORE_GOOGLEAUTH_USED_CODES = CoreGoogleauthUsedCodes.CORE_GOOGLEAUTH_USED_CODES;

    /**
     * The table <code>paradise_forums.core_group_promotions</code>.
     */
    public final CoreGroupPromotions CORE_GROUP_PROMOTIONS = CoreGroupPromotions.CORE_GROUP_PROMOTIONS;

    /**
     * The table <code>paradise_forums.core_groups</code>.
     */
    public final CoreGroups CORE_GROUPS = CoreGroups.CORE_GROUPS;

    /**
     * The table <code>paradise_forums.core_hooks</code>.
     */
    public final CoreHooks CORE_HOOKS = CoreHooks.CORE_HOOKS;

    /**
     * The table <code>paradise_forums.core_ignored_users</code>.
     */
    public final CoreIgnoredUsers CORE_IGNORED_USERS = CoreIgnoredUsers.CORE_IGNORED_USERS;

    /**
     * This table is used to store the incoming email routing rules
     */
    public final CoreIncomingEmails CORE_INCOMING_EMAILS = CoreIncomingEmails.CORE_INCOMING_EMAILS;

    /**
     * The table <code>paradise_forums.core_ips_bulletins</code>.
     */
    public final CoreIpsBulletins CORE_IPS_BULLETINS = CoreIpsBulletins.CORE_IPS_BULLETINS;

    /**
     * The table <code>paradise_forums.core_item_markers</code>.
     */
    public final CoreItemMarkers CORE_ITEM_MARKERS = CoreItemMarkers.CORE_ITEM_MARKERS;

    /**
     * The table <code>paradise_forums.core_item_member_map</code>.
     */
    public final CoreItemMemberMap CORE_ITEM_MEMBER_MAP = CoreItemMemberMap.CORE_ITEM_MEMBER_MAP;

    /**
     * The table <code>paradise_forums.core_item_redirect</code>.
     */
    public final CoreItemRedirect CORE_ITEM_REDIRECT = CoreItemRedirect.CORE_ITEM_REDIRECT;

    /**
     * The table <code>paradise_forums.core_item_statistics_cache</code>.
     */
    public final CoreItemStatisticsCache CORE_ITEM_STATISTICS_CACHE = CoreItemStatisticsCache.CORE_ITEM_STATISTICS_CACHE;

    /**
     * The table <code>paradise_forums.core_javascript</code>.
     */
    public final CoreJavascript CORE_JAVASCRIPT = CoreJavascript.CORE_JAVASCRIPT;

    /**
     * The table <code>paradise_forums.core_leaders</code>.
     */
    public final CoreLeaders CORE_LEADERS = CoreLeaders.CORE_LEADERS;

    /**
     * The table <code>paradise_forums.core_leaders_groups</code>.
     */
    public final CoreLeadersGroups CORE_LEADERS_GROUPS = CoreLeadersGroups.CORE_LEADERS_GROUPS;

    /**
     * The table <code>paradise_forums.core_log</code>.
     */
    public final CoreLog CORE_LOG = CoreLog.CORE_LOG;

    /**
     * The table <code>paradise_forums.core_login_failures</code>.
     */
    public final CoreLoginFailures CORE_LOGIN_FAILURES = CoreLoginFailures.CORE_LOGIN_FAILURES;

    /**
     * The table <code>paradise_forums.core_login_handlers</code>.
     */
    public final CoreLoginHandlers CORE_LOGIN_HANDLERS = CoreLoginHandlers.CORE_LOGIN_HANDLERS;

    /**
     * The table <code>paradise_forums.core_login_links</code>.
     */
    public final CoreLoginLinks CORE_LOGIN_LINKS = CoreLoginLinks.CORE_LOGIN_LINKS;

    /**
     * The table <code>paradise_forums.core_login_methods</code>.
     */
    public final CoreLoginMethods CORE_LOGIN_METHODS = CoreLoginMethods.CORE_LOGIN_METHODS;

    /**
     * The table <code>paradise_forums.core_mail_error_logs</code>.
     */
    public final CoreMailErrorLogs CORE_MAIL_ERROR_LOGS = CoreMailErrorLogs.CORE_MAIL_ERROR_LOGS;

    /**
     * The table <code>paradise_forums.core_member_badges</code>.
     */
    public final CoreMemberBadges CORE_MEMBER_BADGES = CoreMemberBadges.CORE_MEMBER_BADGES;

    /**
     * The table <code>paradise_forums.core_member_history</code>.
     */
    public final CoreMemberHistory CORE_MEMBER_HISTORY = CoreMemberHistory.CORE_MEMBER_HISTORY;

    /**
     * The table <code>paradise_forums.core_member_privacy_actions</code>.
     */
    public final CoreMemberPrivacyActions CORE_MEMBER_PRIVACY_ACTIONS = CoreMemberPrivacyActions.CORE_MEMBER_PRIVACY_ACTIONS;

    /**
     * The table <code>paradise_forums.core_member_ranks</code>.
     */
    public final CoreMemberRanks CORE_MEMBER_RANKS = CoreMemberRanks.CORE_MEMBER_RANKS;

    /**
     * The table <code>paradise_forums.core_member_recognize</code>.
     */
    public final CoreMemberRecognize CORE_MEMBER_RECOGNIZE = CoreMemberRecognize.CORE_MEMBER_RECOGNIZE;

    /**
     * The table <code>paradise_forums.core_member_status_replies</code>.
     */
    public final CoreMemberStatusReplies CORE_MEMBER_STATUS_REPLIES = CoreMemberStatusReplies.CORE_MEMBER_STATUS_REPLIES;

    /**
     * The table <code>paradise_forums.core_member_status_updates</code>.
     */
    public final CoreMemberStatusUpdates CORE_MEMBER_STATUS_UPDATES = CoreMemberStatusUpdates.CORE_MEMBER_STATUS_UPDATES;

    /**
     * The table <code>paradise_forums.core_members</code>.
     */
    public final CoreMembers CORE_MEMBERS = CoreMembers.CORE_MEMBERS;

    /**
     * The table <code>paradise_forums.core_members_feature_seen</code>.
     */
    public final CoreMembersFeatureSeen CORE_MEMBERS_FEATURE_SEEN = CoreMembersFeatureSeen.CORE_MEMBERS_FEATURE_SEEN;

    /**
     * The table <code>paradise_forums.core_members_known_devices</code>.
     */
    public final CoreMembersKnownDevices CORE_MEMBERS_KNOWN_DEVICES = CoreMembersKnownDevices.CORE_MEMBERS_KNOWN_DEVICES;

    /**
     * The table <code>paradise_forums.core_members_known_ip_addresses</code>.
     */
    public final CoreMembersKnownIpAddresses CORE_MEMBERS_KNOWN_IP_ADDRESSES = CoreMembersKnownIpAddresses.CORE_MEMBERS_KNOWN_IP_ADDRESSES;

    /**
     * The table <code>paradise_forums.core_members_logins</code>.
     */
    public final CoreMembersLogins CORE_MEMBERS_LOGINS = CoreMembersLogins.CORE_MEMBERS_LOGINS;

    /**
     * The table <code>paradise_forums.core_members_warn_actions</code>.
     */
    public final CoreMembersWarnActions CORE_MEMBERS_WARN_ACTIONS = CoreMembersWarnActions.CORE_MEMBERS_WARN_ACTIONS;

    /**
     * The table <code>paradise_forums.core_members_warn_logs</code>.
     */
    public final CoreMembersWarnLogs CORE_MEMBERS_WARN_LOGS = CoreMembersWarnLogs.CORE_MEMBERS_WARN_LOGS;

    /**
     * The table <code>paradise_forums.core_members_warn_reasons</code>.
     */
    public final CoreMembersWarnReasons CORE_MEMBERS_WARN_REASONS = CoreMembersWarnReasons.CORE_MEMBERS_WARN_REASONS;

    /**
     * The table <code>paradise_forums.core_menu</code>.
     */
    public final CoreMenu CORE_MENU = CoreMenu.CORE_MENU;

    /**
     * The table <code>paradise_forums.core_message_posts</code>.
     */
    public final CoreMessagePosts CORE_MESSAGE_POSTS = CoreMessagePosts.CORE_MESSAGE_POSTS;

    /**
     * The table <code>paradise_forums.core_message_topic_user_map</code>.
     */
    public final CoreMessageTopicUserMap CORE_MESSAGE_TOPIC_USER_MAP = CoreMessageTopicUserMap.CORE_MESSAGE_TOPIC_USER_MAP;

    /**
     * The table <code>paradise_forums.core_message_topics</code>.
     */
    public final CoreMessageTopics CORE_MESSAGE_TOPICS = CoreMessageTopics.CORE_MESSAGE_TOPICS;

    /**
     * The table <code>paradise_forums.core_moderator_logs</code>.
     */
    public final CoreModeratorLogs CORE_MODERATOR_LOGS = CoreModeratorLogs.CORE_MODERATOR_LOGS;

    /**
     * The table <code>paradise_forums.core_moderators</code>.
     */
    public final CoreModerators CORE_MODERATORS = CoreModerators.CORE_MODERATORS;

    /**
     * The table <code>paradise_forums.core_modules</code>.
     */
    public final CoreModules CORE_MODULES = CoreModules.CORE_MODULES;

    /**
     * The table <code>paradise_forums.core_notification_defaults</code>.
     */
    public final CoreNotificationDefaults CORE_NOTIFICATION_DEFAULTS = CoreNotificationDefaults.CORE_NOTIFICATION_DEFAULTS;

    /**
     * The table <code>paradise_forums.core_notification_preferences</code>.
     */
    public final CoreNotificationPreferences CORE_NOTIFICATION_PREFERENCES = CoreNotificationPreferences.CORE_NOTIFICATION_PREFERENCES;

    /**
     * The table <code>paradise_forums.core_notifications</code>.
     */
    public final CoreNotifications CORE_NOTIFICATIONS = CoreNotifications.CORE_NOTIFICATIONS;

    /**
     * The table <code>paradise_forums.core_notifications_pwa_keys</code>.
     */
    public final CoreNotificationsPwaKeys CORE_NOTIFICATIONS_PWA_KEYS = CoreNotificationsPwaKeys.CORE_NOTIFICATIONS_PWA_KEYS;

    /**
     * The table <code>paradise_forums.core_notifications_pwa_queue</code>.
     */
    public final CoreNotificationsPwaQueue CORE_NOTIFICATIONS_PWA_QUEUE = CoreNotificationsPwaQueue.CORE_NOTIFICATIONS_PWA_QUEUE;

    /**
     * The table <code>paradise_forums.core_oauth_authorize_prompts</code>.
     */
    public final CoreOauthAuthorizePrompts CORE_OAUTH_AUTHORIZE_PROMPTS = CoreOauthAuthorizePrompts.CORE_OAUTH_AUTHORIZE_PROMPTS;

    /**
     * The table <code>paradise_forums.core_oauth_clients</code>.
     */
    public final CoreOauthClients CORE_OAUTH_CLIENTS = CoreOauthClients.CORE_OAUTH_CLIENTS;

    /**
     * The table <code>paradise_forums.core_oauth_server_access_tokens</code>.
     */
    public final CoreOauthServerAccessTokens CORE_OAUTH_SERVER_ACCESS_TOKENS = CoreOauthServerAccessTokens.CORE_OAUTH_SERVER_ACCESS_TOKENS;

    /**
     * The table
     * <code>paradise_forums.core_oauth_server_authorization_codes</code>.
     */
    public final CoreOauthServerAuthorizationCodes CORE_OAUTH_SERVER_AUTHORIZATION_CODES = CoreOauthServerAuthorizationCodes.CORE_OAUTH_SERVER_AUTHORIZATION_CODES;

    /**
     * The table <code>paradise_forums.core_output_cache</code>.
     */
    public final CoreOutputCache CORE_OUTPUT_CACHE = CoreOutputCache.CORE_OUTPUT_CACHE;

    /**
     * The table <code>paradise_forums.core_permission_index</code>.
     */
    public final CorePermissionIndex CORE_PERMISSION_INDEX = CorePermissionIndex.CORE_PERMISSION_INDEX;

    /**
     * The table <code>paradise_forums.core_pfields_content</code>.
     */
    public final CorePfieldsContent CORE_PFIELDS_CONTENT = CorePfieldsContent.CORE_PFIELDS_CONTENT;

    /**
     * The table <code>paradise_forums.core_pfields_data</code>.
     */
    public final CorePfieldsData CORE_PFIELDS_DATA = CorePfieldsData.CORE_PFIELDS_DATA;

    /**
     * The table <code>paradise_forums.core_pfields_groups</code>.
     */
    public final CorePfieldsGroups CORE_PFIELDS_GROUPS = CorePfieldsGroups.CORE_PFIELDS_GROUPS;

    /**
     * The table <code>paradise_forums.core_plugins</code>.
     */
    public final CorePlugins CORE_PLUGINS = CorePlugins.CORE_PLUGINS;

    /**
     * The table <code>paradise_forums.core_points_log</code>.
     */
    public final CorePointsLog CORE_POINTS_LOG = CorePointsLog.CORE_POINTS_LOG;

    /**
     * The table <code>paradise_forums.core_polls</code>.
     */
    public final CorePolls CORE_POLLS = CorePolls.CORE_POLLS;

    /**
     * The table <code>paradise_forums.core_post_before_registering</code>.
     */
    public final CorePostBeforeRegistering CORE_POST_BEFORE_REGISTERING = CorePostBeforeRegistering.CORE_POST_BEFORE_REGISTERING;

    /**
     * The table <code>paradise_forums.core_profanity_filters</code>.
     */
    public final CoreProfanityFilters CORE_PROFANITY_FILTERS = CoreProfanityFilters.CORE_PROFANITY_FILTERS;

    /**
     * The table <code>paradise_forums.core_profile_completion</code>.
     */
    public final CoreProfileCompletion CORE_PROFILE_COMPLETION = CoreProfileCompletion.CORE_PROFILE_COMPLETION;

    /**
     * The table <code>paradise_forums.core_profile_steps</code>.
     */
    public final CoreProfileSteps CORE_PROFILE_STEPS = CoreProfileSteps.CORE_PROFILE_STEPS;

    /**
     * The table <code>paradise_forums.core_question_and_answer</code>.
     */
    public final CoreQuestionAndAnswer CORE_QUESTION_AND_ANSWER = CoreQuestionAndAnswer.CORE_QUESTION_AND_ANSWER;

    /**
     * The table <code>paradise_forums.core_queue</code>.
     */
    public final CoreQueue CORE_QUEUE = CoreQueue.CORE_QUEUE;

    /**
     * The table <code>paradise_forums.core_ratings</code>.
     */
    public final CoreRatings CORE_RATINGS = CoreRatings.CORE_RATINGS;

    /**
     * The table <code>paradise_forums.core_rc_author_notification_text</code>.
     */
    public final CoreRcAuthorNotificationText CORE_RC_AUTHOR_NOTIFICATION_TEXT = CoreRcAuthorNotificationText.CORE_RC_AUTHOR_NOTIFICATION_TEXT;

    /**
     * The table <code>paradise_forums.core_rc_comments</code>.
     */
    public final CoreRcComments CORE_RC_COMMENTS = CoreRcComments.CORE_RC_COMMENTS;

    /**
     * The table <code>paradise_forums.core_rc_index</code>.
     */
    public final CoreRcIndex CORE_RC_INDEX = CoreRcIndex.CORE_RC_INDEX;

    /**
     * The table <code>paradise_forums.core_rc_reports</code>.
     */
    public final CoreRcReports CORE_RC_REPORTS = CoreRcReports.CORE_RC_REPORTS;

    /**
     * The table <code>paradise_forums.core_reactions</code>.
     */
    public final CoreReactions CORE_REACTIONS = CoreReactions.CORE_REACTIONS;

    /**
     * The table <code>paradise_forums.core_referral_banners</code>.
     */
    public final CoreReferralBanners CORE_REFERRAL_BANNERS = CoreReferralBanners.CORE_REFERRAL_BANNERS;

    /**
     * The table <code>paradise_forums.core_referrals</code>.
     */
    public final CoreReferrals CORE_REFERRALS = CoreReferrals.CORE_REFERRALS;

    /**
     * The table <code>paradise_forums.core_reputation_index</code>.
     */
    public final CoreReputationIndex CORE_REPUTATION_INDEX = CoreReputationIndex.CORE_REPUTATION_INDEX;

    /**
     * The table
     * <code>paradise_forums.core_reputation_leaderboard_history</code>.
     */
    public final CoreReputationLeaderboardHistory CORE_REPUTATION_LEADERBOARD_HISTORY = CoreReputationLeaderboardHistory.CORE_REPUTATION_LEADERBOARD_HISTORY;

    /**
     * The table <code>paradise_forums.core_reputation_levels</code>.
     */
    public final CoreReputationLevels CORE_REPUTATION_LEVELS = CoreReputationLevels.CORE_REPUTATION_LEVELS;

    /**
     * The table <code>paradise_forums.core_rss_export</code>.
     */
    public final CoreRssExport CORE_RSS_EXPORT = CoreRssExport.CORE_RSS_EXPORT;

    /**
     * The table <code>paradise_forums.core_rss_import</code>.
     */
    public final CoreRssImport CORE_RSS_IMPORT = CoreRssImport.CORE_RSS_IMPORT;

    /**
     * The table <code>paradise_forums.core_rss_imported</code>.
     */
    public final CoreRssImported CORE_RSS_IMPORTED = CoreRssImported.CORE_RSS_IMPORTED;

    /**
     * The table <code>paradise_forums.core_s3_deletions</code>.
     */
    public final CoreS3Deletions CORE_S3_DELETIONS = CoreS3Deletions.CORE_S3_DELETIONS;

    /**
     * The table <code>paradise_forums.core_saved_charts</code>.
     */
    public final CoreSavedCharts CORE_SAVED_CHARTS = CoreSavedCharts.CORE_SAVED_CHARTS;

    /**
     * The table <code>paradise_forums.core_search_index</code>.
     */
    public final CoreSearchIndex CORE_SEARCH_INDEX = CoreSearchIndex.CORE_SEARCH_INDEX;

    /**
     * The table <code>paradise_forums.core_search_index_item_map</code>.
     */
    public final CoreSearchIndexItemMap CORE_SEARCH_INDEX_ITEM_MAP = CoreSearchIndexItemMap.CORE_SEARCH_INDEX_ITEM_MAP;

    /**
     * The table <code>paradise_forums.core_search_index_tags</code>.
     */
    public final CoreSearchIndexTags CORE_SEARCH_INDEX_TAGS = CoreSearchIndexTags.CORE_SEARCH_INDEX_TAGS;

    /**
     * The table <code>paradise_forums.core_security_answers</code>.
     */
    public final CoreSecurityAnswers CORE_SECURITY_ANSWERS = CoreSecurityAnswers.CORE_SECURITY_ANSWERS;

    /**
     * The table <code>paradise_forums.core_security_questions</code>.
     */
    public final CoreSecurityQuestions CORE_SECURITY_QUESTIONS = CoreSecurityQuestions.CORE_SECURITY_QUESTIONS;

    /**
     * The table <code>paradise_forums.core_seo_meta</code>.
     */
    public final CoreSeoMeta CORE_SEO_META = CoreSeoMeta.CORE_SEO_META;

    /**
     * The table <code>paradise_forums.core_sessions</code>.
     */
    public final CoreSessions CORE_SESSIONS = CoreSessions.CORE_SESSIONS;

    /**
     * The table <code>paradise_forums.core_share_links</code>.
     */
    public final CoreShareLinks CORE_SHARE_LINKS = CoreShareLinks.CORE_SHARE_LINKS;

    /**
     * The table <code>paradise_forums.core_sitemap</code>.
     */
    public final CoreSitemap CORE_SITEMAP = CoreSitemap.CORE_SITEMAP;

    /**
     * The table <code>paradise_forums.core_social_promote</code>.
     */
    public final CoreSocialPromote CORE_SOCIAL_PROMOTE = CoreSocialPromote.CORE_SOCIAL_PROMOTE;

    /**
     * The table <code>paradise_forums.core_social_promote_content</code>.
     */
    public final CoreSocialPromoteContent CORE_SOCIAL_PROMOTE_CONTENT = CoreSocialPromoteContent.CORE_SOCIAL_PROMOTE_CONTENT;

    /**
     * The table <code>paradise_forums.core_social_promote_sharers</code>.
     */
    public final CoreSocialPromoteSharers CORE_SOCIAL_PROMOTE_SHARERS = CoreSocialPromoteSharers.CORE_SOCIAL_PROMOTE_SHARERS;

    /**
     * The table <code>paradise_forums.core_soft_delete_log</code>.
     */
    public final CoreSoftDeleteLog CORE_SOFT_DELETE_LOG = CoreSoftDeleteLog.CORE_SOFT_DELETE_LOG;

    /**
     * The table <code>paradise_forums.core_solved_index</code>.
     */
    public final CoreSolvedIndex CORE_SOLVED_INDEX = CoreSolvedIndex.CORE_SOLVED_INDEX;

    /**
     * The table <code>paradise_forums.core_spam_service_log</code>.
     */
    public final CoreSpamServiceLog CORE_SPAM_SERVICE_LOG = CoreSpamServiceLog.CORE_SPAM_SERVICE_LOG;

    /**
     * The table <code>paradise_forums.core_spam_whitelist</code>.
     */
    public final CoreSpamWhitelist CORE_SPAM_WHITELIST = CoreSpamWhitelist.CORE_SPAM_WHITELIST;

    /**
     * The table <code>paradise_forums.core_statistics</code>.
     */
    public final CoreStatistics CORE_STATISTICS = CoreStatistics.CORE_STATISTICS;

    /**
     * The table <code>paradise_forums.core_store</code>.
     */
    public final CoreStore CORE_STORE = CoreStore.CORE_STORE;

    /**
     * The table <code>paradise_forums.core_stream_subscriptions</code>.
     */
    public final CoreStreamSubscriptions CORE_STREAM_SUBSCRIPTIONS = CoreStreamSubscriptions.CORE_STREAM_SUBSCRIPTIONS;

    /**
     * The table <code>paradise_forums.core_streams</code>.
     */
    public final CoreStreams CORE_STREAMS = CoreStreams.CORE_STREAMS;

    /**
     * The table <code>paradise_forums.core_sys_conf_settings</code>.
     */
    public final CoreSysConfSettings CORE_SYS_CONF_SETTINGS = CoreSysConfSettings.CORE_SYS_CONF_SETTINGS;

    /**
     * The table <code>paradise_forums.core_sys_cp_sessions</code>.
     */
    public final CoreSysCpSessions CORE_SYS_CP_SESSIONS = CoreSysCpSessions.CORE_SYS_CP_SESSIONS;

    /**
     * The table <code>paradise_forums.core_sys_lang</code>.
     */
    public final CoreSysLang CORE_SYS_LANG = CoreSysLang.CORE_SYS_LANG;

    /**
     * The table <code>paradise_forums.core_sys_lang_words</code>.
     */
    public final CoreSysLangWords CORE_SYS_LANG_WORDS = CoreSysLangWords.CORE_SYS_LANG_WORDS;

    /**
     * The table <code>paradise_forums.core_sys_social_group_members</code>.
     */
    public final CoreSysSocialGroupMembers CORE_SYS_SOCIAL_GROUP_MEMBERS = CoreSysSocialGroupMembers.CORE_SYS_SOCIAL_GROUP_MEMBERS;

    /**
     * The table <code>paradise_forums.core_sys_social_groups</code>.
     */
    public final CoreSysSocialGroups CORE_SYS_SOCIAL_GROUPS = CoreSysSocialGroups.CORE_SYS_SOCIAL_GROUPS;

    /**
     * The table <code>paradise_forums.core_tags</code>.
     */
    public final CoreTags CORE_TAGS = CoreTags.CORE_TAGS;

    /**
     * The table <code>paradise_forums.core_tags_cache</code>.
     */
    public final CoreTagsCache CORE_TAGS_CACHE = CoreTagsCache.CORE_TAGS_CACHE;

    /**
     * The table <code>paradise_forums.core_tags_perms</code>.
     */
    public final CoreTagsPerms CORE_TAGS_PERMS = CoreTagsPerms.CORE_TAGS_PERMS;

    /**
     * Stores information about tasks
     */
    public final CoreTasks CORE_TASKS = CoreTasks.CORE_TASKS;

    /**
     * The table <code>paradise_forums.core_tasks_log</code>.
     */
    public final CoreTasksLog CORE_TASKS_LOG = CoreTasksLog.CORE_TASKS_LOG;

    /**
     * The table <code>paradise_forums.core_theme_conflict</code>.
     */
    public final CoreThemeConflict CORE_THEME_CONFLICT = CoreThemeConflict.CORE_THEME_CONFLICT;

    /**
     * The table <code>paradise_forums.core_theme_content_history</code>.
     */
    public final CoreThemeContentHistory CORE_THEME_CONTENT_HISTORY = CoreThemeContentHistory.CORE_THEME_CONTENT_HISTORY;

    /**
     * The table <code>paradise_forums.core_theme_css</code>.
     */
    public final CoreThemeCss CORE_THEME_CSS = CoreThemeCss.CORE_THEME_CSS;

    /**
     * The table <code>paradise_forums.core_theme_resources</code>.
     */
    public final CoreThemeResources CORE_THEME_RESOURCES = CoreThemeResources.CORE_THEME_RESOURCES;

    /**
     * The table <code>paradise_forums.core_theme_settings_fields</code>.
     */
    public final CoreThemeSettingsFields CORE_THEME_SETTINGS_FIELDS = CoreThemeSettingsFields.CORE_THEME_SETTINGS_FIELDS;

    /**
     * The table <code>paradise_forums.core_theme_settings_values</code>.
     */
    public final CoreThemeSettingsValues CORE_THEME_SETTINGS_VALUES = CoreThemeSettingsValues.CORE_THEME_SETTINGS_VALUES;

    /**
     * The table <code>paradise_forums.core_theme_templates</code>.
     */
    public final CoreThemeTemplates CORE_THEME_TEMPLATES = CoreThemeTemplates.CORE_THEME_TEMPLATES;

    /**
     * The table <code>paradise_forums.core_themes</code>.
     */
    public final CoreThemes CORE_THEMES = CoreThemes.CORE_THEMES;

    /**
     * The table <code>paradise_forums.core_upgrade_history</code>.
     */
    public final CoreUpgradeHistory CORE_UPGRADE_HISTORY = CoreUpgradeHistory.CORE_UPGRADE_HISTORY;

    /**
     * The table <code>paradise_forums.core_validating</code>.
     */
    public final CoreValidating CORE_VALIDATING = CoreValidating.CORE_VALIDATING;

    /**
     * The table <code>paradise_forums.core_view_updates</code>.
     */
    public final CoreViewUpdates CORE_VIEW_UPDATES = CoreViewUpdates.CORE_VIEW_UPDATES;

    /**
     * The table <code>paradise_forums.core_voters</code>.
     */
    public final CoreVoters CORE_VOTERS = CoreVoters.CORE_VOTERS;

    /**
     * The table <code>paradise_forums.core_widget_areas</code>.
     */
    public final CoreWidgetAreas CORE_WIDGET_AREAS = CoreWidgetAreas.CORE_WIDGET_AREAS;

    /**
     * The table <code>paradise_forums.core_widget_trash</code>.
     */
    public final CoreWidgetTrash CORE_WIDGET_TRASH = CoreWidgetTrash.CORE_WIDGET_TRASH;

    /**
     * The table <code>paradise_forums.core_widgets</code>.
     */
    public final CoreWidgets CORE_WIDGETS = CoreWidgets.CORE_WIDGETS;

    /**
     * The table <code>paradise_forums.forums_answer_ratings</code>.
     */
    public final ForumsAnswerRatings FORUMS_ANSWER_RATINGS = ForumsAnswerRatings.FORUMS_ANSWER_RATINGS;

    /**
     * The table <code>paradise_forums.forums_archive_posts</code>.
     */
    public final ForumsArchivePosts FORUMS_ARCHIVE_POSTS = ForumsArchivePosts.FORUMS_ARCHIVE_POSTS;

    /**
     * The table <code>paradise_forums.forums_archive_rules</code>.
     */
    public final ForumsArchiveRules FORUMS_ARCHIVE_RULES = ForumsArchiveRules.FORUMS_ARCHIVE_RULES;

    /**
     * The table <code>paradise_forums.forums_forums</code>.
     */
    public final ForumsForums FORUMS_FORUMS = ForumsForums.FORUMS_FORUMS;

    /**
     * The table <code>paradise_forums.forums_posts</code>.
     */
    public final ForumsPosts FORUMS_POSTS = ForumsPosts.FORUMS_POSTS;

    /**
     * The table <code>paradise_forums.forums_question_ratings</code>.
     */
    public final ForumsQuestionRatings FORUMS_QUESTION_RATINGS = ForumsQuestionRatings.FORUMS_QUESTION_RATINGS;

    /**
     * The table <code>paradise_forums.forums_topic_mmod</code>.
     */
    public final ForumsTopicMmod FORUMS_TOPIC_MMOD = ForumsTopicMmod.FORUMS_TOPIC_MMOD;

    /**
     * The table <code>paradise_forums.forums_topics</code>.
     */
    public final ForumsTopics FORUMS_TOPICS = ForumsTopics.FORUMS_TOPICS;

    /**
     * The table <code>paradise_forums.forums_view_method</code>.
     */
    public final ForumsViewMethod FORUMS_VIEW_METHOD = ForumsViewMethod.FORUMS_VIEW_METHOD;

    /**
     * The table <code>paradise_forums.patreonintegration_tier</code>.
     */
    public final PatreonintegrationTier PATREONINTEGRATION_TIER = PatreonintegrationTier.PATREONINTEGRATION_TIER;

    /**
     * The table <code>paradise_forums.patreonintegration_user</code>.
     */
    public final PatreonintegrationUser PATREONINTEGRATION_USER = PatreonintegrationUser.PATREONINTEGRATION_USER;

    /**
     * No further instances allowed
     */
    private ParadiseForums() {
        super("paradise_forums", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            BrilliantdiscordApprovalActions.BRILLIANTDISCORD_APPROVAL_ACTIONS,
            BrilliantdiscordBehavior.BRILLIANTDISCORD_BEHAVIOR,
            BrilliantdiscordGroupdata.BRILLIANTDISCORD_GROUPDATA,
            BrilliantdiscordLogs.BRILLIANTDISCORD_LOGS,
            BrilliantdiscordNotifications.BRILLIANTDISCORD_NOTIFICATIONS,
            BrilliantdiscordRatelimits.BRILLIANTDISCORD_RATELIMITS,
            BrilliantdiscordXinvites.BRILLIANTDISCORD_XINVITES,
            CalendarCalendars.CALENDAR_CALENDARS,
            CalendarEventComments.CALENDAR_EVENT_COMMENTS,
            CalendarEventReminders.CALENDAR_EVENT_REMINDERS,
            CalendarEventReviews.CALENDAR_EVENT_REVIEWS,
            CalendarEventRsvp.CALENDAR_EVENT_RSVP,
            CalendarEvents.CALENDAR_EVENTS,
            CalendarImportFeeds.CALENDAR_IMPORT_FEEDS,
            CalendarImportMap.CALENDAR_IMPORT_MAP,
            CalendarVenues.CALENDAR_VENUES,
            ConvertAppSessions.CONVERT_APP_SESSIONS,
            ConvertApps.CONVERT_APPS,
            ConvertBbcodeMediatag.CONVERT_BBCODE_MEDIATAG,
            ConvertCustomBbcode.CONVERT_CUSTOM_BBCODE,
            ConvertLink.CONVERT_LINK,
            ConvertLinkPms.CONVERT_LINK_PMS,
            ConvertLinkPosts.CONVERT_LINK_POSTS,
            ConvertLinkTopics.CONVERT_LINK_TOPICS,
            ConvertLogs.CONVERT_LOGS,
            CoreAchievementsLog.CORE_ACHIEVEMENTS_LOG,
            CoreAchievementsLogMilestones.CORE_ACHIEVEMENTS_LOG_MILESTONES,
            CoreAchievementsRules.CORE_ACHIEVEMENTS_RULES,
            CoreAcpNotifcationsDismissals.CORE_ACP_NOTIFCATIONS_DISMISSALS,
            CoreAcpNotifications.CORE_ACP_NOTIFICATIONS,
            CoreAcpNotificationsPreferences.CORE_ACP_NOTIFICATIONS_PREFERENCES,
            CoreAcpSearchIndex.CORE_ACP_SEARCH_INDEX,
            CoreAcpTabOrder.CORE_ACP_TAB_ORDER,
            CoreAcronyms.CORE_ACRONYMS,
            CoreAdminLoginLogs.CORE_ADMIN_LOGIN_LOGS,
            CoreAdminLogs.CORE_ADMIN_LOGS,
            CoreAdminPermissionRows.CORE_ADMIN_PERMISSION_ROWS,
            CoreAdvertisements.CORE_ADVERTISEMENTS,
            CoreAlerts.CORE_ALERTS,
            CoreAlertsSeen.CORE_ALERTS_SEEN,
            CoreAnnouncements.CORE_ANNOUNCEMENTS,
            CoreAnonymousPosts.CORE_ANONYMOUS_POSTS,
            CoreApiKeys.CORE_API_KEYS,
            CoreApiLogs.CORE_API_LOGS,
            CoreApiWebhookFires.CORE_API_WEBHOOK_FIRES,
            CoreApiWebhooks.CORE_API_WEBHOOKS,
            CoreApplications.CORE_APPLICATIONS,
            CoreApprovalQueue.CORE_APPROVAL_QUEUE,
            CoreAttachments.CORE_ATTACHMENTS,
            CoreAttachmentsMap.CORE_ATTACHMENTS_MAP,
            CoreAutomaticModerationPending.CORE_AUTOMATIC_MODERATION_PENDING,
            CoreAutomaticModerationRules.CORE_AUTOMATIC_MODERATION_RULES,
            CoreAutomaticModerationTypes.CORE_AUTOMATIC_MODERATION_TYPES,
            CoreBadges.CORE_BADGES,
            CoreBanfilters.CORE_BANFILTERS,
            CoreBulkMail.CORE_BULK_MAIL,
            CoreCache.CORE_CACHE,
            CoreClubPages.CORE_CLUB_PAGES,
            CoreClubs.CORE_CLUBS,
            CoreClubsFields.CORE_CLUBS_FIELDS,
            CoreClubsFieldvalues.CORE_CLUBS_FIELDVALUES,
            CoreClubsMemberships.CORE_CLUBS_MEMBERSHIPS,
            CoreClubsNodeMap.CORE_CLUBS_NODE_MAP,
            CoreContactVerify.CORE_CONTACT_VERIFY,
            CoreContentFeatured.CORE_CONTENT_FEATURED,
            CoreContentMeta.CORE_CONTENT_META,
            CoreDeletionLog.CORE_DELETION_LOG,
            CoreDev.CORE_DEV,
            CoreEditHistory.CORE_EDIT_HISTORY,
            CoreEditorStoredReplies.CORE_EDITOR_STORED_REPLIES,
            CoreEmailTemplates.CORE_EMAIL_TEMPLATES,
            CoreEmoticons.CORE_EMOTICONS,
            CoreErrorLogs.CORE_ERROR_LOGS,
            CoreFileLogs.CORE_FILE_LOGS,
            CoreFileStorage.CORE_FILE_STORAGE,
            CoreFiles.CORE_FILES,
            CoreFilesTemp.CORE_FILES_TEMP,
            CoreFollow.CORE_FOLLOW,
            CoreFollowCountCache.CORE_FOLLOW_COUNT_CACHE,
            CoreGeoipCache.CORE_GEOIP_CACHE,
            CoreGoogleauthUsedCodes.CORE_GOOGLEAUTH_USED_CODES,
            CoreGroupPromotions.CORE_GROUP_PROMOTIONS,
            CoreGroups.CORE_GROUPS,
            CoreHooks.CORE_HOOKS,
            CoreIgnoredUsers.CORE_IGNORED_USERS,
            CoreIncomingEmails.CORE_INCOMING_EMAILS,
            CoreIpsBulletins.CORE_IPS_BULLETINS,
            CoreItemMarkers.CORE_ITEM_MARKERS,
            CoreItemMemberMap.CORE_ITEM_MEMBER_MAP,
            CoreItemRedirect.CORE_ITEM_REDIRECT,
            CoreItemStatisticsCache.CORE_ITEM_STATISTICS_CACHE,
            CoreJavascript.CORE_JAVASCRIPT,
            CoreLeaders.CORE_LEADERS,
            CoreLeadersGroups.CORE_LEADERS_GROUPS,
            CoreLog.CORE_LOG,
            CoreLoginFailures.CORE_LOGIN_FAILURES,
            CoreLoginHandlers.CORE_LOGIN_HANDLERS,
            CoreLoginLinks.CORE_LOGIN_LINKS,
            CoreLoginMethods.CORE_LOGIN_METHODS,
            CoreMailErrorLogs.CORE_MAIL_ERROR_LOGS,
            CoreMemberBadges.CORE_MEMBER_BADGES,
            CoreMemberHistory.CORE_MEMBER_HISTORY,
            CoreMemberPrivacyActions.CORE_MEMBER_PRIVACY_ACTIONS,
            CoreMemberRanks.CORE_MEMBER_RANKS,
            CoreMemberRecognize.CORE_MEMBER_RECOGNIZE,
            CoreMemberStatusReplies.CORE_MEMBER_STATUS_REPLIES,
            CoreMemberStatusUpdates.CORE_MEMBER_STATUS_UPDATES,
            CoreMembers.CORE_MEMBERS,
            CoreMembersFeatureSeen.CORE_MEMBERS_FEATURE_SEEN,
            CoreMembersKnownDevices.CORE_MEMBERS_KNOWN_DEVICES,
            CoreMembersKnownIpAddresses.CORE_MEMBERS_KNOWN_IP_ADDRESSES,
            CoreMembersLogins.CORE_MEMBERS_LOGINS,
            CoreMembersWarnActions.CORE_MEMBERS_WARN_ACTIONS,
            CoreMembersWarnLogs.CORE_MEMBERS_WARN_LOGS,
            CoreMembersWarnReasons.CORE_MEMBERS_WARN_REASONS,
            CoreMenu.CORE_MENU,
            CoreMessagePosts.CORE_MESSAGE_POSTS,
            CoreMessageTopicUserMap.CORE_MESSAGE_TOPIC_USER_MAP,
            CoreMessageTopics.CORE_MESSAGE_TOPICS,
            CoreModeratorLogs.CORE_MODERATOR_LOGS,
            CoreModerators.CORE_MODERATORS,
            CoreModules.CORE_MODULES,
            CoreNotificationDefaults.CORE_NOTIFICATION_DEFAULTS,
            CoreNotificationPreferences.CORE_NOTIFICATION_PREFERENCES,
            CoreNotifications.CORE_NOTIFICATIONS,
            CoreNotificationsPwaKeys.CORE_NOTIFICATIONS_PWA_KEYS,
            CoreNotificationsPwaQueue.CORE_NOTIFICATIONS_PWA_QUEUE,
            CoreOauthAuthorizePrompts.CORE_OAUTH_AUTHORIZE_PROMPTS,
            CoreOauthClients.CORE_OAUTH_CLIENTS,
            CoreOauthServerAccessTokens.CORE_OAUTH_SERVER_ACCESS_TOKENS,
            CoreOauthServerAuthorizationCodes.CORE_OAUTH_SERVER_AUTHORIZATION_CODES,
            CoreOutputCache.CORE_OUTPUT_CACHE,
            CorePermissionIndex.CORE_PERMISSION_INDEX,
            CorePfieldsContent.CORE_PFIELDS_CONTENT,
            CorePfieldsData.CORE_PFIELDS_DATA,
            CorePfieldsGroups.CORE_PFIELDS_GROUPS,
            CorePlugins.CORE_PLUGINS,
            CorePointsLog.CORE_POINTS_LOG,
            CorePolls.CORE_POLLS,
            CorePostBeforeRegistering.CORE_POST_BEFORE_REGISTERING,
            CoreProfanityFilters.CORE_PROFANITY_FILTERS,
            CoreProfileCompletion.CORE_PROFILE_COMPLETION,
            CoreProfileSteps.CORE_PROFILE_STEPS,
            CoreQuestionAndAnswer.CORE_QUESTION_AND_ANSWER,
            CoreQueue.CORE_QUEUE,
            CoreRatings.CORE_RATINGS,
            CoreRcAuthorNotificationText.CORE_RC_AUTHOR_NOTIFICATION_TEXT,
            CoreRcComments.CORE_RC_COMMENTS,
            CoreRcIndex.CORE_RC_INDEX,
            CoreRcReports.CORE_RC_REPORTS,
            CoreReactions.CORE_REACTIONS,
            CoreReferralBanners.CORE_REFERRAL_BANNERS,
            CoreReferrals.CORE_REFERRALS,
            CoreReputationIndex.CORE_REPUTATION_INDEX,
            CoreReputationLeaderboardHistory.CORE_REPUTATION_LEADERBOARD_HISTORY,
            CoreReputationLevels.CORE_REPUTATION_LEVELS,
            CoreRssExport.CORE_RSS_EXPORT,
            CoreRssImport.CORE_RSS_IMPORT,
            CoreRssImported.CORE_RSS_IMPORTED,
            CoreS3Deletions.CORE_S3_DELETIONS,
            CoreSavedCharts.CORE_SAVED_CHARTS,
            CoreSearchIndex.CORE_SEARCH_INDEX,
            CoreSearchIndexItemMap.CORE_SEARCH_INDEX_ITEM_MAP,
            CoreSearchIndexTags.CORE_SEARCH_INDEX_TAGS,
            CoreSecurityAnswers.CORE_SECURITY_ANSWERS,
            CoreSecurityQuestions.CORE_SECURITY_QUESTIONS,
            CoreSeoMeta.CORE_SEO_META,
            CoreSessions.CORE_SESSIONS,
            CoreShareLinks.CORE_SHARE_LINKS,
            CoreSitemap.CORE_SITEMAP,
            CoreSocialPromote.CORE_SOCIAL_PROMOTE,
            CoreSocialPromoteContent.CORE_SOCIAL_PROMOTE_CONTENT,
            CoreSocialPromoteSharers.CORE_SOCIAL_PROMOTE_SHARERS,
            CoreSoftDeleteLog.CORE_SOFT_DELETE_LOG,
            CoreSolvedIndex.CORE_SOLVED_INDEX,
            CoreSpamServiceLog.CORE_SPAM_SERVICE_LOG,
            CoreSpamWhitelist.CORE_SPAM_WHITELIST,
            CoreStatistics.CORE_STATISTICS,
            CoreStore.CORE_STORE,
            CoreStreamSubscriptions.CORE_STREAM_SUBSCRIPTIONS,
            CoreStreams.CORE_STREAMS,
            CoreSysConfSettings.CORE_SYS_CONF_SETTINGS,
            CoreSysCpSessions.CORE_SYS_CP_SESSIONS,
            CoreSysLang.CORE_SYS_LANG,
            CoreSysLangWords.CORE_SYS_LANG_WORDS,
            CoreSysSocialGroupMembers.CORE_SYS_SOCIAL_GROUP_MEMBERS,
            CoreSysSocialGroups.CORE_SYS_SOCIAL_GROUPS,
            CoreTags.CORE_TAGS,
            CoreTagsCache.CORE_TAGS_CACHE,
            CoreTagsPerms.CORE_TAGS_PERMS,
            CoreTasks.CORE_TASKS,
            CoreTasksLog.CORE_TASKS_LOG,
            CoreThemeConflict.CORE_THEME_CONFLICT,
            CoreThemeContentHistory.CORE_THEME_CONTENT_HISTORY,
            CoreThemeCss.CORE_THEME_CSS,
            CoreThemeResources.CORE_THEME_RESOURCES,
            CoreThemeSettingsFields.CORE_THEME_SETTINGS_FIELDS,
            CoreThemeSettingsValues.CORE_THEME_SETTINGS_VALUES,
            CoreThemeTemplates.CORE_THEME_TEMPLATES,
            CoreThemes.CORE_THEMES,
            CoreUpgradeHistory.CORE_UPGRADE_HISTORY,
            CoreValidating.CORE_VALIDATING,
            CoreViewUpdates.CORE_VIEW_UPDATES,
            CoreVoters.CORE_VOTERS,
            CoreWidgetAreas.CORE_WIDGET_AREAS,
            CoreWidgetTrash.CORE_WIDGET_TRASH,
            CoreWidgets.CORE_WIDGETS,
            ForumsAnswerRatings.FORUMS_ANSWER_RATINGS,
            ForumsArchivePosts.FORUMS_ARCHIVE_POSTS,
            ForumsArchiveRules.FORUMS_ARCHIVE_RULES,
            ForumsForums.FORUMS_FORUMS,
            ForumsPosts.FORUMS_POSTS,
            ForumsQuestionRatings.FORUMS_QUESTION_RATINGS,
            ForumsTopicMmod.FORUMS_TOPIC_MMOD,
            ForumsTopics.FORUMS_TOPICS,
            ForumsViewMethod.FORUMS_VIEW_METHOD,
            PatreonintegrationTier.PATREONINTEGRATION_TIER,
            PatreonintegrationUser.PATREONINTEGRATION_USER
        );
    }
}
