/*
 * This file is generated by jOOQ.
 */
package me.aa07.paradise.taskdaemon.database.forums.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * Whether the stream sorts newest first or oldest first by default
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum CoreStreamsSort implements EnumType {

    newest("newest"),

    oldest("oldest");

    private final String literal;

    private CoreStreamsSort(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "core_streams_sort";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
