/*
 * This file is generated by jOOQ.
 */
package me.aa07.paradise.taskdaemon.database.forums.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * The requested prompt type
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum CoreOauthAuthorizePromptsPrompt implements EnumType {

    login("login"),

    reauthorize("reauthorize");

    private final String literal;

    private CoreOauthAuthorizePromptsPrompt(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "core_oauth_authorize_prompts_prompt";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
