/*
 * This file is generated by jOOQ.
 */
package me.aa07.paradise.taskdaemon.database.forums.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum CoreFileLogsLogAction implements EnumType {

    move("move"),

    copy("copy"),

    delete("delete"),

    save("save"),

    orphaned("orphaned");

    private final String literal;

    private CoreFileLogsLogAction(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "core_file_logs_log_action";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
