/*
 * This file is generated by jOOQ.
 */
package me.aa07.paradise.taskdaemon.database.forums.tables;


import java.util.Arrays;
import java.util.List;

import me.aa07.paradise.taskdaemon.database.forums.Indexes;
import me.aa07.paradise.taskdaemon.database.forums.Keys;
import me.aa07.paradise.taskdaemon.database.forums.ParadiseForums;
import me.aa07.paradise.taskdaemon.database.forums.tables.records.CoreThemeSettingsFieldsRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row14;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CoreThemeSettingsFields extends TableImpl<CoreThemeSettingsFieldsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>paradise_forums.core_theme_settings_fields</code>
     */
    public static final CoreThemeSettingsFields CORE_THEME_SETTINGS_FIELDS = new CoreThemeSettingsFields();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CoreThemeSettingsFieldsRecord> getRecordType() {
        return CoreThemeSettingsFieldsRecord.class;
    }

    /**
     * The column <code>paradise_forums.core_theme_settings_fields.sc_id</code>.
     */
    public final TableField<CoreThemeSettingsFieldsRecord, Integer> SC_ID = createField(DSL.name("sc_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column
     * <code>paradise_forums.core_theme_settings_fields.sc_set_id</code>.
     */
    public final TableField<CoreThemeSettingsFieldsRecord, Integer> SC_SET_ID = createField(DSL.name("sc_set_id"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column
     * <code>paradise_forums.core_theme_settings_fields.sc_key</code>.
     */
    public final TableField<CoreThemeSettingsFieldsRecord, String> SC_KEY = createField(DSL.name("sc_key"), SQLDataType.VARCHAR(100).nullable(false).defaultValue(DSL.inline("''", SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>paradise_forums.core_theme_settings_fields.sc_type</code>.
     */
    public final TableField<CoreThemeSettingsFieldsRecord, String> SC_TYPE = createField(DSL.name("sc_type"), SQLDataType.VARCHAR(255).nullable(false).defaultValue(DSL.inline("''", SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>paradise_forums.core_theme_settings_fields.sc_multiple</code>.
     */
    public final TableField<CoreThemeSettingsFieldsRecord, Integer> SC_MULTIPLE = createField(DSL.name("sc_multiple"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column
     * <code>paradise_forums.core_theme_settings_fields.sc_content</code>.
     */
    public final TableField<CoreThemeSettingsFieldsRecord, String> SC_CONTENT = createField(DSL.name("sc_content"), SQLDataType.CLOB.defaultValue(DSL.inline("NULL", SQLDataType.CLOB)), this, "");

    /**
     * The column
     * <code>paradise_forums.core_theme_settings_fields.sc_updated</code>.
     */
    public final TableField<CoreThemeSettingsFieldsRecord, UInteger> SC_UPDATED = createField(DSL.name("sc_updated"), SQLDataType.INTEGERUNSIGNED.defaultValue(DSL.inline("0", SQLDataType.INTEGERUNSIGNED)), this, "");

    /**
     * The column
     * <code>paradise_forums.core_theme_settings_fields.sc_app</code>.
     */
    public final TableField<CoreThemeSettingsFieldsRecord, String> SC_APP = createField(DSL.name("sc_app"), SQLDataType.VARCHAR(100).defaultValue(DSL.inline("'core'", SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>paradise_forums.core_theme_settings_fields.sc_default</code>.
     */
    public final TableField<CoreThemeSettingsFieldsRecord, String> SC_DEFAULT = createField(DSL.name("sc_default"), SQLDataType.CLOB.defaultValue(DSL.inline("NULL", SQLDataType.CLOB)), this, "");

    /**
     * The column
     * <code>paradise_forums.core_theme_settings_fields.sc_tab_key</code>.
     */
    public final TableField<CoreThemeSettingsFieldsRecord, String> SC_TAB_KEY = createField(DSL.name("sc_tab_key"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("'custom'", SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>paradise_forums.core_theme_settings_fields.sc_show_in_vse</code>.
     * Show this theme setting in the easy mode editor
     */
    public final TableField<CoreThemeSettingsFieldsRecord, UInteger> SC_SHOW_IN_VSE = createField(DSL.name("sc_show_in_vse"), SQLDataType.INTEGERUNSIGNED.defaultValue(DSL.inline("0", SQLDataType.INTEGERUNSIGNED)), this, "Show this theme setting in the easy mode editor");

    /**
     * The column
     * <code>paradise_forums.core_theme_settings_fields.sc_title</code>.
     */
    public final TableField<CoreThemeSettingsFieldsRecord, String> SC_TITLE = createField(DSL.name("sc_title"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>paradise_forums.core_theme_settings_fields.sc_order</code>.
     */
    public final TableField<CoreThemeSettingsFieldsRecord, UInteger> SC_ORDER = createField(DSL.name("sc_order"), SQLDataType.INTEGERUNSIGNED.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGERUNSIGNED)), this, "");

    /**
     * The column
     * <code>paradise_forums.core_theme_settings_fields.sc_condition</code>.
     */
    public final TableField<CoreThemeSettingsFieldsRecord, String> SC_CONDITION = createField(DSL.name("sc_condition"), SQLDataType.CLOB.defaultValue(DSL.inline("NULL", SQLDataType.CLOB)), this, "");

    private CoreThemeSettingsFields(Name alias, Table<CoreThemeSettingsFieldsRecord> aliased) {
        this(alias, aliased, null);
    }

    private CoreThemeSettingsFields(Name alias, Table<CoreThemeSettingsFieldsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>paradise_forums.core_theme_settings_fields</code>
     * table reference
     */
    public CoreThemeSettingsFields(String alias) {
        this(DSL.name(alias), CORE_THEME_SETTINGS_FIELDS);
    }

    /**
     * Create an aliased <code>paradise_forums.core_theme_settings_fields</code>
     * table reference
     */
    public CoreThemeSettingsFields(Name alias) {
        this(alias, CORE_THEME_SETTINGS_FIELDS);
    }

    /**
     * Create a <code>paradise_forums.core_theme_settings_fields</code> table
     * reference
     */
    public CoreThemeSettingsFields() {
        this(DSL.name("core_theme_settings_fields"), null);
    }

    public <O extends Record> CoreThemeSettingsFields(Table<O> child, ForeignKey<O, CoreThemeSettingsFieldsRecord> key) {
        super(child, key, CORE_THEME_SETTINGS_FIELDS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : ParadiseForums.PARADISE_FORUMS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.CORE_THEME_SETTINGS_FIELDS_SC_LOOKUP);
    }

    @Override
    public Identity<CoreThemeSettingsFieldsRecord, Integer> getIdentity() {
        return (Identity<CoreThemeSettingsFieldsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<CoreThemeSettingsFieldsRecord> getPrimaryKey() {
        return Keys.KEY_CORE_THEME_SETTINGS_FIELDS_PRIMARY;
    }

    @Override
    public List<UniqueKey<CoreThemeSettingsFieldsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_CORE_THEME_SETTINGS_FIELDS_REPLACE_KEY);
    }

    @Override
    public CoreThemeSettingsFields as(String alias) {
        return new CoreThemeSettingsFields(DSL.name(alias), this);
    }

    @Override
    public CoreThemeSettingsFields as(Name alias) {
        return new CoreThemeSettingsFields(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CoreThemeSettingsFields rename(String name) {
        return new CoreThemeSettingsFields(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CoreThemeSettingsFields rename(Name name) {
        return new CoreThemeSettingsFields(name, null);
    }

    // -------------------------------------------------------------------------
    // Row14 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row14<Integer, Integer, String, String, Integer, String, UInteger, String, String, String, UInteger, String, UInteger, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }
}
