/*
 * This file is generated by jOOQ.
 */
package me.aa07.paradise.taskdaemon.database.forums.tables;


import java.util.Arrays;
import java.util.List;

import me.aa07.paradise.taskdaemon.database.forums.Indexes;
import me.aa07.paradise.taskdaemon.database.forums.Keys;
import me.aa07.paradise.taskdaemon.database.forums.ParadiseForums;
import me.aa07.paradise.taskdaemon.database.forums.tables.records.CoreContentMetaRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CoreContentMeta extends TableImpl<CoreContentMetaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>paradise_forums.core_content_meta</code>
     */
    public static final CoreContentMeta CORE_CONTENT_META = new CoreContentMeta();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CoreContentMetaRecord> getRecordType() {
        return CoreContentMetaRecord.class;
    }

    /**
     * The column <code>paradise_forums.core_content_meta.meta_id</code>. ID
     * Number
     */
    public final TableField<CoreContentMetaRecord, ULong> META_ID = createField(DSL.name("meta_id"), SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "ID Number");

    /**
     * The column <code>paradise_forums.core_content_meta.meta_class</code>. The
     * Item Content Class
     */
    public final TableField<CoreContentMetaRecord, String> META_CLASS = createField(DSL.name("meta_class"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "The Item Content Class");

    /**
     * The column <code>paradise_forums.core_content_meta.meta_item_id</code>.
     * The Item Primary ID
     */
    public final TableField<CoreContentMetaRecord, Long> META_ITEM_ID = createField(DSL.name("meta_item_id"), SQLDataType.BIGINT.defaultValue(DSL.inline("NULL", SQLDataType.BIGINT)), this, "The Item Primary ID");

    /**
     * The column <code>paradise_forums.core_content_meta.meta_type</code>. The
     * Type of Meta Data
     */
    public final TableField<CoreContentMetaRecord, String> META_TYPE = createField(DSL.name("meta_type"), SQLDataType.VARCHAR(100).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "The Type of Meta Data");

    /**
     * The column <code>paradise_forums.core_content_meta.meta_data</code>. The
     * data
     */
    public final TableField<CoreContentMetaRecord, byte[]> META_DATA = createField(DSL.name("meta_data"), SQLDataType.BLOB.defaultValue(DSL.inline("NULL", SQLDataType.BLOB)), this, "The data");

    /**
     * The column
     * <code>paradise_forums.core_content_meta.meta_item_author</code>.
     */
    public final TableField<CoreContentMetaRecord, UInteger> META_ITEM_AUTHOR = createField(DSL.name("meta_item_author"), SQLDataType.INTEGERUNSIGNED.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGERUNSIGNED)), this, "");

    /**
     * The column <code>paradise_forums.core_content_meta.meta_added</code>.
     */
    public final TableField<CoreContentMetaRecord, UInteger> META_ADDED = createField(DSL.name("meta_added"), SQLDataType.INTEGERUNSIGNED.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGERUNSIGNED)), this, "");

    private CoreContentMeta(Name alias, Table<CoreContentMetaRecord> aliased) {
        this(alias, aliased, null);
    }

    private CoreContentMeta(Name alias, Table<CoreContentMetaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>paradise_forums.core_content_meta</code> table
     * reference
     */
    public CoreContentMeta(String alias) {
        this(DSL.name(alias), CORE_CONTENT_META);
    }

    /**
     * Create an aliased <code>paradise_forums.core_content_meta</code> table
     * reference
     */
    public CoreContentMeta(Name alias) {
        this(alias, CORE_CONTENT_META);
    }

    /**
     * Create a <code>paradise_forums.core_content_meta</code> table reference
     */
    public CoreContentMeta() {
        this(DSL.name("core_content_meta"), null);
    }

    public <O extends Record> CoreContentMeta(Table<O> child, ForeignKey<O, CoreContentMetaRecord> key) {
        super(child, key, CORE_CONTENT_META);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : ParadiseForums.PARADISE_FORUMS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.CORE_CONTENT_META_META_CONTENT);
    }

    @Override
    public Identity<CoreContentMetaRecord, ULong> getIdentity() {
        return (Identity<CoreContentMetaRecord, ULong>) super.getIdentity();
    }

    @Override
    public UniqueKey<CoreContentMetaRecord> getPrimaryKey() {
        return Keys.KEY_CORE_CONTENT_META_PRIMARY;
    }

    @Override
    public CoreContentMeta as(String alias) {
        return new CoreContentMeta(DSL.name(alias), this);
    }

    @Override
    public CoreContentMeta as(Name alias) {
        return new CoreContentMeta(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CoreContentMeta rename(String name) {
        return new CoreContentMeta(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CoreContentMeta rename(Name name) {
        return new CoreContentMeta(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<ULong, String, Long, String, byte[], UInteger, UInteger> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
