/*
 * This file is generated by jOOQ.
 */
package me.aa07.paradise.taskdaemon.database.forums.tables;


import java.util.Arrays;
import java.util.List;

import me.aa07.paradise.taskdaemon.database.forums.Keys;
import me.aa07.paradise.taskdaemon.database.forums.ParadiseForums;
import me.aa07.paradise.taskdaemon.database.forums.tables.records.PatreonintegrationTierRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row10;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PatreonintegrationTier extends TableImpl<PatreonintegrationTierRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>paradise_forums.patreonintegration_tier</code>
     */
    public static final PatreonintegrationTier PATREONINTEGRATION_TIER = new PatreonintegrationTier();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PatreonintegrationTierRecord> getRecordType() {
        return PatreonintegrationTierRecord.class;
    }

    /**
     * The column <code>paradise_forums.patreonintegration_tier.id</code>. ID
     * Number
     */
    public final TableField<PatreonintegrationTierRecord, UInteger> ID = createField(DSL.name("id"), SQLDataType.INTEGERUNSIGNED.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGERUNSIGNED)), this, "ID Number");

    /**
     * The column <code>paradise_forums.patreonintegration_tier.title</code>.
     */
    public final TableField<PatreonintegrationTierRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(1024).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>paradise_forums.patreonintegration_tier.description</code>.
     */
    public final TableField<PatreonintegrationTierRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB.defaultValue(DSL.inline("NULL", SQLDataType.CLOB)), this, "");

    /**
     * The column <code>paradise_forums.patreonintegration_tier.amount</code>.
     */
    public final TableField<PatreonintegrationTierRecord, Integer> AMOUNT = createField(DSL.name("amount"), SQLDataType.INTEGER.defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column
     * <code>paradise_forums.patreonintegration_tier.image_url</code>.
     */
    public final TableField<PatreonintegrationTierRecord, String> IMAGE_URL = createField(DSL.name("image_url"), SQLDataType.VARCHAR(1024).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>paradise_forums.patreonintegration_tier.url</code>.
     */
    public final TableField<PatreonintegrationTierRecord, String> URL = createField(DSL.name("url"), SQLDataType.VARCHAR(1024).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>paradise_forums.patreonintegration_tier.updated</code>.
     */
    public final TableField<PatreonintegrationTierRecord, Integer> UPDATED = createField(DSL.name("updated"), SQLDataType.INTEGER.defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column
     * <code>paradise_forums.patreonintegration_tier.patron_count</code>.
     */
    public final TableField<PatreonintegrationTierRecord, Integer> PATRON_COUNT = createField(DSL.name("patron_count"), SQLDataType.INTEGER.defaultValue(DSL.inline("NULL", SQLDataType.INTEGER)), this, "");

    /**
     * The column
     * <code>paradise_forums.patreonintegration_tier.usergroups</code>.
     */
    public final TableField<PatreonintegrationTierRecord, String> USERGROUPS = createField(DSL.name("usergroups"), SQLDataType.VARCHAR(1024).nullable(false).defaultValue(DSL.inline("'0'", SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>paradise_forums.patreonintegration_tier.primary_group</code>.
     */
    public final TableField<PatreonintegrationTierRecord, Integer> PRIMARY_GROUP = createField(DSL.name("primary_group"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    private PatreonintegrationTier(Name alias, Table<PatreonintegrationTierRecord> aliased) {
        this(alias, aliased, null);
    }

    private PatreonintegrationTier(Name alias, Table<PatreonintegrationTierRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>paradise_forums.patreonintegration_tier</code>
     * table reference
     */
    public PatreonintegrationTier(String alias) {
        this(DSL.name(alias), PATREONINTEGRATION_TIER);
    }

    /**
     * Create an aliased <code>paradise_forums.patreonintegration_tier</code>
     * table reference
     */
    public PatreonintegrationTier(Name alias) {
        this(alias, PATREONINTEGRATION_TIER);
    }

    /**
     * Create a <code>paradise_forums.patreonintegration_tier</code> table
     * reference
     */
    public PatreonintegrationTier() {
        this(DSL.name("patreonintegration_tier"), null);
    }

    public <O extends Record> PatreonintegrationTier(Table<O> child, ForeignKey<O, PatreonintegrationTierRecord> key) {
        super(child, key, PATREONINTEGRATION_TIER);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : ParadiseForums.PARADISE_FORUMS;
    }

    @Override
    public List<UniqueKey<PatreonintegrationTierRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_PATREONINTEGRATION_TIER_UID);
    }

    @Override
    public PatreonintegrationTier as(String alias) {
        return new PatreonintegrationTier(DSL.name(alias), this);
    }

    @Override
    public PatreonintegrationTier as(Name alias) {
        return new PatreonintegrationTier(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PatreonintegrationTier rename(String name) {
        return new PatreonintegrationTier(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PatreonintegrationTier rename(Name name) {
        return new PatreonintegrationTier(name, null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<UInteger, String, String, Integer, String, String, Integer, Integer, String, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }
}
