/*
 * This file is generated by jOOQ.
 */
package me.aa07.paradise.taskdaemon.database.forums.tables.records;


import me.aa07.paradise.taskdaemon.database.forums.tables.CoreAcpNotifcationsDismissals;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CoreAcpNotifcationsDismissalsRecord extends UpdatableRecordImpl<CoreAcpNotifcationsDismissalsRecord> implements Record3<ULong, ULong, UInteger> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>paradise_forums.core_acp_notifcations_dismissals.notification</code>.
     * Notification ID Number
     */
    public void setNotification(ULong value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>paradise_forums.core_acp_notifcations_dismissals.notification</code>.
     * Notification ID Number
     */
    public ULong getNotification() {
        return (ULong) get(0);
    }

    /**
     * Setter for
     * <code>paradise_forums.core_acp_notifcations_dismissals.member</code>.
     * Member ID Number
     */
    public void setMember(ULong value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>paradise_forums.core_acp_notifcations_dismissals.member</code>.
     * Member ID Number
     */
    public ULong getMember() {
        return (ULong) get(1);
    }

    /**
     * Setter for
     * <code>paradise_forums.core_acp_notifcations_dismissals.time</code>. Unix
     * timestamp of when the notification was dismissed
     */
    public void setTime(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>paradise_forums.core_acp_notifcations_dismissals.time</code>. Unix
     * timestamp of when the notification was dismissed
     */
    public UInteger getTime() {
        return (UInteger) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<ULong, ULong> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<ULong, ULong, UInteger> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<ULong, ULong, UInteger> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<ULong> field1() {
        return CoreAcpNotifcationsDismissals.CORE_ACP_NOTIFCATIONS_DISMISSALS.NOTIFICATION;
    }

    @Override
    public Field<ULong> field2() {
        return CoreAcpNotifcationsDismissals.CORE_ACP_NOTIFCATIONS_DISMISSALS.MEMBER;
    }

    @Override
    public Field<UInteger> field3() {
        return CoreAcpNotifcationsDismissals.CORE_ACP_NOTIFCATIONS_DISMISSALS.TIME;
    }

    @Override
    public ULong component1() {
        return getNotification();
    }

    @Override
    public ULong component2() {
        return getMember();
    }

    @Override
    public UInteger component3() {
        return getTime();
    }

    @Override
    public ULong value1() {
        return getNotification();
    }

    @Override
    public ULong value2() {
        return getMember();
    }

    @Override
    public UInteger value3() {
        return getTime();
    }

    @Override
    public CoreAcpNotifcationsDismissalsRecord value1(ULong value) {
        setNotification(value);
        return this;
    }

    @Override
    public CoreAcpNotifcationsDismissalsRecord value2(ULong value) {
        setMember(value);
        return this;
    }

    @Override
    public CoreAcpNotifcationsDismissalsRecord value3(UInteger value) {
        setTime(value);
        return this;
    }

    @Override
    public CoreAcpNotifcationsDismissalsRecord values(ULong value1, ULong value2, UInteger value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CoreAcpNotifcationsDismissalsRecord
     */
    public CoreAcpNotifcationsDismissalsRecord() {
        super(CoreAcpNotifcationsDismissals.CORE_ACP_NOTIFCATIONS_DISMISSALS);
    }

    /**
     * Create a detached, initialised CoreAcpNotifcationsDismissalsRecord
     */
    public CoreAcpNotifcationsDismissalsRecord(ULong notification, ULong member, UInteger time) {
        super(CoreAcpNotifcationsDismissals.CORE_ACP_NOTIFCATIONS_DISMISSALS);

        setNotification(notification);
        setMember(member);
        setTime(time);
    }
}
