/*
 * This file is generated by jOOQ.
 */
package me.aa07.paradise.taskdaemon.database.forums.tables.records;


import me.aa07.paradise.taskdaemon.database.forums.tables.CoreIgnoredUsers;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CoreIgnoredUsersRecord extends UpdatableRecordImpl<CoreIgnoredUsersRecord> implements Record7<Integer, Integer, Integer, Integer, Integer, Integer, UByte> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>paradise_forums.core_ignored_users.ignore_id</code>.
     */
    public void setIgnoreId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>paradise_forums.core_ignored_users.ignore_id</code>.
     */
    public Integer getIgnoreId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>paradise_forums.core_ignored_users.ignore_owner_id</code>.
     */
    public void setIgnoreOwnerId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>paradise_forums.core_ignored_users.ignore_owner_id</code>.
     */
    public Integer getIgnoreOwnerId() {
        return (Integer) get(1);
    }

    /**
     * Setter for
     * <code>paradise_forums.core_ignored_users.ignore_ignore_id</code>.
     */
    public void setIgnoreIgnoreId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>paradise_forums.core_ignored_users.ignore_ignore_id</code>.
     */
    public Integer getIgnoreIgnoreId() {
        return (Integer) get(2);
    }

    /**
     * Setter for
     * <code>paradise_forums.core_ignored_users.ignore_messages</code>.
     */
    public void setIgnoreMessages(Integer value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>paradise_forums.core_ignored_users.ignore_messages</code>.
     */
    public Integer getIgnoreMessages() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>paradise_forums.core_ignored_users.ignore_topics</code>.
     */
    public void setIgnoreTopics(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>paradise_forums.core_ignored_users.ignore_topics</code>.
     */
    public Integer getIgnoreTopics() {
        return (Integer) get(4);
    }

    /**
     * Setter for
     * <code>paradise_forums.core_ignored_users.ignore_signatures</code>.
     */
    public void setIgnoreSignatures(Integer value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>paradise_forums.core_ignored_users.ignore_signatures</code>.
     */
    public Integer getIgnoreSignatures() {
        return (Integer) get(5);
    }

    /**
     * Setter for
     * <code>paradise_forums.core_ignored_users.ignore_mentions</code>.
     */
    public void setIgnoreMentions(UByte value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>paradise_forums.core_ignored_users.ignore_mentions</code>.
     */
    public UByte getIgnoreMentions() {
        return (UByte) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, Integer, Integer, Integer, Integer, Integer, UByte> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, Integer, Integer, Integer, Integer, Integer, UByte> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return CoreIgnoredUsers.CORE_IGNORED_USERS.IGNORE_ID;
    }

    @Override
    public Field<Integer> field2() {
        return CoreIgnoredUsers.CORE_IGNORED_USERS.IGNORE_OWNER_ID;
    }

    @Override
    public Field<Integer> field3() {
        return CoreIgnoredUsers.CORE_IGNORED_USERS.IGNORE_IGNORE_ID;
    }

    @Override
    public Field<Integer> field4() {
        return CoreIgnoredUsers.CORE_IGNORED_USERS.IGNORE_MESSAGES;
    }

    @Override
    public Field<Integer> field5() {
        return CoreIgnoredUsers.CORE_IGNORED_USERS.IGNORE_TOPICS;
    }

    @Override
    public Field<Integer> field6() {
        return CoreIgnoredUsers.CORE_IGNORED_USERS.IGNORE_SIGNATURES;
    }

    @Override
    public Field<UByte> field7() {
        return CoreIgnoredUsers.CORE_IGNORED_USERS.IGNORE_MENTIONS;
    }

    @Override
    public Integer component1() {
        return getIgnoreId();
    }

    @Override
    public Integer component2() {
        return getIgnoreOwnerId();
    }

    @Override
    public Integer component3() {
        return getIgnoreIgnoreId();
    }

    @Override
    public Integer component4() {
        return getIgnoreMessages();
    }

    @Override
    public Integer component5() {
        return getIgnoreTopics();
    }

    @Override
    public Integer component6() {
        return getIgnoreSignatures();
    }

    @Override
    public UByte component7() {
        return getIgnoreMentions();
    }

    @Override
    public Integer value1() {
        return getIgnoreId();
    }

    @Override
    public Integer value2() {
        return getIgnoreOwnerId();
    }

    @Override
    public Integer value3() {
        return getIgnoreIgnoreId();
    }

    @Override
    public Integer value4() {
        return getIgnoreMessages();
    }

    @Override
    public Integer value5() {
        return getIgnoreTopics();
    }

    @Override
    public Integer value6() {
        return getIgnoreSignatures();
    }

    @Override
    public UByte value7() {
        return getIgnoreMentions();
    }

    @Override
    public CoreIgnoredUsersRecord value1(Integer value) {
        setIgnoreId(value);
        return this;
    }

    @Override
    public CoreIgnoredUsersRecord value2(Integer value) {
        setIgnoreOwnerId(value);
        return this;
    }

    @Override
    public CoreIgnoredUsersRecord value3(Integer value) {
        setIgnoreIgnoreId(value);
        return this;
    }

    @Override
    public CoreIgnoredUsersRecord value4(Integer value) {
        setIgnoreMessages(value);
        return this;
    }

    @Override
    public CoreIgnoredUsersRecord value5(Integer value) {
        setIgnoreTopics(value);
        return this;
    }

    @Override
    public CoreIgnoredUsersRecord value6(Integer value) {
        setIgnoreSignatures(value);
        return this;
    }

    @Override
    public CoreIgnoredUsersRecord value7(UByte value) {
        setIgnoreMentions(value);
        return this;
    }

    @Override
    public CoreIgnoredUsersRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6, UByte value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CoreIgnoredUsersRecord
     */
    public CoreIgnoredUsersRecord() {
        super(CoreIgnoredUsers.CORE_IGNORED_USERS);
    }

    /**
     * Create a detached, initialised CoreIgnoredUsersRecord
     */
    public CoreIgnoredUsersRecord(Integer ignoreId, Integer ignoreOwnerId, Integer ignoreIgnoreId, Integer ignoreMessages, Integer ignoreTopics, Integer ignoreSignatures, UByte ignoreMentions) {
        super(CoreIgnoredUsers.CORE_IGNORED_USERS);

        setIgnoreId(ignoreId);
        setIgnoreOwnerId(ignoreOwnerId);
        setIgnoreIgnoreId(ignoreIgnoreId);
        setIgnoreMessages(ignoreMessages);
        setIgnoreTopics(ignoreTopics);
        setIgnoreSignatures(ignoreSignatures);
        setIgnoreMentions(ignoreMentions);
    }
}
