/*
 * This file is generated by jOOQ.
 */
package me.aa07.paradise.taskdaemon.database.forums.tables.records;


import me.aa07.paradise.taskdaemon.database.forums.tables.CoreSocialPromoteSharers;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CoreSocialPromoteSharersRecord extends UpdatableRecordImpl<CoreSocialPromoteSharersRecord> implements Record4<Integer, String, String, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>paradise_forums.core_social_promote_sharers.sharer_id</code>.
     */
    public void setSharerId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>paradise_forums.core_social_promote_sharers.sharer_id</code>.
     */
    public Integer getSharerId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>paradise_forums.core_social_promote_sharers.sharer_key</code>.
     */
    public void setSharerKey(String value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>paradise_forums.core_social_promote_sharers.sharer_key</code>.
     */
    public String getSharerKey() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>paradise_forums.core_social_promote_sharers.sharer_settings</code>.
     * JSON array of promotion settings
     */
    public void setSharerSettings(String value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>paradise_forums.core_social_promote_sharers.sharer_settings</code>.
     * JSON array of promotion settings
     */
    public String getSharerSettings() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>paradise_forums.core_social_promote_sharers.sharer_enabled</code>.
     */
    public void setSharerEnabled(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>paradise_forums.core_social_promote_sharers.sharer_enabled</code>.
     */
    public Boolean getSharerEnabled() {
        return (Boolean) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, Boolean> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, String, Boolean> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return CoreSocialPromoteSharers.CORE_SOCIAL_PROMOTE_SHARERS.SHARER_ID;
    }

    @Override
    public Field<String> field2() {
        return CoreSocialPromoteSharers.CORE_SOCIAL_PROMOTE_SHARERS.SHARER_KEY;
    }

    @Override
    public Field<String> field3() {
        return CoreSocialPromoteSharers.CORE_SOCIAL_PROMOTE_SHARERS.SHARER_SETTINGS;
    }

    @Override
    public Field<Boolean> field4() {
        return CoreSocialPromoteSharers.CORE_SOCIAL_PROMOTE_SHARERS.SHARER_ENABLED;
    }

    @Override
    public Integer component1() {
        return getSharerId();
    }

    @Override
    public String component2() {
        return getSharerKey();
    }

    @Override
    public String component3() {
        return getSharerSettings();
    }

    @Override
    public Boolean component4() {
        return getSharerEnabled();
    }

    @Override
    public Integer value1() {
        return getSharerId();
    }

    @Override
    public String value2() {
        return getSharerKey();
    }

    @Override
    public String value3() {
        return getSharerSettings();
    }

    @Override
    public Boolean value4() {
        return getSharerEnabled();
    }

    @Override
    public CoreSocialPromoteSharersRecord value1(Integer value) {
        setSharerId(value);
        return this;
    }

    @Override
    public CoreSocialPromoteSharersRecord value2(String value) {
        setSharerKey(value);
        return this;
    }

    @Override
    public CoreSocialPromoteSharersRecord value3(String value) {
        setSharerSettings(value);
        return this;
    }

    @Override
    public CoreSocialPromoteSharersRecord value4(Boolean value) {
        setSharerEnabled(value);
        return this;
    }

    @Override
    public CoreSocialPromoteSharersRecord values(Integer value1, String value2, String value3, Boolean value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CoreSocialPromoteSharersRecord
     */
    public CoreSocialPromoteSharersRecord() {
        super(CoreSocialPromoteSharers.CORE_SOCIAL_PROMOTE_SHARERS);
    }

    /**
     * Create a detached, initialised CoreSocialPromoteSharersRecord
     */
    public CoreSocialPromoteSharersRecord(Integer sharerId, String sharerKey, String sharerSettings, Boolean sharerEnabled) {
        super(CoreSocialPromoteSharers.CORE_SOCIAL_PROMOTE_SHARERS);

        setSharerId(sharerId);
        setSharerKey(sharerKey);
        setSharerSettings(sharerSettings);
        setSharerEnabled(sharerEnabled);
    }
}
