/*
 * This file is generated by jOOQ.
 */
package me.aa07.paradise.taskdaemon.database.authentik.tables.records;


import java.util.UUID;

import me.aa07.paradise.taskdaemon.database.authentik.tables.AuthentikStagesAuthenticatorEmailAuthenticatoremailstage;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthentikStagesAuthenticatorEmailAuthenticatoremailstageRecord extends UpdatableRecordImpl<AuthentikStagesAuthenticatorEmailAuthenticatoremailstageRecord> implements Record15<UUID, String, Boolean, String, Integer, String, String, Boolean, Boolean, Integer, String, String, String, String, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>public.authentik_stages_authenticator_email_authenticatoremailstage.stage_ptr_id</code>.
     */
    public void setStagePtrId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>public.authentik_stages_authenticator_email_authenticatoremailstage.stage_ptr_id</code>.
     */
    public UUID getStagePtrId() {
        return (UUID) get(0);
    }

    /**
     * Setter for
     * <code>public.authentik_stages_authenticator_email_authenticatoremailstage.friendly_name</code>.
     */
    public void setFriendlyName(String value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>public.authentik_stages_authenticator_email_authenticatoremailstage.friendly_name</code>.
     */
    public String getFriendlyName() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>public.authentik_stages_authenticator_email_authenticatoremailstage.use_global_settings</code>.
     */
    public void setUseGlobalSettings(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>public.authentik_stages_authenticator_email_authenticatoremailstage.use_global_settings</code>.
     */
    public Boolean getUseGlobalSettings() {
        return (Boolean) get(2);
    }

    /**
     * Setter for
     * <code>public.authentik_stages_authenticator_email_authenticatoremailstage.host</code>.
     */
    public void setHost(String value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>public.authentik_stages_authenticator_email_authenticatoremailstage.host</code>.
     */
    public String getHost() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>public.authentik_stages_authenticator_email_authenticatoremailstage.port</code>.
     */
    public void setPort(Integer value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>public.authentik_stages_authenticator_email_authenticatoremailstage.port</code>.
     */
    public Integer getPort() {
        return (Integer) get(4);
    }

    /**
     * Setter for
     * <code>public.authentik_stages_authenticator_email_authenticatoremailstage.username</code>.
     */
    public void setUsername(String value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>public.authentik_stages_authenticator_email_authenticatoremailstage.username</code>.
     */
    public String getUsername() {
        return (String) get(5);
    }

    /**
     * Setter for
     * <code>public.authentik_stages_authenticator_email_authenticatoremailstage.password</code>.
     */
    public void setPassword(String value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>public.authentik_stages_authenticator_email_authenticatoremailstage.password</code>.
     */
    public String getPassword() {
        return (String) get(6);
    }

    /**
     * Setter for
     * <code>public.authentik_stages_authenticator_email_authenticatoremailstage.use_tls</code>.
     */
    public void setUseTls(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>public.authentik_stages_authenticator_email_authenticatoremailstage.use_tls</code>.
     */
    public Boolean getUseTls() {
        return (Boolean) get(7);
    }

    /**
     * Setter for
     * <code>public.authentik_stages_authenticator_email_authenticatoremailstage.use_ssl</code>.
     */
    public void setUseSsl(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>public.authentik_stages_authenticator_email_authenticatoremailstage.use_ssl</code>.
     */
    public Boolean getUseSsl() {
        return (Boolean) get(8);
    }

    /**
     * Setter for
     * <code>public.authentik_stages_authenticator_email_authenticatoremailstage.timeout</code>.
     */
    public void setTimeout(Integer value) {
        set(9, value);
    }

    /**
     * Getter for
     * <code>public.authentik_stages_authenticator_email_authenticatoremailstage.timeout</code>.
     */
    public Integer getTimeout() {
        return (Integer) get(9);
    }

    /**
     * Setter for
     * <code>public.authentik_stages_authenticator_email_authenticatoremailstage.from_address</code>.
     */
    public void setFromAddress(String value) {
        set(10, value);
    }

    /**
     * Getter for
     * <code>public.authentik_stages_authenticator_email_authenticatoremailstage.from_address</code>.
     */
    public String getFromAddress() {
        return (String) get(10);
    }

    /**
     * Setter for
     * <code>public.authentik_stages_authenticator_email_authenticatoremailstage.token_expiry</code>.
     */
    public void setTokenExpiry(String value) {
        set(11, value);
    }

    /**
     * Getter for
     * <code>public.authentik_stages_authenticator_email_authenticatoremailstage.token_expiry</code>.
     */
    public String getTokenExpiry() {
        return (String) get(11);
    }

    /**
     * Setter for
     * <code>public.authentik_stages_authenticator_email_authenticatoremailstage.subject</code>.
     */
    public void setSubject(String value) {
        set(12, value);
    }

    /**
     * Getter for
     * <code>public.authentik_stages_authenticator_email_authenticatoremailstage.subject</code>.
     */
    public String getSubject() {
        return (String) get(12);
    }

    /**
     * Setter for
     * <code>public.authentik_stages_authenticator_email_authenticatoremailstage.template</code>.
     */
    public void setTemplate(String value) {
        set(13, value);
    }

    /**
     * Getter for
     * <code>public.authentik_stages_authenticator_email_authenticatoremailstage.template</code>.
     */
    public String getTemplate() {
        return (String) get(13);
    }

    /**
     * Setter for
     * <code>public.authentik_stages_authenticator_email_authenticatoremailstage.configure_flow_id</code>.
     */
    public void setConfigureFlowId(UUID value) {
        set(14, value);
    }

    /**
     * Getter for
     * <code>public.authentik_stages_authenticator_email_authenticatoremailstage.configure_flow_id</code>.
     */
    public UUID getConfigureFlowId() {
        return (UUID) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row15<UUID, String, Boolean, String, Integer, String, String, Boolean, Boolean, Integer, String, String, String, String, UUID> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    @Override
    public Row15<UUID, String, Boolean, String, Integer, String, String, Boolean, Boolean, Integer, String, String, String, String, UUID> valuesRow() {
        return (Row15) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return AuthentikStagesAuthenticatorEmailAuthenticatoremailstage.AUTHENTIK_STAGES_AUTHENTICATOR_EMAIL_AUTHENTICATOREMAILSTAGE.STAGE_PTR_ID;
    }

    @Override
    public Field<String> field2() {
        return AuthentikStagesAuthenticatorEmailAuthenticatoremailstage.AUTHENTIK_STAGES_AUTHENTICATOR_EMAIL_AUTHENTICATOREMAILSTAGE.FRIENDLY_NAME;
    }

    @Override
    public Field<Boolean> field3() {
        return AuthentikStagesAuthenticatorEmailAuthenticatoremailstage.AUTHENTIK_STAGES_AUTHENTICATOR_EMAIL_AUTHENTICATOREMAILSTAGE.USE_GLOBAL_SETTINGS;
    }

    @Override
    public Field<String> field4() {
        return AuthentikStagesAuthenticatorEmailAuthenticatoremailstage.AUTHENTIK_STAGES_AUTHENTICATOR_EMAIL_AUTHENTICATOREMAILSTAGE.HOST;
    }

    @Override
    public Field<Integer> field5() {
        return AuthentikStagesAuthenticatorEmailAuthenticatoremailstage.AUTHENTIK_STAGES_AUTHENTICATOR_EMAIL_AUTHENTICATOREMAILSTAGE.PORT;
    }

    @Override
    public Field<String> field6() {
        return AuthentikStagesAuthenticatorEmailAuthenticatoremailstage.AUTHENTIK_STAGES_AUTHENTICATOR_EMAIL_AUTHENTICATOREMAILSTAGE.USERNAME;
    }

    @Override
    public Field<String> field7() {
        return AuthentikStagesAuthenticatorEmailAuthenticatoremailstage.AUTHENTIK_STAGES_AUTHENTICATOR_EMAIL_AUTHENTICATOREMAILSTAGE.PASSWORD;
    }

    @Override
    public Field<Boolean> field8() {
        return AuthentikStagesAuthenticatorEmailAuthenticatoremailstage.AUTHENTIK_STAGES_AUTHENTICATOR_EMAIL_AUTHENTICATOREMAILSTAGE.USE_TLS;
    }

    @Override
    public Field<Boolean> field9() {
        return AuthentikStagesAuthenticatorEmailAuthenticatoremailstage.AUTHENTIK_STAGES_AUTHENTICATOR_EMAIL_AUTHENTICATOREMAILSTAGE.USE_SSL;
    }

    @Override
    public Field<Integer> field10() {
        return AuthentikStagesAuthenticatorEmailAuthenticatoremailstage.AUTHENTIK_STAGES_AUTHENTICATOR_EMAIL_AUTHENTICATOREMAILSTAGE.TIMEOUT;
    }

    @Override
    public Field<String> field11() {
        return AuthentikStagesAuthenticatorEmailAuthenticatoremailstage.AUTHENTIK_STAGES_AUTHENTICATOR_EMAIL_AUTHENTICATOREMAILSTAGE.FROM_ADDRESS;
    }

    @Override
    public Field<String> field12() {
        return AuthentikStagesAuthenticatorEmailAuthenticatoremailstage.AUTHENTIK_STAGES_AUTHENTICATOR_EMAIL_AUTHENTICATOREMAILSTAGE.TOKEN_EXPIRY;
    }

    @Override
    public Field<String> field13() {
        return AuthentikStagesAuthenticatorEmailAuthenticatoremailstage.AUTHENTIK_STAGES_AUTHENTICATOR_EMAIL_AUTHENTICATOREMAILSTAGE.SUBJECT;
    }

    @Override
    public Field<String> field14() {
        return AuthentikStagesAuthenticatorEmailAuthenticatoremailstage.AUTHENTIK_STAGES_AUTHENTICATOR_EMAIL_AUTHENTICATOREMAILSTAGE.TEMPLATE;
    }

    @Override
    public Field<UUID> field15() {
        return AuthentikStagesAuthenticatorEmailAuthenticatoremailstage.AUTHENTIK_STAGES_AUTHENTICATOR_EMAIL_AUTHENTICATOREMAILSTAGE.CONFIGURE_FLOW_ID;
    }

    @Override
    public UUID component1() {
        return getStagePtrId();
    }

    @Override
    public String component2() {
        return getFriendlyName();
    }

    @Override
    public Boolean component3() {
        return getUseGlobalSettings();
    }

    @Override
    public String component4() {
        return getHost();
    }

    @Override
    public Integer component5() {
        return getPort();
    }

    @Override
    public String component6() {
        return getUsername();
    }

    @Override
    public String component7() {
        return getPassword();
    }

    @Override
    public Boolean component8() {
        return getUseTls();
    }

    @Override
    public Boolean component9() {
        return getUseSsl();
    }

    @Override
    public Integer component10() {
        return getTimeout();
    }

    @Override
    public String component11() {
        return getFromAddress();
    }

    @Override
    public String component12() {
        return getTokenExpiry();
    }

    @Override
    public String component13() {
        return getSubject();
    }

    @Override
    public String component14() {
        return getTemplate();
    }

    @Override
    public UUID component15() {
        return getConfigureFlowId();
    }

    @Override
    public UUID value1() {
        return getStagePtrId();
    }

    @Override
    public String value2() {
        return getFriendlyName();
    }

    @Override
    public Boolean value3() {
        return getUseGlobalSettings();
    }

    @Override
    public String value4() {
        return getHost();
    }

    @Override
    public Integer value5() {
        return getPort();
    }

    @Override
    public String value6() {
        return getUsername();
    }

    @Override
    public String value7() {
        return getPassword();
    }

    @Override
    public Boolean value8() {
        return getUseTls();
    }

    @Override
    public Boolean value9() {
        return getUseSsl();
    }

    @Override
    public Integer value10() {
        return getTimeout();
    }

    @Override
    public String value11() {
        return getFromAddress();
    }

    @Override
    public String value12() {
        return getTokenExpiry();
    }

    @Override
    public String value13() {
        return getSubject();
    }

    @Override
    public String value14() {
        return getTemplate();
    }

    @Override
    public UUID value15() {
        return getConfigureFlowId();
    }

    @Override
    public AuthentikStagesAuthenticatorEmailAuthenticatoremailstageRecord value1(UUID value) {
        setStagePtrId(value);
        return this;
    }

    @Override
    public AuthentikStagesAuthenticatorEmailAuthenticatoremailstageRecord value2(String value) {
        setFriendlyName(value);
        return this;
    }

    @Override
    public AuthentikStagesAuthenticatorEmailAuthenticatoremailstageRecord value3(Boolean value) {
        setUseGlobalSettings(value);
        return this;
    }

    @Override
    public AuthentikStagesAuthenticatorEmailAuthenticatoremailstageRecord value4(String value) {
        setHost(value);
        return this;
    }

    @Override
    public AuthentikStagesAuthenticatorEmailAuthenticatoremailstageRecord value5(Integer value) {
        setPort(value);
        return this;
    }

    @Override
    public AuthentikStagesAuthenticatorEmailAuthenticatoremailstageRecord value6(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public AuthentikStagesAuthenticatorEmailAuthenticatoremailstageRecord value7(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public AuthentikStagesAuthenticatorEmailAuthenticatoremailstageRecord value8(Boolean value) {
        setUseTls(value);
        return this;
    }

    @Override
    public AuthentikStagesAuthenticatorEmailAuthenticatoremailstageRecord value9(Boolean value) {
        setUseSsl(value);
        return this;
    }

    @Override
    public AuthentikStagesAuthenticatorEmailAuthenticatoremailstageRecord value10(Integer value) {
        setTimeout(value);
        return this;
    }

    @Override
    public AuthentikStagesAuthenticatorEmailAuthenticatoremailstageRecord value11(String value) {
        setFromAddress(value);
        return this;
    }

    @Override
    public AuthentikStagesAuthenticatorEmailAuthenticatoremailstageRecord value12(String value) {
        setTokenExpiry(value);
        return this;
    }

    @Override
    public AuthentikStagesAuthenticatorEmailAuthenticatoremailstageRecord value13(String value) {
        setSubject(value);
        return this;
    }

    @Override
    public AuthentikStagesAuthenticatorEmailAuthenticatoremailstageRecord value14(String value) {
        setTemplate(value);
        return this;
    }

    @Override
    public AuthentikStagesAuthenticatorEmailAuthenticatoremailstageRecord value15(UUID value) {
        setConfigureFlowId(value);
        return this;
    }

    @Override
    public AuthentikStagesAuthenticatorEmailAuthenticatoremailstageRecord values(UUID value1, String value2, Boolean value3, String value4, Integer value5, String value6, String value7, Boolean value8, Boolean value9, Integer value10, String value11, String value12, String value13, String value14, UUID value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached
     * AuthentikStagesAuthenticatorEmailAuthenticatoremailstageRecord
     */
    public AuthentikStagesAuthenticatorEmailAuthenticatoremailstageRecord() {
        super(AuthentikStagesAuthenticatorEmailAuthenticatoremailstage.AUTHENTIK_STAGES_AUTHENTICATOR_EMAIL_AUTHENTICATOREMAILSTAGE);
    }

    /**
     * Create a detached, initialised
     * AuthentikStagesAuthenticatorEmailAuthenticatoremailstageRecord
     */
    public AuthentikStagesAuthenticatorEmailAuthenticatoremailstageRecord(UUID stagePtrId, String friendlyName, Boolean useGlobalSettings, String host, Integer port, String username, String password, Boolean useTls, Boolean useSsl, Integer timeout, String fromAddress, String tokenExpiry, String subject, String template, UUID configureFlowId) {
        super(AuthentikStagesAuthenticatorEmailAuthenticatoremailstage.AUTHENTIK_STAGES_AUTHENTICATOR_EMAIL_AUTHENTICATOREMAILSTAGE);

        setStagePtrId(stagePtrId);
        setFriendlyName(friendlyName);
        setUseGlobalSettings(useGlobalSettings);
        setHost(host);
        setPort(port);
        setUsername(username);
        setPassword(password);
        setUseTls(useTls);
        setUseSsl(useSsl);
        setTimeout(timeout);
        setFromAddress(fromAddress);
        setTokenExpiry(tokenExpiry);
        setSubject(subject);
        setTemplate(template);
        setConfigureFlowId(configureFlowId);
    }
}
