/*
 * This file is generated by jOOQ.
 */
package me.aa07.paradise.taskdaemon.database.authentik.tables.records;


import java.util.UUID;

import me.aa07.paradise.taskdaemon.database.authentik.tables.AuthentikSourcesLdapLdapsource;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthentikSourcesLdapLdapsourceRecord extends UpdatableRecordImpl<AuthentikSourcesLdapLdapsourceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>public.authentik_sources_ldap_ldapsource.source_ptr_id</code>.
     */
    public void setSourcePtrId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>public.authentik_sources_ldap_ldapsource.source_ptr_id</code>.
     */
    public UUID getSourcePtrId() {
        return (UUID) get(0);
    }

    /**
     * Setter for
     * <code>public.authentik_sources_ldap_ldapsource.server_uri</code>.
     */
    public void setServerUri(String value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>public.authentik_sources_ldap_ldapsource.server_uri</code>.
     */
    public String getServerUri() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.authentik_sources_ldap_ldapsource.bind_cn</code>.
     */
    public void setBindCn(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.authentik_sources_ldap_ldapsource.bind_cn</code>.
     */
    public String getBindCn() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>public.authentik_sources_ldap_ldapsource.bind_password</code>.
     */
    public void setBindPassword(String value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>public.authentik_sources_ldap_ldapsource.bind_password</code>.
     */
    public String getBindPassword() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>public.authentik_sources_ldap_ldapsource.start_tls</code>.
     */
    public void setStartTls(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>public.authentik_sources_ldap_ldapsource.start_tls</code>.
     */
    public Boolean getStartTls() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.authentik_sources_ldap_ldapsource.base_dn</code>.
     */
    public void setBaseDn(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.authentik_sources_ldap_ldapsource.base_dn</code>.
     */
    public String getBaseDn() {
        return (String) get(5);
    }

    /**
     * Setter for
     * <code>public.authentik_sources_ldap_ldapsource.additional_user_dn</code>.
     */
    public void setAdditionalUserDn(String value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>public.authentik_sources_ldap_ldapsource.additional_user_dn</code>.
     */
    public String getAdditionalUserDn() {
        return (String) get(6);
    }

    /**
     * Setter for
     * <code>public.authentik_sources_ldap_ldapsource.additional_group_dn</code>.
     */
    public void setAdditionalGroupDn(String value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>public.authentik_sources_ldap_ldapsource.additional_group_dn</code>.
     */
    public String getAdditionalGroupDn() {
        return (String) get(7);
    }

    /**
     * Setter for
     * <code>public.authentik_sources_ldap_ldapsource.user_object_filter</code>.
     */
    public void setUserObjectFilter(String value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>public.authentik_sources_ldap_ldapsource.user_object_filter</code>.
     */
    public String getUserObjectFilter() {
        return (String) get(8);
    }

    /**
     * Setter for
     * <code>public.authentik_sources_ldap_ldapsource.group_object_filter</code>.
     */
    public void setGroupObjectFilter(String value) {
        set(9, value);
    }

    /**
     * Getter for
     * <code>public.authentik_sources_ldap_ldapsource.group_object_filter</code>.
     */
    public String getGroupObjectFilter() {
        return (String) get(9);
    }

    /**
     * Setter for
     * <code>public.authentik_sources_ldap_ldapsource.object_uniqueness_field</code>.
     */
    public void setObjectUniquenessField(String value) {
        set(10, value);
    }

    /**
     * Getter for
     * <code>public.authentik_sources_ldap_ldapsource.object_uniqueness_field</code>.
     */
    public String getObjectUniquenessField() {
        return (String) get(10);
    }

    /**
     * Setter for
     * <code>public.authentik_sources_ldap_ldapsource.sync_groups</code>.
     */
    public void setSyncGroups(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for
     * <code>public.authentik_sources_ldap_ldapsource.sync_groups</code>.
     */
    public Boolean getSyncGroups() {
        return (Boolean) get(11);
    }

    /**
     * Setter for
     * <code>public.authentik_sources_ldap_ldapsource.sync_parent_group_id</code>.
     */
    public void setSyncParentGroupId(UUID value) {
        set(12, value);
    }

    /**
     * Getter for
     * <code>public.authentik_sources_ldap_ldapsource.sync_parent_group_id</code>.
     */
    public UUID getSyncParentGroupId() {
        return (UUID) get(12);
    }

    /**
     * Setter for
     * <code>public.authentik_sources_ldap_ldapsource.sync_users</code>.
     */
    public void setSyncUsers(Boolean value) {
        set(13, value);
    }

    /**
     * Getter for
     * <code>public.authentik_sources_ldap_ldapsource.sync_users</code>.
     */
    public Boolean getSyncUsers() {
        return (Boolean) get(13);
    }

    /**
     * Setter for
     * <code>public.authentik_sources_ldap_ldapsource.sync_users_password</code>.
     */
    public void setSyncUsersPassword(Boolean value) {
        set(14, value);
    }

    /**
     * Getter for
     * <code>public.authentik_sources_ldap_ldapsource.sync_users_password</code>.
     */
    public Boolean getSyncUsersPassword() {
        return (Boolean) get(14);
    }

    /**
     * Setter for
     * <code>public.authentik_sources_ldap_ldapsource.group_membership_field</code>.
     */
    public void setGroupMembershipField(String value) {
        set(15, value);
    }

    /**
     * Getter for
     * <code>public.authentik_sources_ldap_ldapsource.group_membership_field</code>.
     */
    public String getGroupMembershipField() {
        return (String) get(15);
    }

    /**
     * Setter for
     * <code>public.authentik_sources_ldap_ldapsource.peer_certificate_id</code>.
     */
    public void setPeerCertificateId(UUID value) {
        set(16, value);
    }

    /**
     * Getter for
     * <code>public.authentik_sources_ldap_ldapsource.peer_certificate_id</code>.
     */
    public UUID getPeerCertificateId() {
        return (UUID) get(16);
    }

    /**
     * Setter for
     * <code>public.authentik_sources_ldap_ldapsource.client_certificate_id</code>.
     */
    public void setClientCertificateId(UUID value) {
        set(17, value);
    }

    /**
     * Getter for
     * <code>public.authentik_sources_ldap_ldapsource.client_certificate_id</code>.
     */
    public UUID getClientCertificateId() {
        return (UUID) get(17);
    }

    /**
     * Setter for <code>public.authentik_sources_ldap_ldapsource.sni</code>.
     */
    public void setSni(Boolean value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.authentik_sources_ldap_ldapsource.sni</code>.
     */
    public Boolean getSni() {
        return (Boolean) get(18);
    }

    /**
     * Setter for
     * <code>public.authentik_sources_ldap_ldapsource.password_login_update_internal_password</code>.
     */
    public void setPasswordLoginUpdateInternalPassword(Boolean value) {
        set(19, value);
    }

    /**
     * Getter for
     * <code>public.authentik_sources_ldap_ldapsource.password_login_update_internal_password</code>.
     */
    public Boolean getPasswordLoginUpdateInternalPassword() {
        return (Boolean) get(19);
    }

    /**
     * Setter for
     * <code>public.authentik_sources_ldap_ldapsource.lookup_groups_from_user</code>.
     */
    public void setLookupGroupsFromUser(Boolean value) {
        set(20, value);
    }

    /**
     * Getter for
     * <code>public.authentik_sources_ldap_ldapsource.lookup_groups_from_user</code>.
     */
    public Boolean getLookupGroupsFromUser() {
        return (Boolean) get(20);
    }

    /**
     * Setter for
     * <code>public.authentik_sources_ldap_ldapsource.delete_not_found_objects</code>.
     */
    public void setDeleteNotFoundObjects(Boolean value) {
        set(21, value);
    }

    /**
     * Getter for
     * <code>public.authentik_sources_ldap_ldapsource.delete_not_found_objects</code>.
     */
    public Boolean getDeleteNotFoundObjects() {
        return (Boolean) get(21);
    }

    /**
     * Setter for
     * <code>public.authentik_sources_ldap_ldapsource.user_membership_attribute</code>.
     */
    public void setUserMembershipAttribute(String value) {
        set(22, value);
    }

    /**
     * Getter for
     * <code>public.authentik_sources_ldap_ldapsource.user_membership_attribute</code>.
     */
    public String getUserMembershipAttribute() {
        return (String) get(22);
    }

    /**
     * Setter for
     * <code>public.authentik_sources_ldap_ldapsource.sync_outgoing_trigger_mode</code>.
     */
    public void setSyncOutgoingTriggerMode(String value) {
        set(23, value);
    }

    /**
     * Getter for
     * <code>public.authentik_sources_ldap_ldapsource.sync_outgoing_trigger_mode</code>.
     */
    public String getSyncOutgoingTriggerMode() {
        return (String) get(23);
    }

    /**
     * Setter for
     * <code>public.authentik_sources_ldap_ldapsource.sync_group_hierarchy</code>.
     */
    public void setSyncGroupHierarchy(Boolean value) {
        set(24, value);
    }

    /**
     * Getter for
     * <code>public.authentik_sources_ldap_ldapsource.sync_group_hierarchy</code>.
     */
    public Boolean getSyncGroupHierarchy() {
        return (Boolean) get(24);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthentikSourcesLdapLdapsourceRecord
     */
    public AuthentikSourcesLdapLdapsourceRecord() {
        super(AuthentikSourcesLdapLdapsource.AUTHENTIK_SOURCES_LDAP_LDAPSOURCE);
    }

    /**
     * Create a detached, initialised AuthentikSourcesLdapLdapsourceRecord
     */
    public AuthentikSourcesLdapLdapsourceRecord(UUID sourcePtrId, String serverUri, String bindCn, String bindPassword, Boolean startTls, String baseDn, String additionalUserDn, String additionalGroupDn, String userObjectFilter, String groupObjectFilter, String objectUniquenessField, Boolean syncGroups, UUID syncParentGroupId, Boolean syncUsers, Boolean syncUsersPassword, String groupMembershipField, UUID peerCertificateId, UUID clientCertificateId, Boolean sni, Boolean passwordLoginUpdateInternalPassword, Boolean lookupGroupsFromUser, Boolean deleteNotFoundObjects, String userMembershipAttribute, String syncOutgoingTriggerMode, Boolean syncGroupHierarchy) {
        super(AuthentikSourcesLdapLdapsource.AUTHENTIK_SOURCES_LDAP_LDAPSOURCE);

        setSourcePtrId(sourcePtrId);
        setServerUri(serverUri);
        setBindCn(bindCn);
        setBindPassword(bindPassword);
        setStartTls(startTls);
        setBaseDn(baseDn);
        setAdditionalUserDn(additionalUserDn);
        setAdditionalGroupDn(additionalGroupDn);
        setUserObjectFilter(userObjectFilter);
        setGroupObjectFilter(groupObjectFilter);
        setObjectUniquenessField(objectUniquenessField);
        setSyncGroups(syncGroups);
        setSyncParentGroupId(syncParentGroupId);
        setSyncUsers(syncUsers);
        setSyncUsersPassword(syncUsersPassword);
        setGroupMembershipField(groupMembershipField);
        setPeerCertificateId(peerCertificateId);
        setClientCertificateId(clientCertificateId);
        setSni(sni);
        setPasswordLoginUpdateInternalPassword(passwordLoginUpdateInternalPassword);
        setLookupGroupsFromUser(lookupGroupsFromUser);
        setDeleteNotFoundObjects(deleteNotFoundObjects);
        setUserMembershipAttribute(userMembershipAttribute);
        setSyncOutgoingTriggerMode(syncOutgoingTriggerMode);
        setSyncGroupHierarchy(syncGroupHierarchy);
    }
}
