/*
 * This file is generated by jOOQ.
 */
package me.aa07.paradise.taskdaemon.database.authentik.tables.records;


import java.util.UUID;

import me.aa07.paradise.taskdaemon.database.authentik.tables.AuthentikTasksTaskdependency;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthentikTasksTaskdependencyRecord extends UpdatableRecordImpl<AuthentikTasksTaskdependencyRecord> implements Record2<UUID, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>public.authentik_tasks_taskdependency.dependency_id</code>.
     */
    public void setDependencyId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>public.authentik_tasks_taskdependency.dependency_id</code>.
     */
    public UUID getDependencyId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.authentik_tasks_taskdependency.task_id</code>.
     */
    public void setTaskId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.authentik_tasks_taskdependency.task_id</code>.
     */
    public UUID getTaskId() {
        return (UUID) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, UUID> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<UUID, UUID> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return AuthentikTasksTaskdependency.AUTHENTIK_TASKS_TASKDEPENDENCY.DEPENDENCY_ID;
    }

    @Override
    public Field<UUID> field2() {
        return AuthentikTasksTaskdependency.AUTHENTIK_TASKS_TASKDEPENDENCY.TASK_ID;
    }

    @Override
    public UUID component1() {
        return getDependencyId();
    }

    @Override
    public UUID component2() {
        return getTaskId();
    }

    @Override
    public UUID value1() {
        return getDependencyId();
    }

    @Override
    public UUID value2() {
        return getTaskId();
    }

    @Override
    public AuthentikTasksTaskdependencyRecord value1(UUID value) {
        setDependencyId(value);
        return this;
    }

    @Override
    public AuthentikTasksTaskdependencyRecord value2(UUID value) {
        setTaskId(value);
        return this;
    }

    @Override
    public AuthentikTasksTaskdependencyRecord values(UUID value1, UUID value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthentikTasksTaskdependencyRecord
     */
    public AuthentikTasksTaskdependencyRecord() {
        super(AuthentikTasksTaskdependency.AUTHENTIK_TASKS_TASKDEPENDENCY);
    }

    /**
     * Create a detached, initialised AuthentikTasksTaskdependencyRecord
     */
    public AuthentikTasksTaskdependencyRecord(UUID dependencyId, UUID taskId) {
        super(AuthentikTasksTaskdependency.AUTHENTIK_TASKS_TASKDEPENDENCY);

        setDependencyId(dependencyId);
        setTaskId(taskId);
    }
}
