/*
 * This file is generated by jOOQ.
 */
package me.aa07.paradise.taskdaemon.database.authentik.tables.records;


import java.time.OffsetDateTime;

import me.aa07.paradise.taskdaemon.database.authentik.tables.AuthentikProvidersOauth2Devicetoken;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthentikProvidersOauth2DevicetokenRecord extends UpdatableRecordImpl<AuthentikProvidersOauth2DevicetokenRecord> implements Record10<Integer, OffsetDateTime, Boolean, String, String, String, Integer, Integer, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.authentik_providers_oauth2_devicetoken.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.authentik_providers_oauth2_devicetoken.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>public.authentik_providers_oauth2_devicetoken.expires</code>.
     */
    public void setExpires(OffsetDateTime value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>public.authentik_providers_oauth2_devicetoken.expires</code>.
     */
    public OffsetDateTime getExpires() {
        return (OffsetDateTime) get(1);
    }

    /**
     * Setter for
     * <code>public.authentik_providers_oauth2_devicetoken.expiring</code>.
     */
    public void setExpiring(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>public.authentik_providers_oauth2_devicetoken.expiring</code>.
     */
    public Boolean getExpiring() {
        return (Boolean) get(2);
    }

    /**
     * Setter for
     * <code>public.authentik_providers_oauth2_devicetoken.device_code</code>.
     */
    public void setDeviceCode(String value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>public.authentik_providers_oauth2_devicetoken.device_code</code>.
     */
    public String getDeviceCode() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>public.authentik_providers_oauth2_devicetoken.user_code</code>.
     */
    public void setUserCode(String value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>public.authentik_providers_oauth2_devicetoken.user_code</code>.
     */
    public String getUserCode() {
        return (String) get(4);
    }

    /**
     * Setter for
     * <code>public.authentik_providers_oauth2_devicetoken._scope</code>.
     */
    public void set_Scope(String value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>public.authentik_providers_oauth2_devicetoken._scope</code>.
     */
    public String get_Scope() {
        return (String) get(5);
    }

    /**
     * Setter for
     * <code>public.authentik_providers_oauth2_devicetoken.provider_id</code>.
     */
    public void setProviderId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>public.authentik_providers_oauth2_devicetoken.provider_id</code>.
     */
    public Integer getProviderId() {
        return (Integer) get(6);
    }

    /**
     * Setter for
     * <code>public.authentik_providers_oauth2_devicetoken.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>public.authentik_providers_oauth2_devicetoken.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(7);
    }

    /**
     * Setter for
     * <code>public.authentik_providers_oauth2_devicetoken.session_id</code>.
     */
    public void setSessionId(String value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>public.authentik_providers_oauth2_devicetoken.session_id</code>.
     */
    public String getSessionId() {
        return (String) get(8);
    }

    /**
     * Setter for
     * <code>public.authentik_providers_oauth2_devicetoken.dpop_jkt</code>.
     */
    public void setDpopJkt(String value) {
        set(9, value);
    }

    /**
     * Getter for
     * <code>public.authentik_providers_oauth2_devicetoken.dpop_jkt</code>.
     */
    public String getDpopJkt() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, OffsetDateTime, Boolean, String, String, String, Integer, Integer, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, OffsetDateTime, Boolean, String, String, String, Integer, Integer, String, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return AuthentikProvidersOauth2Devicetoken.AUTHENTIK_PROVIDERS_OAUTH2_DEVICETOKEN.ID;
    }

    @Override
    public Field<OffsetDateTime> field2() {
        return AuthentikProvidersOauth2Devicetoken.AUTHENTIK_PROVIDERS_OAUTH2_DEVICETOKEN.EXPIRES;
    }

    @Override
    public Field<Boolean> field3() {
        return AuthentikProvidersOauth2Devicetoken.AUTHENTIK_PROVIDERS_OAUTH2_DEVICETOKEN.EXPIRING;
    }

    @Override
    public Field<String> field4() {
        return AuthentikProvidersOauth2Devicetoken.AUTHENTIK_PROVIDERS_OAUTH2_DEVICETOKEN.DEVICE_CODE;
    }

    @Override
    public Field<String> field5() {
        return AuthentikProvidersOauth2Devicetoken.AUTHENTIK_PROVIDERS_OAUTH2_DEVICETOKEN.USER_CODE;
    }

    @Override
    public Field<String> field6() {
        return AuthentikProvidersOauth2Devicetoken.AUTHENTIK_PROVIDERS_OAUTH2_DEVICETOKEN._SCOPE;
    }

    @Override
    public Field<Integer> field7() {
        return AuthentikProvidersOauth2Devicetoken.AUTHENTIK_PROVIDERS_OAUTH2_DEVICETOKEN.PROVIDER_ID;
    }

    @Override
    public Field<Integer> field8() {
        return AuthentikProvidersOauth2Devicetoken.AUTHENTIK_PROVIDERS_OAUTH2_DEVICETOKEN.USER_ID;
    }

    @Override
    public Field<String> field9() {
        return AuthentikProvidersOauth2Devicetoken.AUTHENTIK_PROVIDERS_OAUTH2_DEVICETOKEN.SESSION_ID;
    }

    @Override
    public Field<String> field10() {
        return AuthentikProvidersOauth2Devicetoken.AUTHENTIK_PROVIDERS_OAUTH2_DEVICETOKEN.DPOP_JKT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public OffsetDateTime component2() {
        return getExpires();
    }

    @Override
    public Boolean component3() {
        return getExpiring();
    }

    @Override
    public String component4() {
        return getDeviceCode();
    }

    @Override
    public String component5() {
        return getUserCode();
    }

    @Override
    public String component6() {
        return get_Scope();
    }

    @Override
    public Integer component7() {
        return getProviderId();
    }

    @Override
    public Integer component8() {
        return getUserId();
    }

    @Override
    public String component9() {
        return getSessionId();
    }

    @Override
    public String component10() {
        return getDpopJkt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public OffsetDateTime value2() {
        return getExpires();
    }

    @Override
    public Boolean value3() {
        return getExpiring();
    }

    @Override
    public String value4() {
        return getDeviceCode();
    }

    @Override
    public String value5() {
        return getUserCode();
    }

    @Override
    public String value6() {
        return get_Scope();
    }

    @Override
    public Integer value7() {
        return getProviderId();
    }

    @Override
    public Integer value8() {
        return getUserId();
    }

    @Override
    public String value9() {
        return getSessionId();
    }

    @Override
    public String value10() {
        return getDpopJkt();
    }

    @Override
    public AuthentikProvidersOauth2DevicetokenRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public AuthentikProvidersOauth2DevicetokenRecord value2(OffsetDateTime value) {
        setExpires(value);
        return this;
    }

    @Override
    public AuthentikProvidersOauth2DevicetokenRecord value3(Boolean value) {
        setExpiring(value);
        return this;
    }

    @Override
    public AuthentikProvidersOauth2DevicetokenRecord value4(String value) {
        setDeviceCode(value);
        return this;
    }

    @Override
    public AuthentikProvidersOauth2DevicetokenRecord value5(String value) {
        setUserCode(value);
        return this;
    }

    @Override
    public AuthentikProvidersOauth2DevicetokenRecord value6(String value) {
        set_Scope(value);
        return this;
    }

    @Override
    public AuthentikProvidersOauth2DevicetokenRecord value7(Integer value) {
        setProviderId(value);
        return this;
    }

    @Override
    public AuthentikProvidersOauth2DevicetokenRecord value8(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public AuthentikProvidersOauth2DevicetokenRecord value9(String value) {
        setSessionId(value);
        return this;
    }

    @Override
    public AuthentikProvidersOauth2DevicetokenRecord value10(String value) {
        setDpopJkt(value);
        return this;
    }

    @Override
    public AuthentikProvidersOauth2DevicetokenRecord values(Integer value1, OffsetDateTime value2, Boolean value3, String value4, String value5, String value6, Integer value7, Integer value8, String value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthentikProvidersOauth2DevicetokenRecord
     */
    public AuthentikProvidersOauth2DevicetokenRecord() {
        super(AuthentikProvidersOauth2Devicetoken.AUTHENTIK_PROVIDERS_OAUTH2_DEVICETOKEN);
    }

    /**
     * Create a detached, initialised AuthentikProvidersOauth2DevicetokenRecord
     */
    public AuthentikProvidersOauth2DevicetokenRecord(Integer id, OffsetDateTime expires, Boolean expiring, String deviceCode, String userCode, String _Scope, Integer providerId, Integer userId, String sessionId, String dpopJkt) {
        super(AuthentikProvidersOauth2Devicetoken.AUTHENTIK_PROVIDERS_OAUTH2_DEVICETOKEN);

        setId(id);
        setExpires(expires);
        setExpiring(expiring);
        setDeviceCode(deviceCode);
        setUserCode(userCode);
        set_Scope(_Scope);
        setProviderId(providerId);
        setUserId(userId);
        setSessionId(sessionId);
        setDpopJkt(dpopJkt);
    }
}
