/*
 * This file is generated by jOOQ.
 */
package me.aa07.paradise.taskdaemon.database.authentik.tables.records;


import java.util.UUID;

import me.aa07.paradise.taskdaemon.database.authentik.tables.AuthentikProvidersScimScimproviderPropertyMappingsGroup;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthentikProvidersScimScimproviderPropertyMappingsGroupRecord extends UpdatableRecordImpl<AuthentikProvidersScimScimproviderPropertyMappingsGroupRecord> implements Record3<Integer, Integer, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>public.authentik_providers_scim_scimprovider_property_mappings_group.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>public.authentik_providers_scim_scimprovider_property_mappings_group.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>public.authentik_providers_scim_scimprovider_property_mappings_group.scimprovider_id</code>.
     */
    public void setScimproviderId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>public.authentik_providers_scim_scimprovider_property_mappings_group.scimprovider_id</code>.
     */
    public Integer getScimproviderId() {
        return (Integer) get(1);
    }

    /**
     * Setter for
     * <code>public.authentik_providers_scim_scimprovider_property_mappings_group.propertymapping_id</code>.
     */
    public void setPropertymappingId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>public.authentik_providers_scim_scimprovider_property_mappings_group.propertymapping_id</code>.
     */
    public UUID getPropertymappingId() {
        return (UUID) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, UUID> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, UUID> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return AuthentikProvidersScimScimproviderPropertyMappingsGroup.AUTHENTIK_PROVIDERS_SCIM_SCIMPROVIDER_PROPERTY_MAPPINGS_GROUP.ID;
    }

    @Override
    public Field<Integer> field2() {
        return AuthentikProvidersScimScimproviderPropertyMappingsGroup.AUTHENTIK_PROVIDERS_SCIM_SCIMPROVIDER_PROPERTY_MAPPINGS_GROUP.SCIMPROVIDER_ID;
    }

    @Override
    public Field<UUID> field3() {
        return AuthentikProvidersScimScimproviderPropertyMappingsGroup.AUTHENTIK_PROVIDERS_SCIM_SCIMPROVIDER_PROPERTY_MAPPINGS_GROUP.PROPERTYMAPPING_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getScimproviderId();
    }

    @Override
    public UUID component3() {
        return getPropertymappingId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getScimproviderId();
    }

    @Override
    public UUID value3() {
        return getPropertymappingId();
    }

    @Override
    public AuthentikProvidersScimScimproviderPropertyMappingsGroupRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public AuthentikProvidersScimScimproviderPropertyMappingsGroupRecord value2(Integer value) {
        setScimproviderId(value);
        return this;
    }

    @Override
    public AuthentikProvidersScimScimproviderPropertyMappingsGroupRecord value3(UUID value) {
        setPropertymappingId(value);
        return this;
    }

    @Override
    public AuthentikProvidersScimScimproviderPropertyMappingsGroupRecord values(Integer value1, Integer value2, UUID value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached
     * AuthentikProvidersScimScimproviderPropertyMappingsGroupRecord
     */
    public AuthentikProvidersScimScimproviderPropertyMappingsGroupRecord() {
        super(AuthentikProvidersScimScimproviderPropertyMappingsGroup.AUTHENTIK_PROVIDERS_SCIM_SCIMPROVIDER_PROPERTY_MAPPINGS_GROUP);
    }

    /**
     * Create a detached, initialised
     * AuthentikProvidersScimScimproviderPropertyMappingsGroupRecord
     */
    public AuthentikProvidersScimScimproviderPropertyMappingsGroupRecord(Integer id, Integer scimproviderId, UUID propertymappingId) {
        super(AuthentikProvidersScimScimproviderPropertyMappingsGroup.AUTHENTIK_PROVIDERS_SCIM_SCIMPROVIDER_PROPERTY_MAPPINGS_GROUP);

        setId(id);
        setScimproviderId(scimproviderId);
        setPropertymappingId(propertymappingId);
    }
}
