/*
 * This file is generated by jOOQ.
 */
package me.aa07.paradise.taskdaemon.database.authentik.tables.records;


import java.util.UUID;

import me.aa07.paradise.taskdaemon.database.authentik.tables.AuthentikEndpointsDeviceuserbinding;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthentikEndpointsDeviceuserbindingRecord extends UpdatableRecordImpl<AuthentikEndpointsDeviceuserbindingRecord> implements Record3<UUID, Boolean, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>public.authentik_endpoints_deviceuserbinding.policybinding_ptr_id</code>.
     */
    public void setPolicybindingPtrId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>public.authentik_endpoints_deviceuserbinding.policybinding_ptr_id</code>.
     */
    public UUID getPolicybindingPtrId() {
        return (UUID) get(0);
    }

    /**
     * Setter for
     * <code>public.authentik_endpoints_deviceuserbinding.is_primary</code>.
     */
    public void setIsPrimary(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>public.authentik_endpoints_deviceuserbinding.is_primary</code>.
     */
    public Boolean getIsPrimary() {
        return (Boolean) get(1);
    }

    /**
     * Setter for
     * <code>public.authentik_endpoints_deviceuserbinding.connector_id</code>.
     */
    public void setConnectorId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>public.authentik_endpoints_deviceuserbinding.connector_id</code>.
     */
    public UUID getConnectorId() {
        return (UUID) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, Boolean, UUID> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<UUID, Boolean, UUID> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return AuthentikEndpointsDeviceuserbinding.AUTHENTIK_ENDPOINTS_DEVICEUSERBINDING.POLICYBINDING_PTR_ID;
    }

    @Override
    public Field<Boolean> field2() {
        return AuthentikEndpointsDeviceuserbinding.AUTHENTIK_ENDPOINTS_DEVICEUSERBINDING.IS_PRIMARY;
    }

    @Override
    public Field<UUID> field3() {
        return AuthentikEndpointsDeviceuserbinding.AUTHENTIK_ENDPOINTS_DEVICEUSERBINDING.CONNECTOR_ID;
    }

    @Override
    public UUID component1() {
        return getPolicybindingPtrId();
    }

    @Override
    public Boolean component2() {
        return getIsPrimary();
    }

    @Override
    public UUID component3() {
        return getConnectorId();
    }

    @Override
    public UUID value1() {
        return getPolicybindingPtrId();
    }

    @Override
    public Boolean value2() {
        return getIsPrimary();
    }

    @Override
    public UUID value3() {
        return getConnectorId();
    }

    @Override
    public AuthentikEndpointsDeviceuserbindingRecord value1(UUID value) {
        setPolicybindingPtrId(value);
        return this;
    }

    @Override
    public AuthentikEndpointsDeviceuserbindingRecord value2(Boolean value) {
        setIsPrimary(value);
        return this;
    }

    @Override
    public AuthentikEndpointsDeviceuserbindingRecord value3(UUID value) {
        setConnectorId(value);
        return this;
    }

    @Override
    public AuthentikEndpointsDeviceuserbindingRecord values(UUID value1, Boolean value2, UUID value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthentikEndpointsDeviceuserbindingRecord
     */
    public AuthentikEndpointsDeviceuserbindingRecord() {
        super(AuthentikEndpointsDeviceuserbinding.AUTHENTIK_ENDPOINTS_DEVICEUSERBINDING);
    }

    /**
     * Create a detached, initialised AuthentikEndpointsDeviceuserbindingRecord
     */
    public AuthentikEndpointsDeviceuserbindingRecord(UUID policybindingPtrId, Boolean isPrimary, UUID connectorId) {
        super(AuthentikEndpointsDeviceuserbinding.AUTHENTIK_ENDPOINTS_DEVICEUSERBINDING);

        setPolicybindingPtrId(policybindingPtrId);
        setIsPrimary(isPrimary);
        setConnectorId(connectorId);
    }
}
