/*
 * This file is generated by jOOQ.
 */
package me.aa07.paradise.taskdaemon.database.authentik.tables.records;


import java.util.UUID;

import me.aa07.paradise.taskdaemon.database.authentik.tables.AuthentikPoliciesEventMatcherEventmatcherpolicy;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthentikPoliciesEventMatcherEventmatcherpolicyRecord extends UpdatableRecordImpl<AuthentikPoliciesEventMatcherEventmatcherpolicyRecord> implements Record6<UUID, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>public.authentik_policies_event_matcher_eventmatcherpolicy.policy_ptr_id</code>.
     */
    public void setPolicyPtrId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>public.authentik_policies_event_matcher_eventmatcherpolicy.policy_ptr_id</code>.
     */
    public UUID getPolicyPtrId() {
        return (UUID) get(0);
    }

    /**
     * Setter for
     * <code>public.authentik_policies_event_matcher_eventmatcherpolicy.action</code>.
     */
    public void setAction(String value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>public.authentik_policies_event_matcher_eventmatcherpolicy.action</code>.
     */
    public String getAction() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>public.authentik_policies_event_matcher_eventmatcherpolicy.client_ip</code>.
     */
    public void setClientIp(String value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>public.authentik_policies_event_matcher_eventmatcherpolicy.client_ip</code>.
     */
    public String getClientIp() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>public.authentik_policies_event_matcher_eventmatcherpolicy.app</code>.
     */
    public void setApp(String value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>public.authentik_policies_event_matcher_eventmatcherpolicy.app</code>.
     */
    public String getApp() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>public.authentik_policies_event_matcher_eventmatcherpolicy.model</code>.
     */
    public void setModel(String value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>public.authentik_policies_event_matcher_eventmatcherpolicy.model</code>.
     */
    public String getModel() {
        return (String) get(4);
    }

    /**
     * Setter for
     * <code>public.authentik_policies_event_matcher_eventmatcherpolicy.query</code>.
     */
    public void setQuery(String value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>public.authentik_policies_event_matcher_eventmatcherpolicy.query</code>.
     */
    public String getQuery() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<UUID, String, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return AuthentikPoliciesEventMatcherEventmatcherpolicy.AUTHENTIK_POLICIES_EVENT_MATCHER_EVENTMATCHERPOLICY.POLICY_PTR_ID;
    }

    @Override
    public Field<String> field2() {
        return AuthentikPoliciesEventMatcherEventmatcherpolicy.AUTHENTIK_POLICIES_EVENT_MATCHER_EVENTMATCHERPOLICY.ACTION;
    }

    @Override
    public Field<String> field3() {
        return AuthentikPoliciesEventMatcherEventmatcherpolicy.AUTHENTIK_POLICIES_EVENT_MATCHER_EVENTMATCHERPOLICY.CLIENT_IP;
    }

    @Override
    public Field<String> field4() {
        return AuthentikPoliciesEventMatcherEventmatcherpolicy.AUTHENTIK_POLICIES_EVENT_MATCHER_EVENTMATCHERPOLICY.APP;
    }

    @Override
    public Field<String> field5() {
        return AuthentikPoliciesEventMatcherEventmatcherpolicy.AUTHENTIK_POLICIES_EVENT_MATCHER_EVENTMATCHERPOLICY.MODEL;
    }

    @Override
    public Field<String> field6() {
        return AuthentikPoliciesEventMatcherEventmatcherpolicy.AUTHENTIK_POLICIES_EVENT_MATCHER_EVENTMATCHERPOLICY.QUERY;
    }

    @Override
    public UUID component1() {
        return getPolicyPtrId();
    }

    @Override
    public String component2() {
        return getAction();
    }

    @Override
    public String component3() {
        return getClientIp();
    }

    @Override
    public String component4() {
        return getApp();
    }

    @Override
    public String component5() {
        return getModel();
    }

    @Override
    public String component6() {
        return getQuery();
    }

    @Override
    public UUID value1() {
        return getPolicyPtrId();
    }

    @Override
    public String value2() {
        return getAction();
    }

    @Override
    public String value3() {
        return getClientIp();
    }

    @Override
    public String value4() {
        return getApp();
    }

    @Override
    public String value5() {
        return getModel();
    }

    @Override
    public String value6() {
        return getQuery();
    }

    @Override
    public AuthentikPoliciesEventMatcherEventmatcherpolicyRecord value1(UUID value) {
        setPolicyPtrId(value);
        return this;
    }

    @Override
    public AuthentikPoliciesEventMatcherEventmatcherpolicyRecord value2(String value) {
        setAction(value);
        return this;
    }

    @Override
    public AuthentikPoliciesEventMatcherEventmatcherpolicyRecord value3(String value) {
        setClientIp(value);
        return this;
    }

    @Override
    public AuthentikPoliciesEventMatcherEventmatcherpolicyRecord value4(String value) {
        setApp(value);
        return this;
    }

    @Override
    public AuthentikPoliciesEventMatcherEventmatcherpolicyRecord value5(String value) {
        setModel(value);
        return this;
    }

    @Override
    public AuthentikPoliciesEventMatcherEventmatcherpolicyRecord value6(String value) {
        setQuery(value);
        return this;
    }

    @Override
    public AuthentikPoliciesEventMatcherEventmatcherpolicyRecord values(UUID value1, String value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthentikPoliciesEventMatcherEventmatcherpolicyRecord
     */
    public AuthentikPoliciesEventMatcherEventmatcherpolicyRecord() {
        super(AuthentikPoliciesEventMatcherEventmatcherpolicy.AUTHENTIK_POLICIES_EVENT_MATCHER_EVENTMATCHERPOLICY);
    }

    /**
     * Create a detached, initialised
     * AuthentikPoliciesEventMatcherEventmatcherpolicyRecord
     */
    public AuthentikPoliciesEventMatcherEventmatcherpolicyRecord(UUID policyPtrId, String action, String clientIp, String app, String model, String query) {
        super(AuthentikPoliciesEventMatcherEventmatcherpolicy.AUTHENTIK_POLICIES_EVENT_MATCHER_EVENTMATCHERPOLICY);

        setPolicyPtrId(policyPtrId);
        setAction(action);
        setClientIp(clientIp);
        setApp(app);
        setModel(model);
        setQuery(query);
    }
}
