/*
 * This file is generated by jOOQ.
 */
package me.aa07.paradise.taskdaemon.database.authentik.tables.records;


import java.util.UUID;

import me.aa07.paradise.taskdaemon.database.authentik.tables.AuthentikPoliciesDummyDummypolicy;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthentikPoliciesDummyDummypolicyRecord extends UpdatableRecordImpl<AuthentikPoliciesDummyDummypolicyRecord> implements Record4<UUID, Boolean, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>public.authentik_policies_dummy_dummypolicy.policy_ptr_id</code>.
     */
    public void setPolicyPtrId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>public.authentik_policies_dummy_dummypolicy.policy_ptr_id</code>.
     */
    public UUID getPolicyPtrId() {
        return (UUID) get(0);
    }

    /**
     * Setter for
     * <code>public.authentik_policies_dummy_dummypolicy.result</code>.
     */
    public void setResult(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>public.authentik_policies_dummy_dummypolicy.result</code>.
     */
    public Boolean getResult() {
        return (Boolean) get(1);
    }

    /**
     * Setter for
     * <code>public.authentik_policies_dummy_dummypolicy.wait_min</code>.
     */
    public void setWaitMin(Integer value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>public.authentik_policies_dummy_dummypolicy.wait_min</code>.
     */
    public Integer getWaitMin() {
        return (Integer) get(2);
    }

    /**
     * Setter for
     * <code>public.authentik_policies_dummy_dummypolicy.wait_max</code>.
     */
    public void setWaitMax(Integer value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>public.authentik_policies_dummy_dummypolicy.wait_max</code>.
     */
    public Integer getWaitMax() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<UUID, Boolean, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<UUID, Boolean, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return AuthentikPoliciesDummyDummypolicy.AUTHENTIK_POLICIES_DUMMY_DUMMYPOLICY.POLICY_PTR_ID;
    }

    @Override
    public Field<Boolean> field2() {
        return AuthentikPoliciesDummyDummypolicy.AUTHENTIK_POLICIES_DUMMY_DUMMYPOLICY.RESULT;
    }

    @Override
    public Field<Integer> field3() {
        return AuthentikPoliciesDummyDummypolicy.AUTHENTIK_POLICIES_DUMMY_DUMMYPOLICY.WAIT_MIN;
    }

    @Override
    public Field<Integer> field4() {
        return AuthentikPoliciesDummyDummypolicy.AUTHENTIK_POLICIES_DUMMY_DUMMYPOLICY.WAIT_MAX;
    }

    @Override
    public UUID component1() {
        return getPolicyPtrId();
    }

    @Override
    public Boolean component2() {
        return getResult();
    }

    @Override
    public Integer component3() {
        return getWaitMin();
    }

    @Override
    public Integer component4() {
        return getWaitMax();
    }

    @Override
    public UUID value1() {
        return getPolicyPtrId();
    }

    @Override
    public Boolean value2() {
        return getResult();
    }

    @Override
    public Integer value3() {
        return getWaitMin();
    }

    @Override
    public Integer value4() {
        return getWaitMax();
    }

    @Override
    public AuthentikPoliciesDummyDummypolicyRecord value1(UUID value) {
        setPolicyPtrId(value);
        return this;
    }

    @Override
    public AuthentikPoliciesDummyDummypolicyRecord value2(Boolean value) {
        setResult(value);
        return this;
    }

    @Override
    public AuthentikPoliciesDummyDummypolicyRecord value3(Integer value) {
        setWaitMin(value);
        return this;
    }

    @Override
    public AuthentikPoliciesDummyDummypolicyRecord value4(Integer value) {
        setWaitMax(value);
        return this;
    }

    @Override
    public AuthentikPoliciesDummyDummypolicyRecord values(UUID value1, Boolean value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthentikPoliciesDummyDummypolicyRecord
     */
    public AuthentikPoliciesDummyDummypolicyRecord() {
        super(AuthentikPoliciesDummyDummypolicy.AUTHENTIK_POLICIES_DUMMY_DUMMYPOLICY);
    }

    /**
     * Create a detached, initialised AuthentikPoliciesDummyDummypolicyRecord
     */
    public AuthentikPoliciesDummyDummypolicyRecord(UUID policyPtrId, Boolean result, Integer waitMin, Integer waitMax) {
        super(AuthentikPoliciesDummyDummypolicy.AUTHENTIK_POLICIES_DUMMY_DUMMYPOLICY);

        setPolicyPtrId(policyPtrId);
        setResult(result);
        setWaitMin(waitMin);
        setWaitMax(waitMax);
    }
}
