/*
 * This file is generated by jOOQ.
 */
package me.aa07.paradise.taskdaemon.database.authentik.tables.records;


import java.util.UUID;

import me.aa07.paradise.taskdaemon.database.authentik.tables.AuthentikEventsNotificationtransport;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthentikEventsNotificationtransportRecord extends UpdatableRecordImpl<AuthentikEventsNotificationtransportRecord> implements Record10<UUID, String, String, String, Boolean, UUID, UUID, String, String, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>public.authentik_events_notificationtransport.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>public.authentik_events_notificationtransport.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for
     * <code>public.authentik_events_notificationtransport.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>public.authentik_events_notificationtransport.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>public.authentik_events_notificationtransport.mode</code>.
     */
    public void setMode(String value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>public.authentik_events_notificationtransport.mode</code>.
     */
    public String getMode() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>public.authentik_events_notificationtransport.webhook_url</code>.
     */
    public void setWebhookUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>public.authentik_events_notificationtransport.webhook_url</code>.
     */
    public String getWebhookUrl() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>public.authentik_events_notificationtransport.send_once</code>.
     */
    public void setSendOnce(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>public.authentik_events_notificationtransport.send_once</code>.
     */
    public Boolean getSendOnce() {
        return (Boolean) get(4);
    }

    /**
     * Setter for
     * <code>public.authentik_events_notificationtransport.webhook_mapping_body_id</code>.
     */
    public void setWebhookMappingBodyId(UUID value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>public.authentik_events_notificationtransport.webhook_mapping_body_id</code>.
     */
    public UUID getWebhookMappingBodyId() {
        return (UUID) get(5);
    }

    /**
     * Setter for
     * <code>public.authentik_events_notificationtransport.webhook_mapping_headers_id</code>.
     */
    public void setWebhookMappingHeadersId(UUID value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>public.authentik_events_notificationtransport.webhook_mapping_headers_id</code>.
     */
    public UUID getWebhookMappingHeadersId() {
        return (UUID) get(6);
    }

    /**
     * Setter for
     * <code>public.authentik_events_notificationtransport.email_subject_prefix</code>.
     */
    public void setEmailSubjectPrefix(String value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>public.authentik_events_notificationtransport.email_subject_prefix</code>.
     */
    public String getEmailSubjectPrefix() {
        return (String) get(7);
    }

    /**
     * Setter for
     * <code>public.authentik_events_notificationtransport.email_template</code>.
     */
    public void setEmailTemplate(String value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>public.authentik_events_notificationtransport.email_template</code>.
     */
    public String getEmailTemplate() {
        return (String) get(8);
    }

    /**
     * Setter for
     * <code>public.authentik_events_notificationtransport.webhook_ca_id</code>.
     */
    public void setWebhookCaId(UUID value) {
        set(9, value);
    }

    /**
     * Getter for
     * <code>public.authentik_events_notificationtransport.webhook_ca_id</code>.
     */
    public UUID getWebhookCaId() {
        return (UUID) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<UUID, String, String, String, Boolean, UUID, UUID, String, String, UUID> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<UUID, String, String, String, Boolean, UUID, UUID, String, String, UUID> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return AuthentikEventsNotificationtransport.AUTHENTIK_EVENTS_NOTIFICATIONTRANSPORT.UUID;
    }

    @Override
    public Field<String> field2() {
        return AuthentikEventsNotificationtransport.AUTHENTIK_EVENTS_NOTIFICATIONTRANSPORT.NAME;
    }

    @Override
    public Field<String> field3() {
        return AuthentikEventsNotificationtransport.AUTHENTIK_EVENTS_NOTIFICATIONTRANSPORT.MODE;
    }

    @Override
    public Field<String> field4() {
        return AuthentikEventsNotificationtransport.AUTHENTIK_EVENTS_NOTIFICATIONTRANSPORT.WEBHOOK_URL;
    }

    @Override
    public Field<Boolean> field5() {
        return AuthentikEventsNotificationtransport.AUTHENTIK_EVENTS_NOTIFICATIONTRANSPORT.SEND_ONCE;
    }

    @Override
    public Field<UUID> field6() {
        return AuthentikEventsNotificationtransport.AUTHENTIK_EVENTS_NOTIFICATIONTRANSPORT.WEBHOOK_MAPPING_BODY_ID;
    }

    @Override
    public Field<UUID> field7() {
        return AuthentikEventsNotificationtransport.AUTHENTIK_EVENTS_NOTIFICATIONTRANSPORT.WEBHOOK_MAPPING_HEADERS_ID;
    }

    @Override
    public Field<String> field8() {
        return AuthentikEventsNotificationtransport.AUTHENTIK_EVENTS_NOTIFICATIONTRANSPORT.EMAIL_SUBJECT_PREFIX;
    }

    @Override
    public Field<String> field9() {
        return AuthentikEventsNotificationtransport.AUTHENTIK_EVENTS_NOTIFICATIONTRANSPORT.EMAIL_TEMPLATE;
    }

    @Override
    public Field<UUID> field10() {
        return AuthentikEventsNotificationtransport.AUTHENTIK_EVENTS_NOTIFICATIONTRANSPORT.WEBHOOK_CA_ID;
    }

    @Override
    public UUID component1() {
        return getUuid();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getMode();
    }

    @Override
    public String component4() {
        return getWebhookUrl();
    }

    @Override
    public Boolean component5() {
        return getSendOnce();
    }

    @Override
    public UUID component6() {
        return getWebhookMappingBodyId();
    }

    @Override
    public UUID component7() {
        return getWebhookMappingHeadersId();
    }

    @Override
    public String component8() {
        return getEmailSubjectPrefix();
    }

    @Override
    public String component9() {
        return getEmailTemplate();
    }

    @Override
    public UUID component10() {
        return getWebhookCaId();
    }

    @Override
    public UUID value1() {
        return getUuid();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getMode();
    }

    @Override
    public String value4() {
        return getWebhookUrl();
    }

    @Override
    public Boolean value5() {
        return getSendOnce();
    }

    @Override
    public UUID value6() {
        return getWebhookMappingBodyId();
    }

    @Override
    public UUID value7() {
        return getWebhookMappingHeadersId();
    }

    @Override
    public String value8() {
        return getEmailSubjectPrefix();
    }

    @Override
    public String value9() {
        return getEmailTemplate();
    }

    @Override
    public UUID value10() {
        return getWebhookCaId();
    }

    @Override
    public AuthentikEventsNotificationtransportRecord value1(UUID value) {
        setUuid(value);
        return this;
    }

    @Override
    public AuthentikEventsNotificationtransportRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public AuthentikEventsNotificationtransportRecord value3(String value) {
        setMode(value);
        return this;
    }

    @Override
    public AuthentikEventsNotificationtransportRecord value4(String value) {
        setWebhookUrl(value);
        return this;
    }

    @Override
    public AuthentikEventsNotificationtransportRecord value5(Boolean value) {
        setSendOnce(value);
        return this;
    }

    @Override
    public AuthentikEventsNotificationtransportRecord value6(UUID value) {
        setWebhookMappingBodyId(value);
        return this;
    }

    @Override
    public AuthentikEventsNotificationtransportRecord value7(UUID value) {
        setWebhookMappingHeadersId(value);
        return this;
    }

    @Override
    public AuthentikEventsNotificationtransportRecord value8(String value) {
        setEmailSubjectPrefix(value);
        return this;
    }

    @Override
    public AuthentikEventsNotificationtransportRecord value9(String value) {
        setEmailTemplate(value);
        return this;
    }

    @Override
    public AuthentikEventsNotificationtransportRecord value10(UUID value) {
        setWebhookCaId(value);
        return this;
    }

    @Override
    public AuthentikEventsNotificationtransportRecord values(UUID value1, String value2, String value3, String value4, Boolean value5, UUID value6, UUID value7, String value8, String value9, UUID value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthentikEventsNotificationtransportRecord
     */
    public AuthentikEventsNotificationtransportRecord() {
        super(AuthentikEventsNotificationtransport.AUTHENTIK_EVENTS_NOTIFICATIONTRANSPORT);
    }

    /**
     * Create a detached, initialised AuthentikEventsNotificationtransportRecord
     */
    public AuthentikEventsNotificationtransportRecord(UUID uuid, String name, String mode, String webhookUrl, Boolean sendOnce, UUID webhookMappingBodyId, UUID webhookMappingHeadersId, String emailSubjectPrefix, String emailTemplate, UUID webhookCaId) {
        super(AuthentikEventsNotificationtransport.AUTHENTIK_EVENTS_NOTIFICATIONTRANSPORT);

        setUuid(uuid);
        setName(name);
        setMode(mode);
        setWebhookUrl(webhookUrl);
        setSendOnce(sendOnce);
        setWebhookMappingBodyId(webhookMappingBodyId);
        setWebhookMappingHeadersId(webhookMappingHeadersId);
        setEmailSubjectPrefix(emailSubjectPrefix);
        setEmailTemplate(emailTemplate);
        setWebhookCaId(webhookCaId);
    }
}
