/*
 * This file is generated by jOOQ.
 */
package me.aa07.paradise.taskdaemon.database.authentik.tables.records;


import java.time.OffsetDateTime;
import java.util.UUID;

import me.aa07.paradise.taskdaemon.database.authentik.tables.AuthentikEndpointsConnectorsAgentAppleindependentsecure0d47;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthentikEndpointsConnectorsAgentAppleindependentsecure0d47Record extends UpdatableRecordImpl<AuthentikEndpointsConnectorsAgentAppleindependentsecure0d47Record> implements Record10<OffsetDateTime, OffsetDateTime, String, Boolean, OffsetDateTime, UUID, String, String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>public.authentik_endpoints_connectors_agent_appleindependentsecure0d47.created</code>.
     */
    public void setCreated(OffsetDateTime value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>public.authentik_endpoints_connectors_agent_appleindependentsecure0d47.created</code>.
     */
    public OffsetDateTime getCreated() {
        return (OffsetDateTime) get(0);
    }

    /**
     * Setter for
     * <code>public.authentik_endpoints_connectors_agent_appleindependentsecure0d47.last_updated</code>.
     */
    public void setLastUpdated(OffsetDateTime value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>public.authentik_endpoints_connectors_agent_appleindependentsecure0d47.last_updated</code>.
     */
    public OffsetDateTime getLastUpdated() {
        return (OffsetDateTime) get(1);
    }

    /**
     * Setter for
     * <code>public.authentik_endpoints_connectors_agent_appleindependentsecure0d47.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>public.authentik_endpoints_connectors_agent_appleindependentsecure0d47.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>public.authentik_endpoints_connectors_agent_appleindependentsecure0d47.confirmed</code>.
     */
    public void setConfirmed(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>public.authentik_endpoints_connectors_agent_appleindependentsecure0d47.confirmed</code>.
     */
    public Boolean getConfirmed() {
        return (Boolean) get(3);
    }

    /**
     * Setter for
     * <code>public.authentik_endpoints_connectors_agent_appleindependentsecure0d47.last_used</code>.
     */
    public void setLastUsed(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>public.authentik_endpoints_connectors_agent_appleindependentsecure0d47.last_used</code>.
     */
    public OffsetDateTime getLastUsed() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for
     * <code>public.authentik_endpoints_connectors_agent_appleindependentsecure0d47.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>public.authentik_endpoints_connectors_agent_appleindependentsecure0d47.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(5);
    }

    /**
     * Setter for
     * <code>public.authentik_endpoints_connectors_agent_appleindependentsecure0d47.apple_secure_enclave_key</code>.
     */
    public void setAppleSecureEnclaveKey(String value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>public.authentik_endpoints_connectors_agent_appleindependentsecure0d47.apple_secure_enclave_key</code>.
     */
    public String getAppleSecureEnclaveKey() {
        return (String) get(6);
    }

    /**
     * Setter for
     * <code>public.authentik_endpoints_connectors_agent_appleindependentsecure0d47.apple_enclave_key_id</code>.
     */
    public void setAppleEnclaveKeyId(String value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>public.authentik_endpoints_connectors_agent_appleindependentsecure0d47.apple_enclave_key_id</code>.
     */
    public String getAppleEnclaveKeyId() {
        return (String) get(7);
    }

    /**
     * Setter for
     * <code>public.authentik_endpoints_connectors_agent_appleindependentsecure0d47.device_type</code>.
     */
    public void setDeviceType(String value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>public.authentik_endpoints_connectors_agent_appleindependentsecure0d47.device_type</code>.
     */
    public String getDeviceType() {
        return (String) get(8);
    }

    /**
     * Setter for
     * <code>public.authentik_endpoints_connectors_agent_appleindependentsecure0d47.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for
     * <code>public.authentik_endpoints_connectors_agent_appleindependentsecure0d47.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<OffsetDateTime, OffsetDateTime, String, Boolean, OffsetDateTime, UUID, String, String, String, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<OffsetDateTime, OffsetDateTime, String, Boolean, OffsetDateTime, UUID, String, String, String, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<OffsetDateTime> field1() {
        return AuthentikEndpointsConnectorsAgentAppleindependentsecure0d47.AUTHENTIK_ENDPOINTS_CONNECTORS_AGENT_APPLEINDEPENDENTSECURE0D47.CREATED;
    }

    @Override
    public Field<OffsetDateTime> field2() {
        return AuthentikEndpointsConnectorsAgentAppleindependentsecure0d47.AUTHENTIK_ENDPOINTS_CONNECTORS_AGENT_APPLEINDEPENDENTSECURE0D47.LAST_UPDATED;
    }

    @Override
    public Field<String> field3() {
        return AuthentikEndpointsConnectorsAgentAppleindependentsecure0d47.AUTHENTIK_ENDPOINTS_CONNECTORS_AGENT_APPLEINDEPENDENTSECURE0D47.NAME;
    }

    @Override
    public Field<Boolean> field4() {
        return AuthentikEndpointsConnectorsAgentAppleindependentsecure0d47.AUTHENTIK_ENDPOINTS_CONNECTORS_AGENT_APPLEINDEPENDENTSECURE0D47.CONFIRMED;
    }

    @Override
    public Field<OffsetDateTime> field5() {
        return AuthentikEndpointsConnectorsAgentAppleindependentsecure0d47.AUTHENTIK_ENDPOINTS_CONNECTORS_AGENT_APPLEINDEPENDENTSECURE0D47.LAST_USED;
    }

    @Override
    public Field<UUID> field6() {
        return AuthentikEndpointsConnectorsAgentAppleindependentsecure0d47.AUTHENTIK_ENDPOINTS_CONNECTORS_AGENT_APPLEINDEPENDENTSECURE0D47.UUID;
    }

    @Override
    public Field<String> field7() {
        return AuthentikEndpointsConnectorsAgentAppleindependentsecure0d47.AUTHENTIK_ENDPOINTS_CONNECTORS_AGENT_APPLEINDEPENDENTSECURE0D47.APPLE_SECURE_ENCLAVE_KEY;
    }

    @Override
    public Field<String> field8() {
        return AuthentikEndpointsConnectorsAgentAppleindependentsecure0d47.AUTHENTIK_ENDPOINTS_CONNECTORS_AGENT_APPLEINDEPENDENTSECURE0D47.APPLE_ENCLAVE_KEY_ID;
    }

    @Override
    public Field<String> field9() {
        return AuthentikEndpointsConnectorsAgentAppleindependentsecure0d47.AUTHENTIK_ENDPOINTS_CONNECTORS_AGENT_APPLEINDEPENDENTSECURE0D47.DEVICE_TYPE;
    }

    @Override
    public Field<Integer> field10() {
        return AuthentikEndpointsConnectorsAgentAppleindependentsecure0d47.AUTHENTIK_ENDPOINTS_CONNECTORS_AGENT_APPLEINDEPENDENTSECURE0D47.USER_ID;
    }

    @Override
    public OffsetDateTime component1() {
        return getCreated();
    }

    @Override
    public OffsetDateTime component2() {
        return getLastUpdated();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public Boolean component4() {
        return getConfirmed();
    }

    @Override
    public OffsetDateTime component5() {
        return getLastUsed();
    }

    @Override
    public UUID component6() {
        return getUuid();
    }

    @Override
    public String component7() {
        return getAppleSecureEnclaveKey();
    }

    @Override
    public String component8() {
        return getAppleEnclaveKeyId();
    }

    @Override
    public String component9() {
        return getDeviceType();
    }

    @Override
    public Integer component10() {
        return getUserId();
    }

    @Override
    public OffsetDateTime value1() {
        return getCreated();
    }

    @Override
    public OffsetDateTime value2() {
        return getLastUpdated();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public Boolean value4() {
        return getConfirmed();
    }

    @Override
    public OffsetDateTime value5() {
        return getLastUsed();
    }

    @Override
    public UUID value6() {
        return getUuid();
    }

    @Override
    public String value7() {
        return getAppleSecureEnclaveKey();
    }

    @Override
    public String value8() {
        return getAppleEnclaveKeyId();
    }

    @Override
    public String value9() {
        return getDeviceType();
    }

    @Override
    public Integer value10() {
        return getUserId();
    }

    @Override
    public AuthentikEndpointsConnectorsAgentAppleindependentsecure0d47Record value1(OffsetDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public AuthentikEndpointsConnectorsAgentAppleindependentsecure0d47Record value2(OffsetDateTime value) {
        setLastUpdated(value);
        return this;
    }

    @Override
    public AuthentikEndpointsConnectorsAgentAppleindependentsecure0d47Record value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public AuthentikEndpointsConnectorsAgentAppleindependentsecure0d47Record value4(Boolean value) {
        setConfirmed(value);
        return this;
    }

    @Override
    public AuthentikEndpointsConnectorsAgentAppleindependentsecure0d47Record value5(OffsetDateTime value) {
        setLastUsed(value);
        return this;
    }

    @Override
    public AuthentikEndpointsConnectorsAgentAppleindependentsecure0d47Record value6(UUID value) {
        setUuid(value);
        return this;
    }

    @Override
    public AuthentikEndpointsConnectorsAgentAppleindependentsecure0d47Record value7(String value) {
        setAppleSecureEnclaveKey(value);
        return this;
    }

    @Override
    public AuthentikEndpointsConnectorsAgentAppleindependentsecure0d47Record value8(String value) {
        setAppleEnclaveKeyId(value);
        return this;
    }

    @Override
    public AuthentikEndpointsConnectorsAgentAppleindependentsecure0d47Record value9(String value) {
        setDeviceType(value);
        return this;
    }

    @Override
    public AuthentikEndpointsConnectorsAgentAppleindependentsecure0d47Record value10(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public AuthentikEndpointsConnectorsAgentAppleindependentsecure0d47Record values(OffsetDateTime value1, OffsetDateTime value2, String value3, Boolean value4, OffsetDateTime value5, UUID value6, String value7, String value8, String value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached
     * AuthentikEndpointsConnectorsAgentAppleindependentsecure0d47Record
     */
    public AuthentikEndpointsConnectorsAgentAppleindependentsecure0d47Record() {
        super(AuthentikEndpointsConnectorsAgentAppleindependentsecure0d47.AUTHENTIK_ENDPOINTS_CONNECTORS_AGENT_APPLEINDEPENDENTSECURE0D47);
    }

    /**
     * Create a detached, initialised
     * AuthentikEndpointsConnectorsAgentAppleindependentsecure0d47Record
     */
    public AuthentikEndpointsConnectorsAgentAppleindependentsecure0d47Record(OffsetDateTime created, OffsetDateTime lastUpdated, String name, Boolean confirmed, OffsetDateTime lastUsed, UUID uuid, String appleSecureEnclaveKey, String appleEnclaveKeyId, String deviceType, Integer userId) {
        super(AuthentikEndpointsConnectorsAgentAppleindependentsecure0d47.AUTHENTIK_ENDPOINTS_CONNECTORS_AGENT_APPLEINDEPENDENTSECURE0D47);

        setCreated(created);
        setLastUpdated(lastUpdated);
        setName(name);
        setConfirmed(confirmed);
        setLastUsed(lastUsed);
        setUuid(uuid);
        setAppleSecureEnclaveKey(appleSecureEnclaveKey);
        setAppleEnclaveKeyId(appleEnclaveKeyId);
        setDeviceType(deviceType);
        setUserId(userId);
    }
}
