/*
 * This file is generated by jOOQ.
 */
package me.aa07.paradise.taskdaemon.database.authentik.tables.records;


import java.util.UUID;

import me.aa07.paradise.taskdaemon.database.authentik.tables.AuthentikRbacInitialpermissions;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthentikRbacInitialpermissionsRecord extends UpdatableRecordImpl<AuthentikRbacInitialpermissionsRecord> implements Record3<Integer, String, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.authentik_rbac_initialpermissions.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.authentik_rbac_initialpermissions.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.authentik_rbac_initialpermissions.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.authentik_rbac_initialpermissions.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.authentik_rbac_initialpermissions.role_id</code>.
     */
    public void setRoleId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.authentik_rbac_initialpermissions.role_id</code>.
     */
    public UUID getRoleId() {
        return (UUID) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, UUID> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, UUID> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return AuthentikRbacInitialpermissions.AUTHENTIK_RBAC_INITIALPERMISSIONS.ID;
    }

    @Override
    public Field<String> field2() {
        return AuthentikRbacInitialpermissions.AUTHENTIK_RBAC_INITIALPERMISSIONS.NAME;
    }

    @Override
    public Field<UUID> field3() {
        return AuthentikRbacInitialpermissions.AUTHENTIK_RBAC_INITIALPERMISSIONS.ROLE_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public UUID component3() {
        return getRoleId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public UUID value3() {
        return getRoleId();
    }

    @Override
    public AuthentikRbacInitialpermissionsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public AuthentikRbacInitialpermissionsRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public AuthentikRbacInitialpermissionsRecord value3(UUID value) {
        setRoleId(value);
        return this;
    }

    @Override
    public AuthentikRbacInitialpermissionsRecord values(Integer value1, String value2, UUID value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthentikRbacInitialpermissionsRecord
     */
    public AuthentikRbacInitialpermissionsRecord() {
        super(AuthentikRbacInitialpermissions.AUTHENTIK_RBAC_INITIALPERMISSIONS);
    }

    /**
     * Create a detached, initialised AuthentikRbacInitialpermissionsRecord
     */
    public AuthentikRbacInitialpermissionsRecord(Integer id, String name, UUID roleId) {
        super(AuthentikRbacInitialpermissions.AUTHENTIK_RBAC_INITIALPERMISSIONS);

        setId(id);
        setName(name);
        setRoleId(roleId);
    }
}
