/*
 * This file is generated by jOOQ.
 */
package me.aa07.paradise.taskdaemon.database.authentik.tables.records;


import java.util.UUID;

import me.aa07.paradise.taskdaemon.database.authentik.tables.AuthentikFlowsStage;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthentikFlowsStageRecord extends UpdatableRecordImpl<AuthentikFlowsStageRecord> implements Record2<UUID, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.authentik_flows_stage.stage_uuid</code>.
     */
    public void setStageUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.authentik_flows_stage.stage_uuid</code>.
     */
    public UUID getStageUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.authentik_flows_stage.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.authentik_flows_stage.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<UUID, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return AuthentikFlowsStage.AUTHENTIK_FLOWS_STAGE.STAGE_UUID;
    }

    @Override
    public Field<String> field2() {
        return AuthentikFlowsStage.AUTHENTIK_FLOWS_STAGE.NAME;
    }

    @Override
    public UUID component1() {
        return getStageUuid();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public UUID value1() {
        return getStageUuid();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public AuthentikFlowsStageRecord value1(UUID value) {
        setStageUuid(value);
        return this;
    }

    @Override
    public AuthentikFlowsStageRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public AuthentikFlowsStageRecord values(UUID value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthentikFlowsStageRecord
     */
    public AuthentikFlowsStageRecord() {
        super(AuthentikFlowsStage.AUTHENTIK_FLOWS_STAGE);
    }

    /**
     * Create a detached, initialised AuthentikFlowsStageRecord
     */
    public AuthentikFlowsStageRecord(UUID stageUuid, String name) {
        super(AuthentikFlowsStage.AUTHENTIK_FLOWS_STAGE);

        setStageUuid(stageUuid);
        setName(name);
    }
}
