/*
 * This file is generated by jOOQ.
 */
package me.aa07.paradise.taskdaemon.database.authentik.tables.records;


import java.util.UUID;

import me.aa07.paradise.taskdaemon.database.authentik.tables.AuthentikStagesAuthenticatorValidateAuthenticatorvalida8318;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthentikStagesAuthenticatorValidateAuthenticatorvalida8318Record extends UpdatableRecordImpl<AuthentikStagesAuthenticatorValidateAuthenticatorvalida8318Record> implements Record3<Integer, UUID, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>public.authentik_stages_authenticator_validate_authenticatorvalida8318.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>public.authentik_stages_authenticator_validate_authenticatorvalida8318.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for
     * <code>public.authentik_stages_authenticator_validate_authenticatorvalida8318.authenticatorvalidatestage_id</code>.
     */
    public void setAuthenticatorvalidatestageId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>public.authentik_stages_authenticator_validate_authenticatorvalida8318.authenticatorvalidatestage_id</code>.
     */
    public UUID getAuthenticatorvalidatestageId() {
        return (UUID) get(1);
    }

    /**
     * Setter for
     * <code>public.authentik_stages_authenticator_validate_authenticatorvalida8318.webauthndevicetype_id</code>.
     */
    public void setWebauthndevicetypeId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>public.authentik_stages_authenticator_validate_authenticatorvalida8318.webauthndevicetype_id</code>.
     */
    public UUID getWebauthndevicetypeId() {
        return (UUID) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, UUID, UUID> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, UUID, UUID> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return AuthentikStagesAuthenticatorValidateAuthenticatorvalida8318.AUTHENTIK_STAGES_AUTHENTICATOR_VALIDATE_AUTHENTICATORVALIDA8318.ID;
    }

    @Override
    public Field<UUID> field2() {
        return AuthentikStagesAuthenticatorValidateAuthenticatorvalida8318.AUTHENTIK_STAGES_AUTHENTICATOR_VALIDATE_AUTHENTICATORVALIDA8318.AUTHENTICATORVALIDATESTAGE_ID;
    }

    @Override
    public Field<UUID> field3() {
        return AuthentikStagesAuthenticatorValidateAuthenticatorvalida8318.AUTHENTIK_STAGES_AUTHENTICATOR_VALIDATE_AUTHENTICATORVALIDA8318.WEBAUTHNDEVICETYPE_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getAuthenticatorvalidatestageId();
    }

    @Override
    public UUID component3() {
        return getWebauthndevicetypeId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getAuthenticatorvalidatestageId();
    }

    @Override
    public UUID value3() {
        return getWebauthndevicetypeId();
    }

    @Override
    public AuthentikStagesAuthenticatorValidateAuthenticatorvalida8318Record value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public AuthentikStagesAuthenticatorValidateAuthenticatorvalida8318Record value2(UUID value) {
        setAuthenticatorvalidatestageId(value);
        return this;
    }

    @Override
    public AuthentikStagesAuthenticatorValidateAuthenticatorvalida8318Record value3(UUID value) {
        setWebauthndevicetypeId(value);
        return this;
    }

    @Override
    public AuthentikStagesAuthenticatorValidateAuthenticatorvalida8318Record values(Integer value1, UUID value2, UUID value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached
     * AuthentikStagesAuthenticatorValidateAuthenticatorvalida8318Record
     */
    public AuthentikStagesAuthenticatorValidateAuthenticatorvalida8318Record() {
        super(AuthentikStagesAuthenticatorValidateAuthenticatorvalida8318.AUTHENTIK_STAGES_AUTHENTICATOR_VALIDATE_AUTHENTICATORVALIDA8318);
    }

    /**
     * Create a detached, initialised
     * AuthentikStagesAuthenticatorValidateAuthenticatorvalida8318Record
     */
    public AuthentikStagesAuthenticatorValidateAuthenticatorvalida8318Record(Integer id, UUID authenticatorvalidatestageId, UUID webauthndevicetypeId) {
        super(AuthentikStagesAuthenticatorValidateAuthenticatorvalida8318.AUTHENTIK_STAGES_AUTHENTICATOR_VALIDATE_AUTHENTICATORVALIDA8318);

        setId(id);
        setAuthenticatorvalidatestageId(authenticatorvalidatestageId);
        setWebauthndevicetypeId(webauthndevicetypeId);
    }
}
