/*
 * This file is generated by jOOQ.
 */
package me.aa07.paradise.taskdaemon.database.authentik.tables.records;


import me.aa07.paradise.taskdaemon.database.authentik.tables.AuthentikSourcesSamlGroupsamlsourceconnection;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthentikSourcesSamlGroupsamlsourceconnectionRecord extends UpdatableRecordImpl<AuthentikSourcesSamlGroupsamlsourceconnectionRecord> implements Record1<Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>public.authentik_sources_saml_groupsamlsourceconnection.groupsourceconnection_ptr_id</code>.
     */
    public void setGroupsourceconnectionPtrId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>public.authentik_sources_saml_groupsamlsourceconnection.groupsourceconnection_ptr_id</code>.
     */
    public Integer getGroupsourceconnectionPtrId() {
        return (Integer) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<Integer> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<Integer> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return AuthentikSourcesSamlGroupsamlsourceconnection.AUTHENTIK_SOURCES_SAML_GROUPSAMLSOURCECONNECTION.GROUPSOURCECONNECTION_PTR_ID;
    }

    @Override
    public Integer component1() {
        return getGroupsourceconnectionPtrId();
    }

    @Override
    public Integer value1() {
        return getGroupsourceconnectionPtrId();
    }

    @Override
    public AuthentikSourcesSamlGroupsamlsourceconnectionRecord value1(Integer value) {
        setGroupsourceconnectionPtrId(value);
        return this;
    }

    @Override
    public AuthentikSourcesSamlGroupsamlsourceconnectionRecord values(Integer value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthentikSourcesSamlGroupsamlsourceconnectionRecord
     */
    public AuthentikSourcesSamlGroupsamlsourceconnectionRecord() {
        super(AuthentikSourcesSamlGroupsamlsourceconnection.AUTHENTIK_SOURCES_SAML_GROUPSAMLSOURCECONNECTION);
    }

    /**
     * Create a detached, initialised
     * AuthentikSourcesSamlGroupsamlsourceconnectionRecord
     */
    public AuthentikSourcesSamlGroupsamlsourceconnectionRecord(Integer groupsourceconnectionPtrId) {
        super(AuthentikSourcesSamlGroupsamlsourceconnection.AUTHENTIK_SOURCES_SAML_GROUPSAMLSOURCECONNECTION);

        setGroupsourceconnectionPtrId(groupsourceconnectionPtrId);
    }
}
