/*
 * This file is generated by jOOQ.
 */
package me.aa07.paradise.taskdaemon.database.authentik.tables.records;


import java.util.UUID;

import me.aa07.paradise.taskdaemon.database.authentik.tables.AuthentikSourcesPlexPlexsourcepropertymapping;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthentikSourcesPlexPlexsourcepropertymappingRecord extends UpdatableRecordImpl<AuthentikSourcesPlexPlexsourcepropertymappingRecord> implements Record1<UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>public.authentik_sources_plex_plexsourcepropertymapping.propertymapping_ptr_id</code>.
     */
    public void setPropertymappingPtrId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>public.authentik_sources_plex_plexsourcepropertymapping.propertymapping_ptr_id</code>.
     */
    public UUID getPropertymappingPtrId() {
        return (UUID) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<UUID> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<UUID> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return AuthentikSourcesPlexPlexsourcepropertymapping.AUTHENTIK_SOURCES_PLEX_PLEXSOURCEPROPERTYMAPPING.PROPERTYMAPPING_PTR_ID;
    }

    @Override
    public UUID component1() {
        return getPropertymappingPtrId();
    }

    @Override
    public UUID value1() {
        return getPropertymappingPtrId();
    }

    @Override
    public AuthentikSourcesPlexPlexsourcepropertymappingRecord value1(UUID value) {
        setPropertymappingPtrId(value);
        return this;
    }

    @Override
    public AuthentikSourcesPlexPlexsourcepropertymappingRecord values(UUID value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthentikSourcesPlexPlexsourcepropertymappingRecord
     */
    public AuthentikSourcesPlexPlexsourcepropertymappingRecord() {
        super(AuthentikSourcesPlexPlexsourcepropertymapping.AUTHENTIK_SOURCES_PLEX_PLEXSOURCEPROPERTYMAPPING);
    }

    /**
     * Create a detached, initialised
     * AuthentikSourcesPlexPlexsourcepropertymappingRecord
     */
    public AuthentikSourcesPlexPlexsourcepropertymappingRecord(UUID propertymappingPtrId) {
        super(AuthentikSourcesPlexPlexsourcepropertymapping.AUTHENTIK_SOURCES_PLEX_PLEXSOURCEPROPERTYMAPPING);

        setPropertymappingPtrId(propertymappingPtrId);
    }
}
